// Auto-generated C wrapper for Fortran function: ComputeUA360_AttachedFlow
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

#include "vit_kernel_callees.h"

// User-provided C++ implementation
#include "computeua360_attachedflow.hpp"

extern "C" {
    void computeua360_attachedflow_c(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl, int* iLower, int* iUpper) {
        ComputeUA360_AttachedFlow(p, ColUAf, cn_cl, n_cn_cl, iLower, iUpper);
    }
}
