// Auto-generated C wrapper for Fortran function: Calculate_Cn
// Generated by VIT (Verified Incremental Translator)

// User-provided C++ implementation
#include "calculate_cn.hpp"

extern "C" {
    void calculate_cn_c(double* alpha, int n_alpha, double* Cl, int n_Cl, double* Cd, int n_Cd, double Cd0, double* Calculate_Cn_result) {
        Calculate_Cn(alpha, n_alpha, Cl, n_Cl, Cd, n_Cd, Cd0, Calculate_Cn_result);
    }
}
