// Auto-generated C wrapper for Fortran function: ComputeUA360_updateSeparationF
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

#include "vit_kernel_callees.h"

// User-provided C++ implementation
#include "computeua360_updateseparationf.hpp"

extern "C" {
    void computeua360_updateseparationf_c(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl, int iLower, int iUpper) {
        ComputeUA360_updateSeparationF(p, ColUAf, cn_cl, n_cn_cl, iLower, iUpper);
    }
}
