// Auto-generated C wrapper for Fortran function: ComputeUASeparationFunction_zero
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

// User-provided C++ implementation
#include "computeuaseparationfunction_zero.hpp"

extern "C" {
    void computeuaseparationfunction_zero_c(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl) {
        ComputeUASeparationFunction_zero(p, ColUAf, cn_cl, n_cn_cl);
    }
}
