// Auto-generated C wrapper for Fortran function: CalculateUACoeffs
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

#include "vit_kernel_callees.h"

// User-provided C++ implementation
#include "calculateuacoeffs.hpp"

extern "C" {
    void calculateuacoeffs_c(afi_ua_bl_default_type_t* CalcDefaults, afi_table_type_view_t* p, int ColCl, int ColCd, int ColCm, int ColUAf, int UAMod) {
        CalculateUACoeffs(CalcDefaults, p, ColCl, ColCd, ColCm, ColUAf, UAMod);
    }
}
