// Auto-generated C wrapper for Fortran function: AFI_ComputeAirfoilCoefs
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

#include "vit_kernel_callees.h"

// User-provided C++ implementation
#include "afi_computeairfoilcoefs.hpp"

extern "C" {
    void afi_computeairfoilcoefs_c(double AOA, double Re, double UserProp, afi_parametertype_view_t* p, afi_outputtype_t* AFI_interp, int* errStat, char* errMsg) {
        AFI_ComputeAirfoilCoefs(AOA, Re, UserProp, p, AFI_interp, errStat, errMsg);
    }
}
