!KGEN-generated Fortran source file 
  
!Generated at : 2026-04-26 16:01:24 
!KGEN version : 0.8.1 
  
!STARTOFREGISTRYGENERATEDFILE 'DBEMT_Types.f90'
! WARNING This file is generated automatically by the FAST registry.
! Do not edit.  Your changes to this file will be lost.
! FAST Registry
!*********************************************************************************************************************************
! DBEMT_Types
!.................................................................................................................................
! This file is part of DBEMT.
! Copyright (C) 2012-2016 National Renewable Energy Laboratory
! Licensed under the Apache License, Version 2.0 (the "License");
! you may not use this file except in compliance with the License.
! You may obtain a copy of the License at
!     http://www.apache.org/licenses/LICENSE-2.0
! Unless required by applicable law or agreed to in writing, software
! distributed under the License is distributed on an "AS IS" BASIS,
! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
! See the License for the specific language governing permissions and
! limitations under the License.
! W A R N I N G : This file was automatically generated from the FAST registry.  Changes made to this file may be lost.
!*********************************************************************************************************************************
!> This module contains the user-defined types needed in DBEMT. It also contains copy, destroy, pack, and
!! unpack routines associated with each defined data type. This code is automatically generated by the FAST Registry.


!
!
!
!
!
!
!
!
!
MODULE DBEMT_Types
!---------------------------------------------------------------------------------------------------------------------------------
    USE nwtc_library 
    USE kgen_utils_mod
    USE tprof_mod, ONLY: tstart, tstop, tnull, tprnt 
    USE kgen_utils_mod
    IMPLICIT NONE 
! =========  DBEMT_InitInputType  =======

! =======================
! =========  DBEMT_InitOutputType  =======

! =======================
! =========  DBEMT_ElementContinuousStateType  =======

! =======================
! =========  DBEMT_ContinuousStateType  =======

! =======================
! =========  DBEMT_DiscreteStateType  =======

! =======================
! =========  DBEMT_ConstraintStateType  =======

! =======================
! =========  DBEMT_OtherStateType  =======

! =======================
! =========  DBEMT_MiscVarType  =======

! =======================
! =========  DBEMT_ParameterType  =======
  TYPE, PUBLIC :: DBEMT_ParameterType
    REAL(DbKi)  :: DT = 0.0_R8Ki      !< Time step for continuous state integration & discrete state update [seconds]
    INTEGER(IntKi)  :: lin_nx = 0      !< Number of continuous states for linearization [-]
    INTEGER(IntKi)  :: NumBlades = 0_IntKi      !< Number of blades on the turbine [-]
    INTEGER(IntKi)  :: NumNodes = 0_IntKi      !< Number of nodes on each blade [-]
    REAL(ReKi)  :: k_0ye = 0.0_ReKi      !< Filter dynamics constant [default = 0.6 ] [-]
    REAL(ReKi)  :: tau1_const = 0.0_ReKi      !< constant version of the delay value [-]
    REAL(ReKi) , DIMENSION(:,:), ALLOCATABLE  :: spanRatio      !< static span ratio of each blade node [-]
    INTEGER(IntKi)  :: DBEMT_Mod = 0_IntKi      !< DBEMT Model.  1 = constant tau1, 2 = time dependent tau1, 3=continuous form of constant tau1 [-]
  END TYPE DBEMT_ParameterType
! =======================
! =========  DBEMT_ElementInputType  =======

! =======================
! =========  DBEMT_InputType  =======

! =======================
! =========  DBEMT_OutputType  =======

! =======================
  PUBLIC kr_dbemt_types_dbemt_parametertype 
  PUBLIC kv_dbemt_types_dbemt_parametertype 

    
  CONTAINS 
    


  !read state subroutine for kr_dbemt_types_dbemt_parametertype 
  RECURSIVE SUBROUTINE kr_dbemt_types_dbemt_parametertype(var, kgen_unit, printname, printvar) 
      TYPE(dbemt_parametertype), INTENT(INOUT) :: var 
      INTEGER, INTENT(IN) :: kgen_unit 
      CHARACTER(LEN=*), INTENT(IN) :: printname 
      LOGICAL, INTENT(IN), OPTIONAL :: printvar 
      LOGICAL :: kgen_istrue 
      REAL(KIND=8) :: kgen_array_sum 
        
      READ (UNIT = kgen_unit) var%dt 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%dt = ", var%dt 
      END IF   
        
      READ (UNIT = kgen_unit) var%lin_nx 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%lin_nx = ", var%lin_nx 
      END IF   
        
      READ (UNIT = kgen_unit) var%numblades 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%numblades = ", var%numblades 
      END IF   
        
      READ (UNIT = kgen_unit) var%numnodes 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%numnodes = ", var%numnodes 
      END IF   
        
      READ (UNIT = kgen_unit) var%k_0ye 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%k_0ye = ", var%k_0ye 
      END IF   
        
      READ (UNIT = kgen_unit) var%tau1_const 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%tau1_const = ", var%tau1_const 
      END IF   
        
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          CALL kr_dbemt_parametertype_real__reki_dim2(var%spanratio, kgen_unit, printname // "%spanratio", .TRUE.) 
      ELSE 
          CALL kr_dbemt_parametertype_real__reki_dim2(var%spanratio, kgen_unit, printname // "%spanratio", .FALSE.) 
      END IF   
        
      READ (UNIT = kgen_unit) var%dbemt_mod 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%dbemt_mod = ", var%dbemt_mod 
      END IF   
        
  END SUBROUTINE kr_dbemt_types_dbemt_parametertype 
    
  !write state subroutine for kr_dbemt_parametertype_real__reki_dim2 
  SUBROUTINE kr_dbemt_parametertype_real__reki_dim2(var, kgen_unit, printname, printvar) 
      REAL(KIND=reki), INTENT(INOUT), ALLOCATABLE, DIMENSION(:,:) :: var 
      INTEGER, INTENT(IN) :: kgen_unit 
      CHARACTER(LEN=*), INTENT(IN) :: printname 
      LOGICAL, INTENT(IN), OPTIONAL :: printvar 
      LOGICAL :: kgen_istrue 
      REAL(KIND=8) :: kgen_array_sum 
      INTEGER :: idx1, idx2 
      INTEGER, DIMENSION(2,2) :: kgen_bound 
        
      READ (UNIT = kgen_unit) kgen_istrue 
      IF (kgen_istrue) THEN 
          IF (ALLOCATED( var )) THEN 
              DEALLOCATE (var) 
          END IF   
          READ (UNIT = kgen_unit) kgen_array_sum 
          READ (UNIT = kgen_unit) kgen_bound(1, 1) 
          READ (UNIT = kgen_unit) kgen_bound(2, 1) 
          READ (UNIT = kgen_unit) kgen_bound(1, 2) 
          READ (UNIT = kgen_unit) kgen_bound(2, 2) 
          ALLOCATE (var(kgen_bound(1,1):kgen_bound(2,1), kgen_bound(1,2):kgen_bound(2,2))) 
          READ (UNIT = kgen_unit) var 
          CALL kgen_array_sumcheck(printname, kgen_array_sum, DBLE(SUM(var, mask=(var .eq. var))), .TRUE.) 
          IF (PRESENT( printvar ) .AND. printvar) THEN 
              WRITE (*, *) "KGEN DEBUG: DBLE(SUM(" // printname // ")) = ", DBLE(SUM(var, mask=(var .eq. var))) 
          END IF   
      END IF   
        
  END SUBROUTINE kr_dbemt_parametertype_real__reki_dim2 
    
  !verify state subroutine for kv_dbemt_types_dbemt_parametertype 
  RECURSIVE SUBROUTINE kv_dbemt_types_dbemt_parametertype(varname, check_status, var, kgenref_var) 
      CHARACTER(LEN=*), INTENT(IN) :: varname 
      TYPE(check_t), INTENT(INOUT) :: check_status 
      TYPE(dbemt_parametertype), INTENT(IN) :: var, kgenref_var 
      TYPE(check_t) :: dtype_check_status, comp_check_status 
      INTEGER :: check_result 
      LOGICAL :: is_print = .FALSE. 
        
      real(KIND=dbki) :: diff_dt 
      integer(KIND=intki) :: diff_lin_nx 
      integer(KIND=intki) :: diff_numblades 
      integer(KIND=intki) :: diff_numnodes 
      real(KIND=reki) :: diff_k_0ye 
      real(KIND=reki) :: diff_tau1_const 
      INTEGER :: n_spanratio 
      real(KIND=reki) :: nrmsdiff_spanratio, rmsdiff_spanratio 
      real(KIND=reki), ALLOCATABLE :: buf1_spanratio(:,:), buf2_spanratio(:,:) 
      integer(KIND=intki) :: diff_dbemt_mod 
        
      check_status%numTotal = check_status%numTotal + 1 
        
      CALL kgen_init_check(dtype_check_status, rank=check_status%rank) 
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%dt == kgenref_var%dt) .OR. ((var%dt /= var%dt) .AND. (kgenref_var%dt /= kgenref_var%dt))) THEN
        IF (var%dt /= var%dt) WRITE(*, *) "localvar%dt is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%dt is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_dt = ABS(var%dt - kgenref_var%dt) 
          IF (diff_dt <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%dt is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%dt is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_dt 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_dt 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%lin_nx == kgenref_var%lin_nx) .OR. ((var%lin_nx /= var%lin_nx) .AND. (kgenref_var%lin_nx /= kgenref_var%lin_nx))) THEN
        IF (var%lin_nx /= var%lin_nx) WRITE(*, *) "localvar%lin_nx is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%lin_nx is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_lin_nx = ABS(var%lin_nx - kgenref_var%lin_nx) 
          IF (diff_lin_nx <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%lin_nx is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%lin_nx is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_lin_nx 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_lin_nx 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%numblades == kgenref_var%numblades) .OR. ((var%numblades /= var%numblades) .AND. (kgenref_var%numblades /= kgenref_var%numblades))) THEN
        IF (var%numblades /= var%numblades) WRITE(*, *) "localvar%numblades is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%numblades is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_numblades = ABS(var%numblades - kgenref_var%numblades) 
          IF (diff_numblades <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%numblades is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%numblades is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_numblades 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_numblades 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%numnodes == kgenref_var%numnodes) .OR. ((var%numnodes /= var%numnodes) .AND. (kgenref_var%numnodes /= kgenref_var%numnodes))) THEN
        IF (var%numnodes /= var%numnodes) WRITE(*, *) "localvar%numnodes is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%numnodes is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_numnodes = ABS(var%numnodes - kgenref_var%numnodes) 
          IF (diff_numnodes <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%numnodes is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%numnodes is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_numnodes 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_numnodes 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%k_0ye == kgenref_var%k_0ye) .OR. ((var%k_0ye /= var%k_0ye) .AND. (kgenref_var%k_0ye /= kgenref_var%k_0ye))) THEN
        IF (var%k_0ye /= var%k_0ye) WRITE(*, *) "localvar%k_0ye is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%k_0ye is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_k_0ye = ABS(var%k_0ye - kgenref_var%k_0ye) 
          IF (diff_k_0ye <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%k_0ye is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%k_0ye is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_k_0ye 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_k_0ye 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%tau1_const == kgenref_var%tau1_const) .OR. ((var%tau1_const /= var%tau1_const) .AND. (kgenref_var%tau1_const /= kgenref_var%tau1_const))) THEN
        IF (var%tau1_const /= var%tau1_const) WRITE(*, *) "localvar%tau1_const is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%tau1_const is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_tau1_const = ABS(var%tau1_const - kgenref_var%tau1_const) 
          IF (diff_tau1_const <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%tau1_const is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%tau1_const is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_tau1_const 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_tau1_const 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      IF (ALLOCATED(var%spanratio)) THEN 
          dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
          IF (ALL(var%spanratio == kgenref_var%spanratio)) THEN 
              dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%spanratio is IDENTICAL." 
                  END IF   
              END IF   
              check_result = CHECK_IDENTICAL 
          ELSE 
              ALLOCATE (buf1_spanratio(SIZE(var%spanratio,dim=1),SIZE(var%spanratio,dim=2))) 
              ALLOCATE (buf2_spanratio(SIZE(var%spanratio,dim=1),SIZE(var%spanratio,dim=2))) 
              n_spanratio = COUNT(var%spanratio /= kgenref_var%spanratio) 
              WHERE ( ABS(kgenref_var%spanratio) > kgen_minvalue ) 
                  buf1_spanratio = ((var%spanratio-kgenref_var%spanratio)/kgenref_var%spanratio)**2 
                  buf2_spanratio = (var%spanratio-kgenref_var%spanratio)**2 
              ELSEWHERE 
                  buf1_spanratio = (var%spanratio-kgenref_var%spanratio)**2 
                  buf2_spanratio = buf1_spanratio 
              END WHERE   
              nrmsdiff_spanratio = SQRT(SUM(buf1_spanratio)/REAL(n_spanratio)) 
              rmsdiff_spanratio = SQRT(SUM(buf2_spanratio)/REAL(n_spanratio)) 
              IF (rmsdiff_spanratio > kgen_tolerance) THEN 
                  dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
                  IF (kgen_verboseLevel > 1) THEN 
                      IF (check_status%rank == 0) THEN 
                          WRITE (*, *) trim(adjustl(varname)), "%spanratio is NOT IDENTICAL(out of tolerance)." 
                      END IF   
                  END IF   
                  check_result = CHECK_OUT_TOL 
              ELSE 
                  dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
                  IF (kgen_verboseLevel > 1) THEN 
                      IF (check_status%rank == 0) THEN 
                          WRITE (*, *) trim(adjustl(varname)), "%spanratio is NOT IDENTICAL(within tolerance)." 
                      END IF   
                  END IF   
                  check_result = CHECK_IN_TOL 
              END IF   
          END IF   
          IF (check_result == CHECK_IDENTICAL) THEN 
              CONTINUE 
          ELSE IF (check_result == CHECK_OUT_TOL) THEN 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank ==0) THEN 
                      WRITE (*, *) count( var%spanratio /= kgenref_var%spanratio), " of ", size( var%spanratio ), " elements are &
                      &different." 
                      WRITE (*, *) "Average - kernel ", sum(var%spanratio)/real(size(var%spanratio)) 
                      WRITE (*, *) "Average - reference ", sum(kgenref_var%spanratio)/real(size(kgenref_var%spanratio)) 
                      WRITE (*, *) "RMS of difference is ", rmsdiff_spanratio 
                      WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_spanratio 
                      WRITE (*, *) "" 
                  END IF   
              END IF   
          ELSE IF (check_result == CHECK_IN_TOL) THEN 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank ==0) THEN 
                      WRITE (*, *) count( var%spanratio /= kgenref_var%spanratio), " of ", size( var%spanratio ), " elements are &
                      &different." 
                      WRITE (*, *) "Average - kernel ", sum(var%spanratio)/real(size(var%spanratio)) 
                      WRITE (*, *) "Average - reference ", sum(kgenref_var%spanratio)/real(size(kgenref_var%spanratio)) 
                      WRITE (*, *) "RMS of difference is ", rmsdiff_spanratio 
                      WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_spanratio 
                      WRITE (*, *) "" 
                  END IF   
              END IF   
          END IF   
            
      END IF   
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%dbemt_mod == kgenref_var%dbemt_mod) .OR. ((var%dbemt_mod /= var%dbemt_mod) .AND. (kgenref_var%dbemt_mod /= kgenref_var%dbemt_mod))) THEN
        IF (var%dbemt_mod /= var%dbemt_mod) WRITE(*, *) "localvar%dbemt_mod is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%dbemt_mod is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_dbemt_mod = ABS(var%dbemt_mod - kgenref_var%dbemt_mod) 
          IF (diff_dbemt_mod <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%dbemt_mod is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%dbemt_mod is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_dbemt_mod 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_dbemt_mod 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      IF (dtype_check_status%numTotal == dtype_check_status%numIdentical) THEN 
          check_status%numIdentical = check_status%numIdentical + 1 
      ELSE IF (dtype_check_status%numOutTol > 0) THEN 
          check_status%numOutTol = check_status%numOutTol + 1 
      ELSE IF (dtype_check_status%numInTol > 0) THEN 
          check_status%numInTol = check_status%numInTol + 1 
      END IF   
  END SUBROUTINE kv_dbemt_types_dbemt_parametertype 
    
END MODULE DBEMT_Types
!ENDOFREGISTRYGENERATEDFILE
