!KGEN-generated Fortran source file 
  
!Generated at : 2026-04-26 16:01:24 
!KGEN version : 0.8.1 
  
!STARTOFREGISTRYGENERATEDFILE 'NWTC_Library_Types.f90'
! WARNING This file is generated automatically by the FAST registry.
! Do not edit.  Your changes to this file will be lost.
! FAST Registry
!*********************************************************************************************************************************
! NWTC_Library_Types
!.................................................................................................................................
! This file is part of NWTC_Library.
! Copyright (C) 2012-2016 National Renewable Energy Laboratory
! Licensed under the Apache License, Version 2.0 (the "License");
! you may not use this file except in compliance with the License.
! You may obtain a copy of the License at
!     http://www.apache.org/licenses/LICENSE-2.0
! Unless required by applicable law or agreed to in writing, software
! distributed under the License is distributed on an "AS IS" BASIS,
! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
! See the License for the specific language governing permissions and
! limitations under the License.
! W A R N I N G : This file was automatically generated from the FAST registry.  Changes made to this file may be lost.
!*********************************************************************************************************************************
!> This module contains the user-defined types needed in NWTC_Library. It also contains copy, destroy, pack, and
!! unpack routines associated with each defined data type. This code is automatically generated by the FAST Registry.


!
!
!
!
!
!
!
!
!
MODULE NWTC_Library_Types
!---------------------------------------------------------------------------------------------------------------------------------
    USE precision 
    USE syssubs 
    USE kgen_utils_mod
    USE tprof_mod, ONLY: tstart, tstop, tnull, tprnt 
    IMPLICIT NONE 
! =========  ProgDesc  =======

! =======================
! =========  FASTdataType  =======

! =======================
! =========  OutParmType  =======

! =======================
! =========  FileInfoType  =======

! =======================
! =========  Quaternion  =======

! =======================
! =========  NWTC_RandomNumber_ParameterType  =======

! =======================
! =========  DatLoc  =======

! =======================
! =========  ModVarType  =======

! =======================
! =========  ModVarsType  =======

! =======================
! =========  ModJacType  =======

! =======================
! =========  ModLinType  =======

! =======================
! =========  ModDataType  =======

! =======================
! =========  KdTreeType  =======

! =======================


END MODULE NWTC_Library_Types
!ENDOFREGISTRYGENERATEDFILE
