!KGEN-generated Fortran source file 
  
!Generated at : 2026-04-26 16:01:24 
!KGEN version : 0.8.1 
  
!STARTOFREGISTRYGENERATEDFILE 'UnsteadyAero_Types.f90'
! WARNING This file is generated automatically by the FAST registry.
! Do not edit.  Your changes to this file will be lost.
! FAST Registry
!*********************************************************************************************************************************
! UnsteadyAero_Types
!.................................................................................................................................
! This file is part of UnsteadyAero.
! Copyright (C) 2012-2016 National Renewable Energy Laboratory
! Licensed under the Apache License, Version 2.0 (the "License");
! you may not use this file except in compliance with the License.
! You may obtain a copy of the License at
!     http://www.apache.org/licenses/LICENSE-2.0
! Unless required by applicable law or agreed to in writing, software
! distributed under the License is distributed on an "AS IS" BASIS,
! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
! See the License for the specific language governing permissions and
! limitations under the License.
! W A R N I N G : This file was automatically generated from the FAST registry.  Changes made to this file may be lost.
!*********************************************************************************************************************************
!> This module contains the user-defined types needed in UnsteadyAero. It also contains copy, destroy, pack, and
!! unpack routines associated with each defined data type. This code is automatically generated by the FAST Registry.


!
!
!
!
!
!
!
!
!
MODULE UnsteadyAero_Types
!---------------------------------------------------------------------------------------------------------------------------------
    USE airfoilinfo_types 
    USE kgen_utils_mod
    USE tprof_mod, ONLY: tstart, tstop, tnull, tprnt 
    USE kgen_utils_mod
    IMPLICIT NONE 
! =========  UA_InitInputType  =======

! =======================
! =========  UA_InitOutputType  =======

! =======================
! =========  UA_KelvinChainType  =======

! =======================
! =========  UA_ElementContinuousStateType  =======

! =======================
! =========  UA_ContinuousStateType  =======

! =======================
! =========  UA_DiscreteStateType  =======

! =======================
! =========  UA_ConstraintStateType  =======

! =======================
! =========  UA_OtherStateType  =======

! =======================
! =========  UA_MiscVarType  =======

! =======================
! =========  UA_ParameterType  =======
  TYPE, PUBLIC :: UA_ParameterType
    REAL(DbKi)  :: dt = 0.0_R8Ki      !< time step [s]
    REAL(ReKi) , DIMENSION(:,:), ALLOCATABLE  :: c      !< Chord length at node [m]
    REAL(ReKi)  :: d_34_to_ac = 0.5      !< Distance from 3/4 chord to aerodynamic center (typically 0.5) in chord length (no dimension) [-]
    INTEGER(IntKi)  :: numBlades = 0_IntKi      !< Number nodes of all blades [-]
    INTEGER(IntKi)  :: nNodesPerBlade = 0_IntKi      !< Number nodes per blades [-]
    INTEGER(IntKi)  :: UAMod = 0_IntKi      !< Model for the dynamic stall equations [1 = Leishman/Beddoes, 2 = Gonzalez, 3 = Minnema] [-]
    LOGICAL  :: Flookup = .false.      !< Use table lookup for f' and f''  [-]
    REAL(ReKi)  :: a_s = 0.0_ReKi      !< speed of sound [m/s]
    INTEGER(IntKi)  :: NumOuts = 0      !< Number of outputs [-]
    INTEGER(IntKi)  :: OutSwtch = 0_IntKi      !< Output requested channels to: [1=Unsteady.out 2=GlueCode.out  3=both files] [-]
    CHARACTER(20)  :: OutFmt      !< Output format for numerical results [-]
    CHARACTER(20)  :: OutSFmt      !< Output format for header strings [-]
    CHARACTER(1)  :: Delim      !< Delimiter string for outputs, defaults to tab-delimiters [-]
    INTEGER(IntKi)  :: UnOutFile = 0      !< File unit for the UnsteadyAero outputs [-]
    LOGICAL  :: ShedEffect = .false.      !< Include the effect of shed vorticity. If False, the input alpha is assumed to already contain this effect (e.g. vortex methods) [-]
    INTEGER(IntKi)  :: lin_nx = 0      !< Number of continuous states for linearization [-]
    LOGICAL , DIMENSION(:,:), ALLOCATABLE  :: UA_off_forGood      !< logical flag indicating if UA is off for good [-]
    INTEGER(IntKi) , DIMENSION(:,:), ALLOCATABLE  :: lin_xIndx      !< array to indicate which state to perturb for UA [-]
    REAL(R8Ki) , DIMENSION(1:7)  :: dx = 0.0_R8Ki      !< array to indicate size of state perturbations (x array) [-]
    INTEGER(IntKi)  :: UA_OUTS = 0      !< Store write outputs 0=None, 1=WriteOutpus, 2=WriteToFile [-]
    INTEGER(IntKi)  :: integrationMethod = 3      !< method to integrate states [-]
  END TYPE UA_ParameterType
! =======================
! =========  UA_InputType  =======

! =======================
! =========  UA_OutputType  =======

! =======================
  PUBLIC kr_unsteadyaero_types_ua_parametertype 
  PUBLIC kv_unsteadyaero_types_ua_parametertype 

    
  CONTAINS 
    


  !read state subroutine for kr_unsteadyaero_types_ua_parametertype 
  RECURSIVE SUBROUTINE kr_unsteadyaero_types_ua_parametertype(var, kgen_unit, printname, printvar) 
      TYPE(ua_parametertype), INTENT(INOUT) :: var 
      INTEGER, INTENT(IN) :: kgen_unit 
      CHARACTER(LEN=*), INTENT(IN) :: printname 
      LOGICAL, INTENT(IN), OPTIONAL :: printvar 
      LOGICAL :: kgen_istrue 
      REAL(KIND=8) :: kgen_array_sum 
        
      READ (UNIT = kgen_unit) var%dt 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%dt = ", var%dt 
      END IF   
        
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          CALL kr_ua_parametertype_real__reki_dim2(var%c, kgen_unit, printname // "%c", .TRUE.) 
      ELSE 
          CALL kr_ua_parametertype_real__reki_dim2(var%c, kgen_unit, printname // "%c", .FALSE.) 
      END IF   
        
      READ (UNIT = kgen_unit) var%d_34_to_ac 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%d_34_to_ac = ", var%d_34_to_ac 
      END IF   
        
      READ (UNIT = kgen_unit) var%numblades 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%numblades = ", var%numblades 
      END IF   
        
      READ (UNIT = kgen_unit) var%nnodesperblade 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%nnodesperblade = ", var%nnodesperblade 
      END IF   
        
      READ (UNIT = kgen_unit) var%uamod 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%uamod = ", var%uamod 
      END IF   
        
      READ (UNIT = kgen_unit) var%flookup 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%flookup = ", var%flookup 
      END IF   
        
      READ (UNIT = kgen_unit) var%a_s 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%a_s = ", var%a_s 
      END IF   
        
      READ (UNIT = kgen_unit) var%numouts 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%numouts = ", var%numouts 
      END IF   
        
      READ (UNIT = kgen_unit) var%outswtch 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%outswtch = ", var%outswtch 
      END IF   
        
      READ (UNIT = kgen_unit) var%outfmt 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%outfmt = ", var%outfmt 
      END IF   
        
      READ (UNIT = kgen_unit) var%outsfmt 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%outsfmt = ", var%outsfmt 
      END IF   
        
      READ (UNIT = kgen_unit) var%delim 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%delim = ", var%delim 
      END IF   
        
      READ (UNIT = kgen_unit) var%unoutfile 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%unoutfile = ", var%unoutfile 
      END IF   
        
      READ (UNIT = kgen_unit) var%shedeffect 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%shedeffect = ", var%shedeffect 
      END IF   
        
      READ (UNIT = kgen_unit) var%lin_nx 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%lin_nx = ", var%lin_nx 
      END IF   
        
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          CALL kr_ua_parametertype_logical___dim2(var%ua_off_forgood, kgen_unit, printname // "%ua_off_forgood", .TRUE.) 
      ELSE 
          CALL kr_ua_parametertype_logical___dim2(var%ua_off_forgood, kgen_unit, printname // "%ua_off_forgood", .FALSE.) 
      END IF   
        
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          CALL kr_ua_parametertype_integer__intki_dim2(var%lin_xindx, kgen_unit, printname // "%lin_xindx", .TRUE.) 
      ELSE 
          CALL kr_ua_parametertype_integer__intki_dim2(var%lin_xindx, kgen_unit, printname // "%lin_xindx", .FALSE.) 
      END IF   
        
      READ (UNIT = kgen_unit) kgen_istrue 
      IF (kgen_istrue) THEN 
          READ (UNIT = kgen_unit) kgen_array_sum 
          READ (UNIT = kgen_unit) var%dx 
          CALL kgen_array_sumcheck(printname // "%dx", kgen_array_sum, DBLE(SUM(var%dx, mask=(var%dx .eq. var%dx))), .TRUE.) 
          IF (PRESENT( printvar ) .AND. printvar) THEN 
              WRITE (*, *) "KGEN DEBUG: DBLE(SUM(" // printname // "%dx)) = ", DBLE(SUM(var%dx, mask=(var%dx .eq. var%dx))) 
          END IF   
      END IF   
        
      READ (UNIT = kgen_unit) var%ua_outs 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%ua_outs = ", var%ua_outs 
      END IF   
        
      READ (UNIT = kgen_unit) var%integrationmethod 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%integrationmethod = ", var%integrationmethod 
      END IF   
        
  END SUBROUTINE kr_unsteadyaero_types_ua_parametertype 
    
  !write state subroutine for kr_ua_parametertype_real__reki_dim2 
  SUBROUTINE kr_ua_parametertype_real__reki_dim2(var, kgen_unit, printname, printvar) 
      REAL(KIND=reki), INTENT(INOUT), ALLOCATABLE, DIMENSION(:,:) :: var 
      INTEGER, INTENT(IN) :: kgen_unit 
      CHARACTER(LEN=*), INTENT(IN) :: printname 
      LOGICAL, INTENT(IN), OPTIONAL :: printvar 
      LOGICAL :: kgen_istrue 
      REAL(KIND=8) :: kgen_array_sum 
      INTEGER :: idx1, idx2 
      INTEGER, DIMENSION(2,2) :: kgen_bound 
        
      READ (UNIT = kgen_unit) kgen_istrue 
      IF (kgen_istrue) THEN 
          IF (ALLOCATED( var )) THEN 
              DEALLOCATE (var) 
          END IF   
          READ (UNIT = kgen_unit) kgen_array_sum 
          READ (UNIT = kgen_unit) kgen_bound(1, 1) 
          READ (UNIT = kgen_unit) kgen_bound(2, 1) 
          READ (UNIT = kgen_unit) kgen_bound(1, 2) 
          READ (UNIT = kgen_unit) kgen_bound(2, 2) 
          ALLOCATE (var(kgen_bound(1,1):kgen_bound(2,1), kgen_bound(1,2):kgen_bound(2,2))) 
          READ (UNIT = kgen_unit) var 
          CALL kgen_array_sumcheck(printname, kgen_array_sum, DBLE(SUM(var, mask=(var .eq. var))), .TRUE.) 
          IF (PRESENT( printvar ) .AND. printvar) THEN 
              WRITE (*, *) "KGEN DEBUG: DBLE(SUM(" // printname // ")) = ", DBLE(SUM(var, mask=(var .eq. var))) 
          END IF   
      END IF   
        
  END SUBROUTINE kr_ua_parametertype_real__reki_dim2 
    
  !write state subroutine for kr_ua_parametertype_logical___dim2 
  SUBROUTINE kr_ua_parametertype_logical___dim2(var, kgen_unit, printname, printvar) 
      LOGICAL, INTENT(INOUT), ALLOCATABLE, DIMENSION(:,:) :: var 
      INTEGER, INTENT(IN) :: kgen_unit 
      CHARACTER(LEN=*), INTENT(IN) :: printname 
      LOGICAL, INTENT(IN), OPTIONAL :: printvar 
      LOGICAL :: kgen_istrue 
      REAL(KIND=8) :: kgen_array_sum 
      INTEGER :: idx1, idx2 
      INTEGER, DIMENSION(2,2) :: kgen_bound 
        
      READ (UNIT = kgen_unit) kgen_istrue 
      IF (kgen_istrue) THEN 
          IF (ALLOCATED( var )) THEN 
              DEALLOCATE (var) 
          END IF   
          READ (UNIT = kgen_unit) kgen_bound(1, 1) 
          READ (UNIT = kgen_unit) kgen_bound(2, 1) 
          READ (UNIT = kgen_unit) kgen_bound(1, 2) 
          READ (UNIT = kgen_unit) kgen_bound(2, 2) 
          ALLOCATE (var(kgen_bound(1,1):kgen_bound(2,1), kgen_bound(1,2):kgen_bound(2,2))) 
          READ (UNIT = kgen_unit) var 
          IF (PRESENT( printvar ) .AND. printvar) THEN 
              WRITE (*, *) "KGEN DEBUG: " // printname // " = ", var 
          END IF   
      END IF   
        
  END SUBROUTINE kr_ua_parametertype_logical___dim2 
    
  !write state subroutine for kr_ua_parametertype_integer__intki_dim2 
  SUBROUTINE kr_ua_parametertype_integer__intki_dim2(var, kgen_unit, printname, printvar) 
      INTEGER(KIND=intki), INTENT(INOUT), ALLOCATABLE, DIMENSION(:,:) :: var 
      INTEGER, INTENT(IN) :: kgen_unit 
      CHARACTER(LEN=*), INTENT(IN) :: printname 
      LOGICAL, INTENT(IN), OPTIONAL :: printvar 
      LOGICAL :: kgen_istrue 
      REAL(KIND=8) :: kgen_array_sum 
      INTEGER :: idx1, idx2 
      INTEGER, DIMENSION(2,2) :: kgen_bound 
        
      READ (UNIT = kgen_unit) kgen_istrue 
      IF (kgen_istrue) THEN 
          IF (ALLOCATED( var )) THEN 
              DEALLOCATE (var) 
          END IF   
          READ (UNIT = kgen_unit) kgen_array_sum 
          READ (UNIT = kgen_unit) kgen_bound(1, 1) 
          READ (UNIT = kgen_unit) kgen_bound(2, 1) 
          READ (UNIT = kgen_unit) kgen_bound(1, 2) 
          READ (UNIT = kgen_unit) kgen_bound(2, 2) 
          ALLOCATE (var(kgen_bound(1,1):kgen_bound(2,1), kgen_bound(1,2):kgen_bound(2,2))) 
          READ (UNIT = kgen_unit) var 
          CALL kgen_array_sumcheck(printname, kgen_array_sum, DBLE(SUM(var, mask=(var .eq. var))), .TRUE.) 
          IF (PRESENT( printvar ) .AND. printvar) THEN 
              WRITE (*, *) "KGEN DEBUG: DBLE(SUM(" // printname // ")) = ", DBLE(SUM(var, mask=(var .eq. var))) 
          END IF   
      END IF   
        
  END SUBROUTINE kr_ua_parametertype_integer__intki_dim2 
    
  !verify state subroutine for kv_unsteadyaero_types_ua_parametertype 
  RECURSIVE SUBROUTINE kv_unsteadyaero_types_ua_parametertype(varname, check_status, var, kgenref_var) 
      CHARACTER(LEN=*), INTENT(IN) :: varname 
      TYPE(check_t), INTENT(INOUT) :: check_status 
      TYPE(ua_parametertype), INTENT(IN) :: var, kgenref_var 
      TYPE(check_t) :: dtype_check_status, comp_check_status 
      INTEGER :: check_result 
      LOGICAL :: is_print = .FALSE. 
        
      real(KIND=dbki) :: diff_dt 
      INTEGER :: n_c 
      real(KIND=reki) :: nrmsdiff_c, rmsdiff_c 
      real(KIND=reki), ALLOCATABLE :: buf1_c(:,:), buf2_c(:,:) 
      real(KIND=reki) :: diff_d_34_to_ac 
      integer(KIND=intki) :: diff_numblades 
      integer(KIND=intki) :: diff_nnodesperblade 
      integer(KIND=intki) :: diff_uamod 
      real(KIND=reki) :: diff_a_s 
      integer(KIND=intki) :: diff_numouts 
      integer(KIND=intki) :: diff_outswtch 
      integer(KIND=intki) :: diff_unoutfile 
      integer(KIND=intki) :: diff_lin_nx 
      INTEGER :: n_ua_off_forgood 
      INTEGER :: n_lin_xindx 
      integer(KIND=intki) :: nrmsdiff_lin_xindx, rmsdiff_lin_xindx 
      integer(KIND=intki), ALLOCATABLE :: buf1_lin_xindx(:,:), buf2_lin_xindx(:,:) 
      INTEGER :: n_dx 
      real(KIND=r8ki) :: nrmsdiff_dx, rmsdiff_dx 
      real(KIND=r8ki), ALLOCATABLE :: buf1_dx(:), buf2_dx(:) 
      integer(KIND=intki) :: diff_ua_outs 
      integer(KIND=intki) :: diff_integrationmethod 
        
      check_status%numTotal = check_status%numTotal + 1 
        
      CALL kgen_init_check(dtype_check_status, rank=check_status%rank) 
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%dt == kgenref_var%dt) .OR. ((var%dt /= var%dt) .AND. (kgenref_var%dt /= kgenref_var%dt))) THEN
        IF (var%dt /= var%dt) WRITE(*, *) "localvar%dt is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%dt is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_dt = ABS(var%dt - kgenref_var%dt) 
          IF (diff_dt <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%dt is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%dt is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_dt 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_dt 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      IF (ALLOCATED(var%c)) THEN 
          dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
          IF (ALL(var%c == kgenref_var%c)) THEN 
              dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%c is IDENTICAL." 
                  END IF   
              END IF   
              check_result = CHECK_IDENTICAL 
          ELSE 
              ALLOCATE (buf1_c(SIZE(var%c,dim=1),SIZE(var%c,dim=2))) 
              ALLOCATE (buf2_c(SIZE(var%c,dim=1),SIZE(var%c,dim=2))) 
              n_c = COUNT(var%c /= kgenref_var%c) 
              WHERE ( ABS(kgenref_var%c) > kgen_minvalue ) 
                  buf1_c = ((var%c-kgenref_var%c)/kgenref_var%c)**2 
                  buf2_c = (var%c-kgenref_var%c)**2 
              ELSEWHERE 
                  buf1_c = (var%c-kgenref_var%c)**2 
                  buf2_c = buf1_c 
              END WHERE   
              nrmsdiff_c = SQRT(SUM(buf1_c)/REAL(n_c)) 
              rmsdiff_c = SQRT(SUM(buf2_c)/REAL(n_c)) 
              IF (rmsdiff_c > kgen_tolerance) THEN 
                  dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
                  IF (kgen_verboseLevel > 1) THEN 
                      IF (check_status%rank == 0) THEN 
                          WRITE (*, *) trim(adjustl(varname)), "%c is NOT IDENTICAL(out of tolerance)." 
                      END IF   
                  END IF   
                  check_result = CHECK_OUT_TOL 
              ELSE 
                  dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
                  IF (kgen_verboseLevel > 1) THEN 
                      IF (check_status%rank == 0) THEN 
                          WRITE (*, *) trim(adjustl(varname)), "%c is NOT IDENTICAL(within tolerance)." 
                      END IF   
                  END IF   
                  check_result = CHECK_IN_TOL 
              END IF   
          END IF   
          IF (check_result == CHECK_IDENTICAL) THEN 
              CONTINUE 
          ELSE IF (check_result == CHECK_OUT_TOL) THEN 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank ==0) THEN 
                      WRITE (*, *) count( var%c /= kgenref_var%c), " of ", size( var%c ), " elements are different." 
                      WRITE (*, *) "Average - kernel ", sum(var%c)/real(size(var%c)) 
                      WRITE (*, *) "Average - reference ", sum(kgenref_var%c)/real(size(kgenref_var%c)) 
                      WRITE (*, *) "RMS of difference is ", rmsdiff_c 
                      WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_c 
                      WRITE (*, *) "" 
                  END IF   
              END IF   
          ELSE IF (check_result == CHECK_IN_TOL) THEN 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank ==0) THEN 
                      WRITE (*, *) count( var%c /= kgenref_var%c), " of ", size( var%c ), " elements are different." 
                      WRITE (*, *) "Average - kernel ", sum(var%c)/real(size(var%c)) 
                      WRITE (*, *) "Average - reference ", sum(kgenref_var%c)/real(size(kgenref_var%c)) 
                      WRITE (*, *) "RMS of difference is ", rmsdiff_c 
                      WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_c 
                      WRITE (*, *) "" 
                  END IF   
              END IF   
          END IF   
            
      END IF   
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%d_34_to_ac == kgenref_var%d_34_to_ac) .OR. ((var%d_34_to_ac /= var%d_34_to_ac) .AND. (kgenref_var%d_34_to_ac /= kgenref_var%d_34_to_ac))) THEN
        IF (var%d_34_to_ac /= var%d_34_to_ac) WRITE(*, *) "localvar%d_34_to_ac is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%d_34_to_ac is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_d_34_to_ac = ABS(var%d_34_to_ac - kgenref_var%d_34_to_ac) 
          IF (diff_d_34_to_ac <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%d_34_to_ac is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%d_34_to_ac is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_d_34_to_ac 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_d_34_to_ac 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%numblades == kgenref_var%numblades) .OR. ((var%numblades /= var%numblades) .AND. (kgenref_var%numblades /= kgenref_var%numblades))) THEN
        IF (var%numblades /= var%numblades) WRITE(*, *) "localvar%numblades is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%numblades is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_numblades = ABS(var%numblades - kgenref_var%numblades) 
          IF (diff_numblades <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%numblades is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%numblades is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_numblades 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_numblades 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%nnodesperblade == kgenref_var%nnodesperblade) .OR. ((var%nnodesperblade /= var%nnodesperblade) .AND. (kgenref_var%nnodesperblade /= kgenref_var%nnodesperblade))) THEN
        IF (var%nnodesperblade /= var%nnodesperblade) WRITE(*, *) "localvar%nnodesperblade is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%nnodesperblade is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_nnodesperblade = ABS(var%nnodesperblade - kgenref_var%nnodesperblade) 
          IF (diff_nnodesperblade <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%nnodesperblade is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%nnodesperblade is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_nnodesperblade 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_nnodesperblade 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%uamod == kgenref_var%uamod) .OR. ((var%uamod /= var%uamod) .AND. (kgenref_var%uamod /= kgenref_var%uamod))) THEN
        IF (var%uamod /= var%uamod) WRITE(*, *) "localvar%uamod is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%uamod is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_uamod = ABS(var%uamod - kgenref_var%uamod) 
          IF (diff_uamod <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%uamod is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%uamod is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_uamod 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_uamod 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF (var%flookup .EQV. kgenref_var%flookup) THEN 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%flookup is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
          IF (kgen_verboseLevel > 1) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%flookup is NOT IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_OUT_TOL 
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%a_s == kgenref_var%a_s) .OR. ((var%a_s /= var%a_s) .AND. (kgenref_var%a_s /= kgenref_var%a_s))) THEN
        IF (var%a_s /= var%a_s) WRITE(*, *) "localvar%a_s is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%a_s is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_a_s = ABS(var%a_s - kgenref_var%a_s) 
          IF (diff_a_s <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%a_s is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%a_s is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_a_s 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_a_s 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%numouts == kgenref_var%numouts) .OR. ((var%numouts /= var%numouts) .AND. (kgenref_var%numouts /= kgenref_var%numouts))) THEN
        IF (var%numouts /= var%numouts) WRITE(*, *) "localvar%numouts is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%numouts is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_numouts = ABS(var%numouts - kgenref_var%numouts) 
          IF (diff_numouts <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%numouts is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%numouts is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_numouts 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_numouts 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%outswtch == kgenref_var%outswtch) .OR. ((var%outswtch /= var%outswtch) .AND. (kgenref_var%outswtch /= kgenref_var%outswtch))) THEN
        IF (var%outswtch /= var%outswtch) WRITE(*, *) "localvar%outswtch is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%outswtch is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_outswtch = ABS(var%outswtch - kgenref_var%outswtch) 
          IF (diff_outswtch <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%outswtch is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%outswtch is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_outswtch 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_outswtch 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%outfmt == kgenref_var%outfmt) .OR. ((var%outfmt /= var%outfmt) .AND. (kgenref_var%outfmt /= kgenref_var%outfmt))) THEN
        IF (var%outfmt /= var%outfmt) WRITE(*, *) "localvar%outfmt is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%outfmt is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
          IF (kgen_verboseLevel > 1) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%outfmt is NOT IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_OUT_TOL 
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%outsfmt == kgenref_var%outsfmt) .OR. ((var%outsfmt /= var%outsfmt) .AND. (kgenref_var%outsfmt /= kgenref_var%outsfmt))) THEN
        IF (var%outsfmt /= var%outsfmt) WRITE(*, *) "localvar%outsfmt is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%outsfmt is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
          IF (kgen_verboseLevel > 1) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%outsfmt is NOT IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_OUT_TOL 
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%delim == kgenref_var%delim) .OR. ((var%delim /= var%delim) .AND. (kgenref_var%delim /= kgenref_var%delim))) THEN
        IF (var%delim /= var%delim) WRITE(*, *) "localvar%delim is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%delim is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
          IF (kgen_verboseLevel > 1) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%delim is NOT IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_OUT_TOL 
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%unoutfile == kgenref_var%unoutfile) .OR. ((var%unoutfile /= var%unoutfile) .AND. (kgenref_var%unoutfile /= kgenref_var%unoutfile))) THEN
        IF (var%unoutfile /= var%unoutfile) WRITE(*, *) "localvar%unoutfile is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%unoutfile is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_unoutfile = ABS(var%unoutfile - kgenref_var%unoutfile) 
          IF (diff_unoutfile <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%unoutfile is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%unoutfile is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_unoutfile 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_unoutfile 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF (var%shedeffect .EQV. kgenref_var%shedeffect) THEN 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%shedeffect is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
          IF (kgen_verboseLevel > 1) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%shedeffect is NOT IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_OUT_TOL 
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "NOT IMPLEMENTED YET" 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%lin_nx == kgenref_var%lin_nx) .OR. ((var%lin_nx /= var%lin_nx) .AND. (kgenref_var%lin_nx /= kgenref_var%lin_nx))) THEN
        IF (var%lin_nx /= var%lin_nx) WRITE(*, *) "localvar%lin_nx is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%lin_nx is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_lin_nx = ABS(var%lin_nx - kgenref_var%lin_nx) 
          IF (diff_lin_nx <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%lin_nx is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%lin_nx is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_lin_nx 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_lin_nx 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      IF (ALLOCATED(var%ua_off_forgood)) THEN 
          dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
          IF (ALL(var%ua_off_forgood .EQV. kgenref_var%ua_off_forgood)) THEN 
              dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%ua_off_forgood is IDENTICAL." 
                  END IF   
              END IF   
              check_result = CHECK_IDENTICAL 
          ELSE 
              n_ua_off_forgood = COUNT(var%ua_off_forgood .NEQV. kgenref_var%ua_off_forgood) 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%ua_off_forgood is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
          IF (check_result == CHECK_IDENTICAL) THEN 
              CONTINUE 
          ELSE IF (check_result == CHECK_OUT_TOL) THEN 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank ==0) THEN 
                      WRITE (*, *) "NOT IMPLEMENTED YET" 
                      WRITE (*, *) "" 
                  END IF   
              END IF   
          ELSE IF (check_result == CHECK_IN_TOL) THEN 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank ==0) THEN 
                      WRITE (*, *) "NOT IMPLEMENTED YET" 
                      WRITE (*, *) "" 
                  END IF   
              END IF   
          END IF   
            
      END IF   
      IF (ALLOCATED(var%lin_xindx)) THEN 
          dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
          IF (ALL(var%lin_xindx == kgenref_var%lin_xindx)) THEN 
              dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%lin_xindx is IDENTICAL." 
                  END IF   
              END IF   
              check_result = CHECK_IDENTICAL 
          ELSE 
              ALLOCATE (buf1_lin_xindx(SIZE(var%lin_xindx,dim=1),SIZE(var%lin_xindx,dim=2))) 
              ALLOCATE (buf2_lin_xindx(SIZE(var%lin_xindx,dim=1),SIZE(var%lin_xindx,dim=2))) 
              n_lin_xindx = COUNT(var%lin_xindx /= kgenref_var%lin_xindx) 
              WHERE ( ABS(kgenref_var%lin_xindx) > kgen_minvalue ) 
                  buf1_lin_xindx = ((var%lin_xindx-kgenref_var%lin_xindx)/kgenref_var%lin_xindx)**2 
                  buf2_lin_xindx = (var%lin_xindx-kgenref_var%lin_xindx)**2 
              ELSEWHERE 
                  buf1_lin_xindx = (var%lin_xindx-kgenref_var%lin_xindx)**2 
                  buf2_lin_xindx = buf1_lin_xindx 
              END WHERE   
              nrmsdiff_lin_xindx = SQRT(SUM(buf1_lin_xindx)/REAL(n_lin_xindx)) 
              rmsdiff_lin_xindx = SQRT(SUM(buf2_lin_xindx)/REAL(n_lin_xindx)) 
              IF (rmsdiff_lin_xindx > kgen_tolerance) THEN 
                  dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
                  IF (kgen_verboseLevel > 1) THEN 
                      IF (check_status%rank == 0) THEN 
                          WRITE (*, *) trim(adjustl(varname)), "%lin_xindx is NOT IDENTICAL(out of tolerance)." 
                      END IF   
                  END IF   
                  check_result = CHECK_OUT_TOL 
              ELSE 
                  dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
                  IF (kgen_verboseLevel > 1) THEN 
                      IF (check_status%rank == 0) THEN 
                          WRITE (*, *) trim(adjustl(varname)), "%lin_xindx is NOT IDENTICAL(within tolerance)." 
                      END IF   
                  END IF   
                  check_result = CHECK_IN_TOL 
              END IF   
          END IF   
          IF (check_result == CHECK_IDENTICAL) THEN 
              CONTINUE 
          ELSE IF (check_result == CHECK_OUT_TOL) THEN 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank ==0) THEN 
                      WRITE (*, *) count( var%lin_xindx /= kgenref_var%lin_xindx), " of ", size( var%lin_xindx ), " elements are &
                      &different." 
                      WRITE (*, *) "Average - kernel ", sum(var%lin_xindx)/real(size(var%lin_xindx)) 
                      WRITE (*, *) "Average - reference ", sum(kgenref_var%lin_xindx)/real(size(kgenref_var%lin_xindx)) 
                      WRITE (*, *) "RMS of difference is ", rmsdiff_lin_xindx 
                      WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_lin_xindx 
                      WRITE (*, *) "" 
                  END IF   
              END IF   
          ELSE IF (check_result == CHECK_IN_TOL) THEN 
              IF (kgen_verboseLevel > 2) THEN 
                  IF (check_status%rank ==0) THEN 
                      WRITE (*, *) count( var%lin_xindx /= kgenref_var%lin_xindx), " of ", size( var%lin_xindx ), " elements are &
                      &different." 
                      WRITE (*, *) "Average - kernel ", sum(var%lin_xindx)/real(size(var%lin_xindx)) 
                      WRITE (*, *) "Average - reference ", sum(kgenref_var%lin_xindx)/real(size(kgenref_var%lin_xindx)) 
                      WRITE (*, *) "RMS of difference is ", rmsdiff_lin_xindx 
                      WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_lin_xindx 
                      WRITE (*, *) "" 
                  END IF   
              END IF   
          END IF   
            
      END IF   
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF (ALL(var%dx == kgenref_var%dx)) THEN 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%dx is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          ALLOCATE (buf1_dx(SIZE(var%dx,dim=1))) 
          ALLOCATE (buf2_dx(SIZE(var%dx,dim=1))) 
          n_dx = COUNT(var%dx /= kgenref_var%dx) 
          WHERE ( ABS(kgenref_var%dx) > kgen_minvalue ) 
              buf1_dx = ((var%dx-kgenref_var%dx)/kgenref_var%dx)**2 
              buf2_dx = (var%dx-kgenref_var%dx)**2 
          ELSEWHERE 
              buf1_dx = (var%dx-kgenref_var%dx)**2 
              buf2_dx = buf1_dx 
          END WHERE   
          nrmsdiff_dx = SQRT(SUM(buf1_dx)/REAL(n_dx)) 
          rmsdiff_dx = SQRT(SUM(buf2_dx)/REAL(n_dx)) 
          IF (rmsdiff_dx > kgen_tolerance) THEN 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%dx is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          ELSE 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%dx is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) count( var%dx /= kgenref_var%dx), " of ", size( var%dx ), " elements are different." 
                  WRITE (*, *) "Average - kernel ", sum(var%dx)/real(size(var%dx)) 
                  WRITE (*, *) "Average - reference ", sum(kgenref_var%dx)/real(size(kgenref_var%dx)) 
                  WRITE (*, *) "RMS of difference is ", rmsdiff_dx 
                  WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_dx 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) count( var%dx /= kgenref_var%dx), " of ", size( var%dx ), " elements are different." 
                  WRITE (*, *) "Average - kernel ", sum(var%dx)/real(size(var%dx)) 
                  WRITE (*, *) "Average - reference ", sum(kgenref_var%dx)/real(size(kgenref_var%dx)) 
                  WRITE (*, *) "RMS of difference is ", rmsdiff_dx 
                  WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_dx 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%ua_outs == kgenref_var%ua_outs) .OR. ((var%ua_outs /= var%ua_outs) .AND. (kgenref_var%ua_outs /= kgenref_var%ua_outs))) THEN
        IF (var%ua_outs /= var%ua_outs) WRITE(*, *) "localvar%ua_outs is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%ua_outs is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_ua_outs = ABS(var%ua_outs - kgenref_var%ua_outs) 
          IF (diff_ua_outs <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%ua_outs is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%ua_outs is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_ua_outs 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_ua_outs 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%integrationmethod == kgenref_var%integrationmethod) .OR. ((var%integrationmethod /= var%integrationmethod) .AND. (kgenref_var%integrationmethod /= kgenref_var%integrationmethod))) THEN
        IF (var%integrationmethod /= var%integrationmethod) WRITE(*, *) "localvar%integrationmethod is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%integrationmethod is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
      ELSE 
          diff_integrationmethod = ABS(var%integrationmethod - kgenref_var%integrationmethod) 
          IF (diff_integrationmethod <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%integrationmethod is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%integrationmethod is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_integrationmethod 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_integrationmethod 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      IF (dtype_check_status%numTotal == dtype_check_status%numIdentical) THEN 
          check_status%numIdentical = check_status%numIdentical + 1 
      ELSE IF (dtype_check_status%numOutTol > 0) THEN 
          check_status%numOutTol = check_status%numOutTol + 1 
      ELSE IF (dtype_check_status%numInTol > 0) THEN 
          check_status%numInTol = check_status%numInTol + 1 
      END IF   
  END SUBROUTINE kv_unsteadyaero_types_ua_parametertype 
    
END MODULE UnsteadyAero_Types
!ENDOFREGISTRYGENERATEDFILE
