// C struct definitions for Fortran derived types.
// Auto-generated by VIT. Do not edit manually.

#ifndef VIT_TYPES_H
#define VIT_TYPES_H

#include <stdint.h>

// Auto-generated C struct for Fortran TYPE(AFI_OutputType)
// Generated by VIT (Verified Incremental Translator)

#ifndef AFI_OUTPUTTYPE_T_H
#define AFI_OUTPUTTYPE_T_H

typedef struct {
    double Cl;
    double Cd;
    double Cm;
    double Cpmin;
    double Cd0;
    double Cm0;
    double f_st;
    double FullySeparate;
    double FullyAttached;
} afi_outputtype_t;

#endif // AFI_OUTPUTTYPE_T_H

// Auto-generated C struct for Fortran TYPE(AFI_UA_BL_Type)
// Generated by VIT (Verified Incremental Translator)

#ifndef AFI_UA_BL_TYPE_T_H
#define AFI_UA_BL_TYPE_T_H

typedef struct {
    double alpha0;
    double alpha1;
    double alpha2;
    double eta_e;
    double C_nalpha;
    double C_lalpha;
    double T_f0;
    double T_V0;
    double T_p;
    double T_VL;
    double b1;
    double b2;
    double b5;
    double A1;
    double A2;
    double A5;
    double S1;
    double S2;
    double S3;
    double S4;
    double Cn1;
    double Cn2;
    double St_sh;
    double Cd0;
    double Cm0;
    double k0;
    double k1;
    double k2;
    double k3;
    double k1_hat;
    double x_cp_bar;
    double UACutout;
    double UACutout_delta;
    double UACutout_blend;
    double filtCutOff;
    double alphaUpper;
    double alphaLower;
    double c_alphaLower;
    double c_alphaUpper;
    double alpha0ReverseFlow;
    double alphaBreakUpper;
    double CnBreakUpper;
    double alphaBreakLower;
    double CnBreakLower;
} afi_ua_bl_type_t;

#endif // AFI_UA_BL_TYPE_T_H

// Auto-generated view struct for Fortran TYPE(AFI_Table_Type)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef AFI_TABLE_TYPE_VIEW_T_H
#define AFI_TABLE_TYPE_VIEW_T_H

#include <stdint.h>

#ifndef AFI_UA_BL_TYPE_T_H
#define AFI_UA_BL_TYPE_T_H
typedef struct {
    double alpha0;
    double alpha1;
    double alpha2;
    double eta_e;
    double C_nalpha;
    double C_lalpha;
    double T_f0;
    double T_V0;
    double T_p;
    double T_VL;
    double b1;
    double b2;
    double b5;
    double A1;
    double A2;
    double A5;
    double S1;
    double S2;
    double S3;
    double S4;
    double Cn1;
    double Cn2;
    double St_sh;
    double Cd0;
    double Cm0;
    double k0;
    double k1;
    double k2;
    double k3;
    double k1_hat;
    double x_cp_bar;
    double UACutout;
    double UACutout_delta;
    double UACutout_blend;
    double filtCutOff;
    double alphaUpper;
    double alphaLower;
    double c_alphaLower;
    double c_alphaUpper;
    double alpha0ReverseFlow;
    double alphaBreakUpper;
    double CnBreakUpper;
    double alphaBreakLower;
    double CnBreakLower;
} afi_ua_bl_type_t;
#endif // AFI_UA_BL_TYPE_T_H

typedef struct {
    // --- Scalar and fixed-size fields ---
    double UserProp;
    double Re;
    int NumAlf;
    int8_t ConstData;
    int8_t InclUAdata;
    afi_ua_bl_type_t UA_BL;

    // --- ALLOCATABLE fields (pointer + size) ---
    double* Alpha;
    int32_t n_Alpha;
    double* Coefs;  // column-major
    int32_t n_Coefs_rows;
    int32_t n_Coefs_cols;
    double* SplineCoefs;  // column-major
    int32_t n_SplineCoefs_dim1;
    int32_t n_SplineCoefs_dim2;
    int32_t n_SplineCoefs_dim3;
} afi_table_type_view_t;

#endif // AFI_TABLE_TYPE_VIEW_T_H

// Auto-generated view struct for Fortran TYPE(AFI_ParameterType)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef AFI_PARAMETERTYPE_VIEW_T_H
#define AFI_PARAMETERTYPE_VIEW_T_H

#include <stdint.h>

typedef struct {
    // --- Scalar and fixed-size fields ---
    int ColCd;
    int ColCl;
    int ColCm;
    int ColCpmin;
    int ColUAf;
    int AFTabMod;
    int InterpOrd;
    double RelThickness;
    double NonDimArea;
    int NumCoords;
    int NumTabs;
    char BL_file[1024];
    char FileName[1024];

    // --- ALLOCATABLE fields (pointer + size) ---
    double* secondVals;
    int32_t n_secondVals;
    double* X_Coord;
    int32_t n_X_Coord;
    double* Y_Coord;
    int32_t n_Y_Coord;
    afi_table_type_view_t* Table;  // Array of view structs, populated by Fortran
    int32_t n_Table;
} afi_parametertype_view_t;

#endif // AFI_PARAMETERTYPE_VIEW_T_H

#endif // VIT_TYPES_H
