// VIT Translation
// Function: AFI_WrTables
// Source: AirfoilInfo.f90
// Module: AirfoilInfo
// Fortran: SUBROUTINE AFI_WrTables(AFI_Params, UAMod, OutRootName)
// Verification: file-output

#include "vit_types.h"
#include "vit_nwtc.h"
#include "vit_aerodyn_constants.h"

#include <cmath>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <string>
#include <vector>

extern "C" {

void afi_wrtables_c(afi_parametertype_view_t* p, int UAMod, const char* OutRootName) {
    std::string rootName(OutRootName);
    // Trim trailing spaces
    while (!rootName.empty() && rootName.back() == ' ') rootName.pop_back();

    const char* Prefix;
    const char* sFullyAtt;
    const char* sCm;

    if (UAMod != UA_HGM && UAMod != UA_Oye) {
        Prefix = "Cn_";
        sFullyAtt = "Cn_FullyAtt";
    } else {
        Prefix = "Cl_";
        sFullyAtt = "Dummy";
    }
    sCm = (p->ColCm > 0) ? "Cm" : "Cm_Dummy";

    for (int iTab = 0; iTab < p->n_Table; iTab++) {
        afi_table_type_view_t* tab = &p->Table[iTab];
        int N = tab->NumAlf;

        std::vector<double> cn(N), cc(N), cl_lin(N), cn_lin(N);
        std::vector<double> cl_smooth(N), cn_smooth(N);

        // Column-major Coefs access: Coefs(row, col) = Coefs[(col-1)*nRows + row]
        int nRows = tab->n_Coefs_rows;
        int ColCl = p->ColCl - 1;  // 0-based column index
        int ColCd = p->ColCd - 1;

        for (int i = 0; i < N; i++) {
            double Cl = tab->Coefs[ColCl * nRows + i];
            double Cd = tab->Coefs[ColCd * nRows + i];
            double alpha = tab->Alpha[i];
            double Cd0 = tab->UA_BL.Cd0;

            cn[i] = Cl * std::cos(alpha) + (Cd - Cd0) * std::sin(alpha);
            cc[i] = Cl * std::sin(alpha) - (Cd - Cd0) * std::cos(alpha);
            cn_lin[i] = tab->UA_BL.C_nalpha * (alpha - tab->UA_BL.alpha0);
            cl_lin[i] = tab->UA_BL.C_lalpha * (alpha - tab->UA_BL.alpha0);
        }

        // Zero cn_lin/cl_lin outside break range
        for (int i = 0; i < N; i++) {
            if (tab->Alpha[i] < tab->UA_BL.alphaBreakLower ||
                tab->Alpha[i] > tab->UA_BL.alphaBreakUpper) {
                cl_lin[i] = 0.0;
                cn_lin[i] = 0.0;
            }
        }

        // Kernel smoothing
        kernelSmoothing(tab->Alpha, cn.data(), N, kernelType_TRIWEIGHT, 2.0 * D2R, cn_smooth.data());

        // cl_smooth: smooth the Cl column
        std::vector<double> cl_col(N);
        for (int i = 0; i < N; i++) cl_col[i] = tab->Coefs[ColCl * nRows + i];
        kernelSmoothing(tab->Alpha, cl_col.data(), N, kernelType_TRIWEIGHT, 2.0 * D2R, cl_smooth.data());

        // Open file: {OutRootName}.Coefs.{iTab+1}.out
        std::string fname = rootName + ".Coefs." + std::to_string(iTab + 1) + ".out";
        FILE* f = fopen(fname.c_str(), "w");
        if (!f) continue;

        // Header
        time_t now = time(nullptr);
        struct tm* t = localtime(&now);
        static const char* months[] = {"Jan","Feb","Mar","Apr","May","Jun",
                                        "Jul","Aug","Sep","Oct","Nov","Dec"};
        char datebuf[32], timebuf[16];
        snprintf(datebuf, sizeof(datebuf), "%02d-%s-%04d", t->tm_mday, months[t->tm_mon], t->tm_year + 1900);
        snprintf(timebuf, sizeof(timebuf), "%02d:%02d:%02d", t->tm_hour, t->tm_min, t->tm_sec);

        fprintf(f, "\nThese predictions were generated by AirfoilInfo on %s at %s.\n", datebuf, timebuf);
        fprintf(f, "\n \n");

        // Column names and units
        int ColUAf0 = p->ColUAf - 1;  // 0-based
        int ColCm0 = p->ColCm - 1;

        if (p->ColUAf > 0) {
            std::string pfxFullySep = std::string(Prefix) + "FullySep";
            fprintf(f, "%20s %20s %20s %20s %20s %20s %20s %20s %20s %20s %20s %20s %20s\n",
                    "Alpha", "Cl", "Cd", sCm, "Cn", "Cc", "f_st",
                    pfxFullySep.c_str(), sFullyAtt, "Cl_lin", "Cn_lin", "Cl_smooth", "Cn_smooth");
            fprintf(f, "%20s %20s %20s %20s %20s %20s %20s %20s %20s %20s %20s %20s %20s\n",
                    "(deg)", "(-)", "(-)", "(-)", "(-)", "(-)", "(-)",
                    "(-)", "(-)", "(-)", "(-)", "(-)", "(-)");

            for (int i = 0; i < N; i++) {
                double Cl = tab->Coefs[ColCl * nRows + i];
                double Cd = tab->Coefs[ColCd * nRows + i];
                double Cm_val = (p->ColCm > 0) ? tab->Coefs[ColCm0 * nRows + i] : 0.0;

                fprintf(f, "%20.6f %20.6f %20.6f %20.6f %20.6f %20.6f",
                        tab->Alpha[i] * R2D, Cl, Cd, Cm_val, cn[i], cc[i]);

                // f_st + FullySep + FullyAtt columns (ColUAf onwards)
                for (int c = ColUAf0; c < tab->n_Coefs_cols; c++) {
                    fprintf(f, " %20.6f", tab->Coefs[c * nRows + i]);
                }

                fprintf(f, " %20.6f %20.6f %20.6f %20.6f\n",
                        cl_lin[i], cn_lin[i], cl_smooth[i], cn_smooth[i]);
            }
        } else {
            fprintf(f, "%20s %20s %20s %20s %20s %20s %20s %20s %20s %20s\n",
                    "Alpha", "Cl", "Cd", sCm, "Cn", "Cc",
                    "Cl_lin", "Cn_lin", "Cl_smooth", "Cn_smooth");
            fprintf(f, "%20s %20s %20s %20s %20s %20s %20s %20s %20s %20s\n",
                    "(deg)", "(-)", "(-)", "(-)", "(-)", "(-)",
                    "(-)", "(-)", "(-)", "(-)");

            for (int i = 0; i < N; i++) {
                double Cl = tab->Coefs[ColCl * nRows + i];
                double Cd = tab->Coefs[ColCd * nRows + i];
                double Cm_val = (p->ColCm > 0) ? tab->Coefs[ColCm0 * nRows + i] : 0.0;

                fprintf(f, "%20.6f %20.6f %20.6f %20.6f %20.6f %20.6f %20.6f %20.6f %20.6f %20.6f\n",
                        tab->Alpha[i] * R2D, Cl, Cd, Cm_val,
                        cn[i], cn[i], cl_lin[i], cn_lin[i], cl_smooth[i], cn_smooth[i]);
            }
        }

        fclose(f);
    }
}

} // extern "C"
