// C++ implementation of Fortran function: AFI_ComputeUACoefs
// Generated by VIT (Verified Incremental Translator)
// After verification: AFI_ComputeUACoefs kernel PASSED

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: AFI_ComputeUACoefs (+ AFI_ComputeUACoefs2D, AFI_UA_BL_Type_ExtrapInterp1)
// Source: AirfoilInfo.f90
// Module: AirfoilInfo
// Fortran: SUBROUTINE AFI_ComputeUACoefs(p, Re, UserProp, UA_BL, errMsg, errStat)
// Source MD5: (auto)
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-26

#include <cmath>
#include <cstring>
#include "vit_types.h"
#include "vit_nwtc.h"
#include "vit_aerodyn_constants.h"

// Error constants (from NWTC_Base.f90)
static constexpr int ErrID_None  = 0;
static constexpr int ErrID_Fatal = 4;

// AFI_CopyUA_BL_Type (AirfoilInfo_Types.f90:222-275)
// Registry-generated struct copy. In C++, this is a trivial struct assignment.
// Defined here so VIT's C++ callee auto-detection skips Fortran bridge generation.
static void AFI_CopyUA_BL_Type(const afi_ua_bl_type_t& src, afi_ua_bl_type_t* dst) {
    *dst = src;
}

// Forward declarations
static void AFI_UA_BL_Type_ExtrapInterp1(const afi_ua_bl_type_t& u1,
                                          const afi_ua_bl_type_t& u2,
                                          const double tin[2],
                                          afi_ua_bl_type_t* u_out,
                                          double tin_out,
                                          int* ErrStat, char* ErrMsg);
static void AFI_ComputeUACoefs2D(double secondaryDepVal,
                                  afi_parametertype_view_t* p,
                                  afi_ua_bl_type_t* UA_BL,
                                  int* errStat, char* errMsg);

// FindBoundingTables is already translated — declare the _c entry point
extern "C" {
    void findboundingtables_c(afi_parametertype_view_t* p, double secondaryDepVal,
                              int* lowerTable, int* upperTable, double* xVals);
}

// --- AFI_UA_BL_Type_ExtrapInterp1 (AirfoilInfo_Types.f90:1267-1354) ---
// Linear interpolation of all 44 UA_BL fields between two tables.
// 8 angle fields use Angles_ExtrapInterp1 for ±2Pi wrapping.
// 36 numeric fields use Lagrange polynomial weights.

static void AFI_UA_BL_Type_ExtrapInterp1(const afi_ua_bl_type_t& u1,
                                          const afi_ua_bl_type_t& u2,
                                          const double tin[2],
                                          afi_ua_bl_type_t* u_out,
                                          double tin_out,
                                          int* ErrStat, char* ErrMsg) {
    *ErrStat = ErrID_None;
    std::memset(ErrMsg, ' ', ErrMsgLen);

    // Normalize time: subtract tin[0] to simplify equations
    double t1 = tin[1] - tin[0];
    double t_out = tin_out - tin[0];

    if (EqualRealNos(0.0, t1)) {
        *ErrStat = ErrID_Fatal;
        // "t(1) must not equal t(2) to avoid a division-by-zero error."
        return;
    }

    // Lagrange polynomial weights (order 1)
    double a1 = -(t_out - t1) / t1;
    double a2 = t_out / t1;

    // 8 angle fields via Angles_ExtrapInterp1 (handles ±2Pi wrapping)
    Angles_ExtrapInterp1(u1.alpha0, u2.alpha0, tin, &u_out->alpha0, tin_out);
    Angles_ExtrapInterp1(u1.alpha1, u2.alpha1, tin, &u_out->alpha1, tin_out);
    Angles_ExtrapInterp1(u1.alpha2, u2.alpha2, tin, &u_out->alpha2, tin_out);

    // 36 linear fields via weighted average
    u_out->eta_e     = a1 * u1.eta_e     + a2 * u2.eta_e;
    u_out->C_nalpha  = a1 * u1.C_nalpha  + a2 * u2.C_nalpha;
    u_out->C_lalpha  = a1 * u1.C_lalpha  + a2 * u2.C_lalpha;
    u_out->T_f0      = a1 * u1.T_f0      + a2 * u2.T_f0;
    u_out->T_V0      = a1 * u1.T_V0      + a2 * u2.T_V0;
    u_out->T_p       = a1 * u1.T_p       + a2 * u2.T_p;
    u_out->T_VL      = a1 * u1.T_VL      + a2 * u2.T_VL;
    u_out->b1        = a1 * u1.b1        + a2 * u2.b1;
    u_out->b2        = a1 * u1.b2        + a2 * u2.b2;
    u_out->b5        = a1 * u1.b5        + a2 * u2.b5;
    u_out->A1        = a1 * u1.A1        + a2 * u2.A1;
    u_out->A2        = a1 * u1.A2        + a2 * u2.A2;
    u_out->A5        = a1 * u1.A5        + a2 * u2.A5;
    u_out->S1        = a1 * u1.S1        + a2 * u2.S1;
    u_out->S2        = a1 * u1.S2        + a2 * u2.S2;
    u_out->S3        = a1 * u1.S3        + a2 * u2.S3;
    u_out->S4        = a1 * u1.S4        + a2 * u2.S4;
    u_out->Cn1       = a1 * u1.Cn1       + a2 * u2.Cn1;
    u_out->Cn2       = a1 * u1.Cn2       + a2 * u2.Cn2;
    u_out->St_sh     = a1 * u1.St_sh     + a2 * u2.St_sh;
    u_out->Cd0       = a1 * u1.Cd0       + a2 * u2.Cd0;
    u_out->Cm0       = a1 * u1.Cm0       + a2 * u2.Cm0;
    u_out->k0        = a1 * u1.k0        + a2 * u2.k0;
    u_out->k1        = a1 * u1.k1        + a2 * u2.k1;
    u_out->k2        = a1 * u1.k2        + a2 * u2.k2;
    u_out->k3        = a1 * u1.k3        + a2 * u2.k3;
    u_out->k1_hat    = a1 * u1.k1_hat    + a2 * u2.k1_hat;
    u_out->x_cp_bar  = a1 * u1.x_cp_bar  + a2 * u2.x_cp_bar;
    u_out->UACutout       = a1 * u1.UACutout       + a2 * u2.UACutout;
    u_out->UACutout_delta = a1 * u1.UACutout_delta + a2 * u2.UACutout_delta;
    u_out->UACutout_blend = a1 * u1.UACutout_blend + a2 * u2.UACutout_blend;
    u_out->filtCutOff     = a1 * u1.filtCutOff     + a2 * u2.filtCutOff;

    // 5 more angle fields via Angles_ExtrapInterp1
    Angles_ExtrapInterp1(u1.alphaUpper, u2.alphaUpper, tin, &u_out->alphaUpper, tin_out);
    Angles_ExtrapInterp1(u1.alphaLower, u2.alphaLower, tin, &u_out->alphaLower, tin_out);

    // 2 linear fields between the angle blocks
    u_out->c_alphaLower = a1 * u1.c_alphaLower + a2 * u2.c_alphaLower;
    u_out->c_alphaUpper = a1 * u1.c_alphaUpper + a2 * u2.c_alphaUpper;

    Angles_ExtrapInterp1(u1.alpha0ReverseFlow, u2.alpha0ReverseFlow, tin, &u_out->alpha0ReverseFlow, tin_out);
    Angles_ExtrapInterp1(u1.alphaBreakUpper, u2.alphaBreakUpper, tin, &u_out->alphaBreakUpper, tin_out);

    u_out->CnBreakUpper = a1 * u1.CnBreakUpper + a2 * u2.CnBreakUpper;

    Angles_ExtrapInterp1(u1.alphaBreakLower, u2.alphaBreakLower, tin, &u_out->alphaBreakLower, tin_out);

    u_out->CnBreakLower = a1 * u1.CnBreakLower + a2 * u2.CnBreakLower;
}

// --- AFI_ComputeUACoefs2D (AirfoilInfo.f90:1614-1657) ---
// Two-table interpolation on a secondary variable (Re or UserProp).

static void AFI_ComputeUACoefs2D(double secondaryDepVal,
                                  afi_parametertype_view_t* p,
                                  afi_ua_bl_type_t* UA_BL,
                                  int* errStat, char* errMsg) {
    *errStat = ErrID_None;
    std::memset(errMsg, ' ', ErrMsgLen);

    // Boundary clamp: below first table, use first table only
    if (secondaryDepVal <= p->secondVals[0]) {
        *UA_BL = p->Table[0].UA_BL;
        return;
    }
    // Above last table, use last table only
    if (secondaryDepVal >= p->secondVals[p->NumTabs - 1]) {
        *UA_BL = p->Table[p->NumTabs - 1].UA_BL;
        return;
    }

    // Find bounding tables for interpolation
    int lowerTable, upperTable;
    double xVals[2];
    findboundingtables_c(p, secondaryDepVal, &lowerTable, &upperTable, xVals);

    // Linear interpolation between lower and upper tables' UA_BL
    AFI_UA_BL_Type_ExtrapInterp1(
        p->Table[lowerTable - 1].UA_BL,  // 1-based → 0-based
        p->Table[upperTable - 1].UA_BL,
        xVals, UA_BL, secondaryDepVal,
        errStat, errMsg);
}

// --- AFI_ComputeUACoefs (AirfoilInfo.f90:1825-1860) ---
// Public dispatcher: routes to struct copy (1D) or table interpolation (2D)
// based on AFTabMod.

void AFI_ComputeUACoefs(afi_parametertype_view_t* p, double Re, double UserProp,
                         afi_ua_bl_type_t* UA_BL, char* errMsg, int* errStat) {

    if (p->AFTabMod == AFITable_1) {
        // Single table: copy Table(1)%UA_BL directly
        *UA_BL = p->Table[0].UA_BL;
        *errStat = ErrID_None;
        std::memset(errMsg, ' ', ErrMsgLen);
        return;  // Return before MPi2Pi — matches Fortran early return
    } else if (p->AFTabMod == AFITable_2Re) {
        // AFI_USE_LINEAR_RE is not defined (default: use log)
        double ReInterp = std::log(Re);
        AFI_ComputeUACoefs2D(ReInterp, p, UA_BL, errStat, errMsg);
    } else {  // AFITable_2User
        AFI_ComputeUACoefs2D(UserProp, p, UA_BL, errStat, errMsg);
    }

    // Post-dispatch: normalize angle outputs to [-Pi, Pi]
    UA_BL->alpha0 = MPi2Pi(UA_BL->alpha0);
    UA_BL->alpha1 = MPi2Pi(UA_BL->alpha1);
    UA_BL->alpha2 = MPi2Pi(UA_BL->alpha2);
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void afi_computeuacoefs_c(afi_parametertype_view_t* p, double Re, double UserProp, afi_ua_bl_type_t* UA_BL, char* errMsg, int* errStat) {
        AFI_ComputeUACoefs(p, Re, UserProp, UA_BL, errMsg, errStat);
    }
}
