// C++ implementation of Fortran function: Calculate_Cn
// Generated by VIT (Verified Incremental Translator)
// After verification: Calculate_Cn kernel PASSED

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: Calculate_Cn
// Source: AirfoilInfo.f90
// Module: AirfoilInfo
// Fortran: FUNCTION Calculate_Cn(alpha, Cl, Cd, Cd0) RESULT(Cn)
// Source MD5: e870261d3759
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-24T14:16:52Z

#include <cmath>

void Calculate_Cn(double* alpha, int n_alpha, double* Cl, int n_Cl, double* Cd, int n_Cd, double Cd0, double* Calculate_Cn_result) {
    for (int i = 0; i < n_alpha; ++i) {
        Calculate_Cn_result[i] = Cl[i] * std::cos(alpha[i]) + (Cd[i] - Cd0) * std::sin(alpha[i]);
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void calculate_cn_c(double* alpha, int n_alpha, double* Cl, int n_Cl, double* Cd, int n_Cd, double Cd0, double* Calculate_Cn_result) {
        Calculate_Cn(alpha, n_alpha, Cl, n_Cl, Cd, n_Cd, Cd0, Calculate_Cn_result);
    }
}
