// C++ implementation of Fortran function: ComputeUA360_CnOffset
// Generated by VIT (Verified Incremental Translator)
// After verification: ComputeUA360_CnOffset kernel PASSED

#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: ComputeUA360_CnOffset
// Source: AirfoilInfo.f90
// Module: AirfoilInfo
// Fortran: FUNCTION ComputeUA360_CnOffset(p, cn_cl, Row, iLower) RESULT(offset)
// Source MD5: 857831738528
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-25T09:42:16Z

#include "vit_types.h"
#include "vit_nwtc.h"

double ComputeUA360_CnOffset(afi_table_type_view_t* p, double* cn_cl, int n_cn_cl, int Row, int iLower) {

    // Compute cnOffset — mathematical trick for strange polars
    double CnOffset;
    if (cn_cl[iLower - 1] > -0.05) {  // 1-based → 0-based
        CnOffset = cn_cl[iLower - 1] + 0.05;
    } else {
        CnOffset = 0.0;
    }

    double SlopeScale = 0.1 * R2D;
    double alpha_row = p->Alpha[Row - 1];  // 1-based → 0-based

    // Only apply Cn offset in vicinity of AoA 0 deg
    return CnOffset * (tanh(SlopeScale * (alpha_row + PiBy2))
                      - tanh(SlopeScale * (alpha_row - PiBy2))) / 2.0;
}

// --- Fortran-callable C wrapper ---
extern "C" {
    double computeua360_cnoffset_c(afi_table_type_view_t* p, double* cn_cl, int n_cn_cl, int Row, int iLower) {
        return ComputeUA360_CnOffset(p, cn_cl, n_cn_cl, Row, iLower);
    }
}
