// C++ implementation of Fortran function: ComputeUASeparationFunction_onCl
// Generated by VIT (Verified Incremental Translator)
// After verification: ComputeUASeparationFunction_onCl kernel PASSED

#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: ComputeUASeparationFunction_onCl
// Source: AirfoilInfo.f90
// Module: AirfoilInfo
// Fortran: SUBROUTINE ComputeUASeparationFunction_onCl(p, ColCl, ColUAf, col_fs, col_fa)
// Source MD5: 6b87ba706963
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-25T21:26:09Z

#include "vit_types.h"
#include <cmath>
#include "vit_nwtc.h"

// 2D column-major access: Coefs(Row, Col) in Fortran = Coefs[(Col-1)*nrows + (Row-1)] in C
#define COEFS(row1, col1) p->Coefs[((col1)-1) * p->n_Coefs_rows + ((row1)-1)]

void ComputeUASeparationFunction_onCl(afi_table_type_view_t* p, int ColCl, int ColUAf, int col_fs, int col_fa) {
    // Callee: ComputeUASeparationFunction_zero (already integrated, declared via vit_kernel_callees.h)
    // Signature: void computeuaseparationfunction_zero_c(void* p, int ColUAf, double* cn_cl, int n_cn_cl)

    if (EqualRealNos(p->UA_BL.C_lalpha, 0.0)) {
        // C_lalpha == 0: set f_st = 0, cl_fs = cl, cl_fa = 0
        for (int Row = 1; Row <= p->NumAlf; Row++) {
            COEFS(Row, ColUAf) = 0.0;
            COEFS(Row, col_fs) = COEFS(Row, ColCl);
            COEFS(Row, col_fa) = 0.0;
        }
        // Initialize break-point variables via separation_zero
        // Pass Coefs(:,ColCl) as the cn_cl array
        double* cl_col = &COEFS(1, ColCl);
        computeuaseparationfunction_zero_c(p, ColUAf, cl_col, p->NumAlf);
    } else {
        // C_lalpha != 0: compute f_st from Kirchhoff model
        for (int Row = 1; Row <= p->NumAlf; Row++) {
            double f_st;
            double fullySeparate;

            if (EqualRealNos(p->Alpha[Row - 1], p->UA_BL.alpha0)) {
                f_st = 1.0;                                              // Eq. 59
                fullySeparate = COEFS(Row, ColCl) / 2.0;                 // Eq. 61
            } else {
                double cl_ratio = COEFS(Row, ColCl) / (p->UA_BL.C_lalpha * (p->Alpha[Row - 1] - p->UA_BL.alpha0));
                cl_ratio = std::max(0.0, cl_ratio);

                f_st = (2.0 * std::sqrt(cl_ratio) - 1.0) * (2.0 * std::sqrt(cl_ratio) - 1.0);

                if (f_st < 1.0) {
                    f_st = std::max(0.0, f_st);
                    fullySeparate = (COEFS(Row, ColCl) - p->UA_BL.C_lalpha * (p->Alpha[Row - 1] - p->UA_BL.alpha0) * f_st) / (1.0 - f_st);  // Eq 61
                } else {
                    f_st = 1.0;
                    fullySeparate = COEFS(Row, ColCl) / 2.0;             // Eq. 61
                }
            }

            COEFS(Row, ColUAf) = f_st;
            COEFS(Row, col_fs) = fullySeparate;
            COEFS(Row, col_fa) = p->UA_BL.C_lalpha * (p->Alpha[Row - 1] - p->UA_BL.alpha0);
        }

        // Make separation function monotonic at boundaries
        double* cl_col = &COEFS(1, ColCl);
        computeuaseparationfunction_zero_c(p, ColUAf, cl_col, p->NumAlf);

        // Ensure consistency: recompute f_st from cl, cl_fs, cl_fa
        for (int Row = 1; Row <= p->NumAlf; Row++) {
            double fullySeparate = COEFS(Row, col_fs);
            double cl_inv = p->UA_BL.C_lalpha * (p->Alpha[Row - 1] - p->UA_BL.alpha0);  // Eq. 64

            if (!EqualRealNos(cl_inv, fullySeparate)) {
                double f_st = (COEFS(Row, ColCl) - fullySeparate) / (cl_inv - fullySeparate);  // Eq. 60
                f_st = std::max(0.0, f_st);
                f_st = std::min(1.0, f_st);
                COEFS(Row, ColUAf) = f_st;
            } else {
                COEFS(Row, ColUAf) = 1.0;
            }
        }
    }
}

#undef COEFS

// --- Fortran-callable C wrapper ---
extern "C" {
    void computeuaseparationfunction_oncl_c(afi_table_type_view_t* p, int ColCl, int ColUAf, int col_fs, int col_fa) {
        ComputeUASeparationFunction_onCl(p, ColCl, ColUAf, col_fs, col_fa);
    }
}
