// C++ implementation of Fortran function: Compute_iLoweriUpper
// Generated by VIT (Verified Incremental Translator)
// After verification: Compute_iLoweriUpper kernel PASSED

#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: Compute_iLoweriUpper
// Source: AirfoilInfo.f90
// Module: AirfoilInfo
// Fortran: SUBROUTINE Compute_iLoweriUpper(p, iLower, iUpper)
// Source MD5: 8fd66298e8f3
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-24T22:30:43Z

#include "vit_types.h"

void Compute_iLoweriUpper(afi_table_type_view_t* p, int* iLower, int* iUpper) {
    // MINLOC(p%alpha, DIM=1, MASK=p%alpha >= p%UA_BL%alphaLower)
    // Fortran MINLOC returns 1-based index of minimum value where mask is true
    double min_val = 1.0e30;
    int min_idx = 1;  // 1-based default
    for (int i = 0; i < p->n_Alpha; i++) {
        if (p->Alpha[i] >= p->UA_BL.alphaLower) {
            if (p->Alpha[i] < min_val) {
                min_val = p->Alpha[i];
                min_idx = i + 1;  // 1-based
            }
        }
    }
    *iLower = min_idx;

    // MAXLOC(p%alpha, DIM=1, MASK=p%alpha <= p%UA_BL%alphaUpper)
    // Fortran MAXLOC returns 1-based index of maximum value where mask is true
    double max_val = -1.0e30;
    int max_idx = 1;  // 1-based default
    for (int i = 0; i < p->n_Alpha; i++) {
        if (p->Alpha[i] <= p->UA_BL.alphaUpper) {
            if (p->Alpha[i] > max_val) {
                max_val = p->Alpha[i];
                max_idx = i + 1;  // 1-based
            }
        }
    }
    *iUpper = max_idx;

    // Clamp to valid ranges (1-based)
    int numAlf = p->NumAlf;
    *iLower = *iLower < 1 ? 1 : (*iLower > numAlf - 1 ? numAlf - 1 : *iLower);
    *iUpper = *iUpper < 2 ? 2 : (*iUpper > numAlf ? numAlf : *iUpper);
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void compute_iloweriupper_c(afi_table_type_view_t* p, int* iLower, int* iUpper) {
        Compute_iLoweriUpper(p, iLower, iUpper);
    }
}
