// C++ implementation of Fortran function: ComputeUA360_updateSeparationF
// Generated by VIT (Verified Incremental Translator)
// After verification: ComputeUA360_updateSeparationF kernel PASSED

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: ComputeUA360_updateSeparationF
// Source: AirfoilInfo.f90
// Module: AirfoilInfo
// Fortran: SUBROUTINE ComputeUA360_updateSeparationF(p, ColUAf, cn_cl, iLower, iUpper)
// Source MD5: feb41b9b53de
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-25T18:40:30Z

#include "vit_types.h"
#include <cmath>
#include <vector>
#include "vit_nwtc.h"

// 2D column-major access: Coefs(Row, Col) in Fortran = Coefs[(Col-1)*nrows + (Row-1)] in C
#define COEFS(row1, col1) p->Coefs[((col1)-1) * p->n_Coefs_rows + ((row1)-1)]

// Fortran CSHIFT: circular shift of array by 'shift' positions
// Positive shift moves elements left (element shift+1 becomes element 1)
static void cshift(const double* src, double* dst, int n, int shift) {
    // Normalize shift to [0, n)
    shift = ((shift % n) + n) % n;
    for (int i = 0; i < n; i++) {
        dst[i] = src[(i + shift) % n];
    }
}

void ComputeUA360_updateSeparationF(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl, int iLower, int iUpper) {
    int N = p->NumAlf;

    // Column number (1-based)
    int col_fa = ColUAf + 2;  // fully attached

    // Compute f_st (separation function)
    for (int Row = 1; Row <= N; Row++) {
        double offset = computeua360_cnoffset_c(p, cn_cl, n_cn_cl, Row, iLower);
        double CnRatio;
        if (EqualRealNos(COEFS(Row, col_fa), offset)) {
            CnRatio = 1.0;
        } else {
            CnRatio = (cn_cl[Row - 1] - offset) / (COEFS(Row, col_fa) - offset);
        }
        CnRatio = std::max(0.25, CnRatio);

        COEFS(Row, ColUAf) = (2.0 * std::sqrt(CnRatio) - 1.0) * (2.0 * std::sqrt(CnRatio) - 1.0);
        COEFS(Row, ColUAf) = std::min(COEFS(Row, ColUAf), 1.0);
        COEFS(Row, ColUAf) = std::max(0.0, COEFS(Row, ColUAf));
    }

    // Where col_fa == cn_cl, set f = 1
    for (int Row = iLower; Row <= iUpper; Row++) {
        COEFS(Row, ColUAf) = 1.0;
    }

    // Fix issues if there is a second peak near 180 degrees
    // iLowerBreak = maxloc(alpha, DIM=1, MASK=alpha <= alphaBreakLower)
    int iLowerBreak = 1;
    {
        double maxAlpha = -std::numeric_limits<double>::max();
        for (int i = 0; i < N; i++) {
            if (p->Alpha[i] <= p->UA_BL.alphaBreakLower) {
                if (p->Alpha[i] > maxAlpha) {
                    maxAlpha = p->Alpha[i];
                    iLowerBreak = i + 1;  // 1-based
                }
            }
        }
    }

    // CSHIFT: circular shift alpha and f_st by iLowerBreak positions
    std::vector<double> alpha_(N);
    std::vector<double> f_st(N);

    // Extract Coefs(:,ColUAf) into a temporary
    std::vector<double> coefs_col(N);
    for (int i = 0; i < N; i++) {
        coefs_col[i] = COEFS(i + 1, ColUAf);
    }

    cshift(p->Alpha, alpha_.data(), N, iLowerBreak);
    cshift(coefs_col.data(), f_st.data(), N, iLowerBreak);

    // Fix wrapped angles
    for (int Row = 1; Row < N; Row++) {  // Row 2..N (0-based: 1..N-1)
        if (alpha_[Row] < alpha_[Row - 1]) {
            alpha_[Row] = alpha_[Row] + TwoPi;
        }
    }

    // iReverseFlow = maxloc(f_st, DIM=1, MASK=alpha_ > alphaBreakUpper)
    int iReverseFlow = 1;
    {
        double maxF = -std::numeric_limits<double>::max();
        for (int i = 0; i < N; i++) {
            if (alpha_[i] > p->UA_BL.alphaBreakUpper) {
                if (f_st[i] > maxF) {
                    maxF = f_st[i];
                    iReverseFlow = i + 1;  // 1-based
                }
            }
        }
    }

    // iUpperBreak = minloc(alpha_, DIM=1, MASK=alpha_ >= alphaBreakUpper)
    int iUpperBreak = 1;
    {
        double minAlpha = std::numeric_limits<double>::max();
        for (int i = 0; i < N; i++) {
            if (alpha_[i] >= p->UA_BL.alphaBreakUpper) {
                if (alpha_[i] < minAlpha) {
                    minAlpha = alpha_[i];
                    iUpperBreak = i + 1;  // 1-based
                }
            }
        }
    }

    // Make monotonically decreasing from single peak (backward sweep)
    // Fortran: do Row=iReverseFlow-1,iUpperBreak+1,-1
    for (int Row = iReverseFlow - 1; Row >= iUpperBreak + 1; Row--) {
        int i = Row - 1;  // 0-based index
        if (EqualRealNos(f_st[i], 0.0)) f_st[i - 1] = 0.0;
        if (f_st[i - 1] > f_st[i]) f_st[i] = 0.5 * (f_st[i + 1] + f_st[i - 1]);
    }

    // Forward sweep
    // Fortran: do Row=iReverseFlow+1,p%NumAlf-1
    for (int Row = iReverseFlow + 1; Row <= N - 1; Row++) {
        int i = Row - 1;  // 0-based index
        if (EqualRealNos(f_st[i], 0.0)) f_st[i + 1] = 0.0;
        if (f_st[i + 1] > f_st[i]) f_st[i] = 0.5 * (f_st[i + 1] + f_st[i - 1]);
    }

    // Reverse CSHIFT: p%Coefs(:,ColUAf) = cshift(f_st, -iLowerBreak)
    std::vector<double> result(N);
    cshift(f_st.data(), result.data(), N, -iLowerBreak);
    for (int i = 0; i < N; i++) {
        COEFS(i + 1, ColUAf) = result[i];
    }
}

#undef COEFS

// --- Fortran-callable C wrapper ---
extern "C" {
    void computeua360_updateseparationf_c(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl, int iLower, int iUpper) {
        ComputeUA360_updateSeparationF(p, ColUAf, cn_cl, n_cn_cl, iLower, iUpper);
    }
}
