// C++ implementation of Fortran function: DBEMT_ValidateInitInp
// Generated by VIT (Verified Incremental Translator)
// After verification: DBEMT_ValidateInitInp kernel PASSED

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: DBEMT_ValidateInitInp
// Source: DBEMT.f90
// Module: DBEMT
// Fortran: SUBROUTINE DBEMT_ValidateInitInp(interval, InitInp, errStat, errMsg)
// Source MD5: 618383920580
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-05-01T00:59:02Z

#include "vit_types.h"
#include "vit_nwtc.h"
#include "vit_aerodyn_constants.h"
#include <cmath>
#include <cstring>
#include <limits>
#include <algorithm>

void DBEMT_ValidateInitInp(double interval, dbemt_initinputtype_view_t* InitInp, int* errStat, char* errMsg) {
    const char* RoutineName = "DBEMT_ValidateInitInp";
    double rlocalMax;
    int i, j;

    *errStat = ErrID_None;
    std::memset(errMsg, ' ', ErrMsgLen);

    if (interval <= std::sqrt(std::numeric_limits<double>::epsilon())) {
        SetErrStat(ErrID_Fatal, " The timestep size for DBEMT (interval) must be larger than sqrt(epsilon).", errStat, errMsg, RoutineName);
    }
    if ((InitInp->DBEMT_Mod != DBEMT_tauConst) && (InitInp->DBEMT_Mod != DBEMT_tauVaries) && (InitInp->DBEMT_Mod != DBEMT_cont_tauConst)) {
        SetErrStat(ErrID_Fatal, " DBEMT_Mod must be set to 1, 2, or 3.", errStat, errMsg, RoutineName);
    }

    if (InitInp->NumBlades < 1) {
        SetErrStat(ErrID_Fatal, " InitInp%numBlades must set to 1 or more.", errStat, errMsg, RoutineName);
    }
    if (InitInp->NumNodes < 2) {
        SetErrStat(ErrID_Fatal, " InitInp%numNodes must set to 2 or more.", errStat, errMsg, RoutineName);
    }

    if (InitInp->DBEMT_Mod == DBEMT_tauConst || InitInp->DBEMT_Mod == DBEMT_cont_tauConst) {

        if (InitInp->tau1_const <= 0.0) {
            SetErrStat(ErrID_Fatal, " InitInp%tau1_const must be greater than zero.", errStat, errMsg, RoutineName);
        }

        if (InitInp->rLocal == nullptr) {
            SetErrStat(ErrID_Fatal, " InitInput%rlocal must be allocated to size (InitInp%numNodes,InitInp%numBlades).", errStat, errMsg, RoutineName);
            return;
        }

        for (j = 1; j <= InitInp->NumBlades; j++) {
            rlocalMax = 0.0;
            for (i = 1; i <= InitInp->NumNodes; i++) {
                if (InitInp->rLocal[(j - 1) * InitInp->n_rLocal_rows + (i - 1)] <= 0.0) {
                    SetErrStat(ErrID_Fatal, " Blades nodes must be located at a positive radial distance (rlocal) greater than zero.", errStat, errMsg, RoutineName);
                    return;
                }

                rlocalMax = std::max(rlocalMax, InitInp->rLocal[(j - 1) * InitInp->n_rLocal_rows + (i - 1)]);
            }
            if (EqualRealNos(rlocalMax, 0.0)) {
                SetErrStat(ErrID_Fatal, " Blades must have nodes located at a radial distance (rlocal) greater than zero.  ", errStat, errMsg, RoutineName);
            }
        }

    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void dbemt_validateinitinp_c(double interval, dbemt_initinputtype_view_t* InitInp, int* errStat, char* errMsg) {
        DBEMT_ValidateInitInp(interval, InitInp, errStat, errMsg);
    }
}
