// C++ implementation of Fortran function: DBEMT_Init
// Generated by VIT (Verified Incremental Translator)
// After verification: DBEMT_Init kernel PASSED

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: DBEMT_Init
// Source: DBEMT.f90
// Module: DBEMT
// Fortran: SUBROUTINE DBEMT_Init(InitInp, u, p, x, OtherState, m, Interval, InitOut, ErrStat, ErrMsg)
// Source MD5: 6763116699c8
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-05-01T10:59:10Z
//
// NOTE: This is the computational core only. The Fortran wrapper handles:
//   - InitOut%Ver = ProgDesc('DBEMT', '', '')
//   - DBEMT_ValidateInitInp call + error check
//   - All ALLOCATE statements (u%element, p%spanRatio, x%element, OtherState%n, xdot, areStatesInitialized)
//   - DBEMT_CopyContState for xdot history slots
//   - DBEMT_ReInit call

#include "vit_types.h"
#include "vit_aerodyn_constants.h"
#include <algorithm>

void DBEMT_Init(dbemt_initinputtype_view_t* InitInp, dbemt_inputtype_view_t* u, dbemt_parametertype_view_t* p, dbemt_continuousstatetype_view_t* x, dbemt_otherstatetype_view_t* OtherState, dbemt_miscvartype_t* m, double Interval, int* ErrStat, char* ErrMsg) {
    p->DBEMT_Mod = InitInp->DBEMT_Mod;
    p->DT = Interval;
    p->NumBlades = InitInp->NumBlades;
    p->NumNodes = InitInp->NumNodes;
    p->k_0ye = 0.6;
    p->tau1_const = InitInp->tau1_const;

    if (InitInp->DBEMT_Mod == DBEMT_tauConst || InitInp->DBEMT_Mod == DBEMT_cont_tauConst) {
        double rTip = 0.0;
        for (int j = 1; j <= InitInp->NumBlades; j++) {
            for (int i = 1; i <= InitInp->NumNodes; i++) {
                int idx = (j - 1) * InitInp->n_rLocal_rows + (i - 1);
                rTip = std::max(rTip, InitInp->rLocal[idx]);
            }
        }

        for (int j = 1; j <= p->NumBlades; j++) {
            for (int i = 1; i <= p->NumNodes; i++) {
                int rlocal_idx = (j - 1) * InitInp->n_rLocal_rows + (i - 1);
                int span_idx = (j - 1) * p->n_spanRatio_rows + (i - 1);
                p->spanRatio[span_idx] = InitInp->rLocal[rlocal_idx] / rTip;
            }
        }
    }

    if (p->DBEMT_Mod == DBEMT_cont_tauConst) {
        p->lin_nx = p->NumNodes * p->NumBlades * 4;
    } else {
        p->lin_nx = 0;
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void dbemt_init_c(dbemt_initinputtype_view_t* InitInp, dbemt_inputtype_view_t* u, dbemt_parametertype_view_t* p, dbemt_continuousstatetype_view_t* x, dbemt_otherstatetype_view_t* OtherState, dbemt_miscvartype_t* m, double Interval, int* ErrStat, char* ErrMsg) {
        DBEMT_Init(InitInp, u, p, x, OtherState, m, Interval, ErrStat, ErrMsg);
    }
}
