// C++ implementation of Fortran function: DBEMT_CalcOutput
// Generated by VIT (Verified Incremental Translator)
// After verification: DBEMT_CalcOutput kernel PASSED

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: DBEMT_CalcOutput
// Source: DBEMT.f90
// Module: DBEMT
// Fortran: SUBROUTINE DBEMT_CalcOutput(i, j, t, u, y_vind, p, x, OtherState, m, errStat, errMsg)
// Source MD5: dea2805152c3
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-29T21:48:49Z

#include "vit_types.h"
#include "vit_nwtc.h"
#include <cstring>

void DBEMT_CalcOutput(int i, int j, double t, dbemt_inputtype_view_t* u, double* y_vind, dbemt_parametertype_view_t* p, dbemt_continuousstatetype_view_t* x, dbemt_otherstatetype_view_t* OtherState, dbemt_miscvartype_t* m, int* errStat, char* errMsg) {
    *errStat = 0;
    std::memset(errMsg, ' ', ErrMsgLen);

    int os_idx = (j - 1) * OtherState->n_areStatesInitialized_rows + (i - 1);

    if (!OtherState->areStatesInitialized[os_idx]) {
        int u_idx = (j - 1) * u->n_element_rows + (i - 1);
        y_vind[0] = u->element[u_idx].vind_s[0];
        y_vind[1] = u->element[u_idx].vind_s[1];
    } else {
        int x_idx = (j - 1) * x->n_element_rows + (i - 1);
        y_vind[0] = x->element[x_idx].vind[0];
        y_vind[1] = x->element[x_idx].vind[1];
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void dbemt_calcoutput_c(int i, int j, double t, dbemt_inputtype_view_t* u, double* y_vind, dbemt_parametertype_view_t* p, dbemt_continuousstatetype_view_t* x, dbemt_otherstatetype_view_t* OtherState, dbemt_miscvartype_t* m, int* errStat, char* errMsg) {
        DBEMT_CalcOutput(i, j, t, u, y_vind, p, x, OtherState, m, errStat, errMsg);
    }
}
