// C++ implementation of Fortran function: DBEMT_InitStates_AllNodes
// Generated by VIT (Verified Incremental Translator)
// After verification: DBEMT_InitStates_AllNodes kernel PASSED

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: DBEMT_InitStates_AllNodes
// Source: DBEMT.f90
// Module: DBEMT
// Fortran: SUBROUTINE DBEMT_InitStates_AllNodes(u, p, x, OtherState)
// Source MD5: 19281cd270a5
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-30T17:13:23Z

#include "vit_types.h"

extern "C" {
    void dbemt_initstates_c(int i, int j, dbemt_inputtype_view_t* u,
                            dbemt_parametertype_view_t* p,
                            dbemt_continuousstatetype_view_t* x,
                            dbemt_otherstatetype_view_t* OtherState);
}

void DBEMT_InitStates_AllNodes(dbemt_inputtype_view_t* u,
                               dbemt_parametertype_view_t* p,
                               dbemt_continuousstatetype_view_t* x,
                               dbemt_otherstatetype_view_t* OtherState) {
    for (int j = 1; j <= x->n_element_cols; j++) {
        for (int i = 1; i <= x->n_element_rows; i++) {
            dbemt_initstates_c(i, j, u, p, x, OtherState);
        }
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void dbemt_initstates_allnodes_c(dbemt_inputtype_view_t* u, dbemt_parametertype_view_t* p, dbemt_continuousstatetype_view_t* x, dbemt_otherstatetype_view_t* OtherState) {
        DBEMT_InitStates_AllNodes(u, p, x, OtherState);
    }
}
