// C++ implementation of Fortran function: DBEMT_UpdateStates
// Generated by VIT (Verified Incremental Translator)
// After verification: DBEMT_UpdateStates kernel PASSED

#include "vit_types.h"
#include "vit_translated.h"

// --- User-provided C++ implementation ---
// VIT Translation Scaffold
// Function: DBEMT_UpdateStates
// Source: DBEMT.f90
// Module: DBEMT
// Fortran: SUBROUTINE DBEMT_UpdateStates(i, j, t, n, u, uTimes, p, x, OtherState, m, errStat, errMsg)
// Source MD5: 93bb7758e558
// VIT: 0.1.0
// Status: unverified
// Generated: 2026-04-30T14:32:57Z

#include "vit_types.h"
#include "vit_nwtc.h"
#include "vit_aerodyn_constants.h"
#include <cmath>
#include <cstring>

extern "C" {
    void computetau1_c(dbemt_inputtype_view_t* u, dbemt_parametertype_view_t* p,
                       dbemt_miscvartype_t* m, double* tau1, int* errStat, char* errMsg);
    void computetau2_c(int i, int j, dbemt_elementinputtype_t* u,
                       dbemt_parametertype_view_t* p, double tau1, double* tau2,
                       int has_k_tau_out, double* k_tau_out);
    void dbemt_initstates_c(int i, int j, dbemt_inputtype_view_t* u,
                            dbemt_parametertype_view_t* p,
                            dbemt_continuousstatetype_view_t* x,
                            dbemt_otherstatetype_view_t* OtherState);
    void dbemt_abm4_c(int i, int j, double t, int n,
                      dbemt_elementinputtype_t* u, int n_u,
                      double* utimes, int n_utimes,
                      dbemt_parametertype_view_t* p,
                      dbemt_continuousstatetype_view_t* x,
                      dbemt_otherstatetype_view_t* OtherState,
                      dbemt_miscvartype_t* m, int* ErrStat, char* ErrMsg);
}

void DBEMT_UpdateStates(int i, int j, double t, int n,
                        dbemt_inputtype_view_t* u, int n_u,
                        double* uTimes,
                        dbemt_parametertype_view_t* p,
                        dbemt_continuousstatetype_view_t* x,
                        dbemt_otherstatetype_view_t* OtherState,
                        dbemt_miscvartype_t* m,
                        int* errStat, char* errMsg) {

    double A, B, C0, k_tau, C0_2;

    *errStat = ErrID_None;
    std::memset(errMsg, ' ', ErrMsgLen);

    // Element index for 2D column-major arrays: element(i,j) -> [(j-1)*n_rows + (i-1)]
    int x_idx = (j - 1) * x->n_element_rows + (i - 1);

    computetau1_c(&u[0], p, m, &OtherState->tau1, errStat, errMsg);
    if (*errStat >= AbortErrLev) return;

    computetau2_c(i, j, &u[0].element[x_idx], p, OtherState->tau1,
                  &OtherState->tau2, 1, &k_tau);

    dbemt_initstates_c(i, j, &u[0], p, x, OtherState);

    if (p->DBEMT_Mod == DBEMT_cont_tauConst) {
        // Continuous formulation: call ABM4
        dbemt_elementinputtype_t u_elem[2];
        u_elem[0] = u[0].element[x_idx];
        u_elem[1] = u[1].element[x_idx];

        dbemt_abm4_c(i, j, t, n, u_elem, 2, uTimes, 2,
                     p, x, OtherState, m, errStat, errMsg);

    } else {
        // Finite difference formulation
        for (int indx = 0; indx < 2; indx++) {

            B = (u[1].element[x_idx].vind_s[indx] - u[0].element[x_idx].vind_s[indx]) / p->DT;
            A = u[0].element[x_idx].vind_s[indx] + B * p->k_0ye * OtherState->tau1;

            C0 = x->element[x_idx].vind_1[indx] - A + B * OtherState->tau1;

            x->element[x_idx].vind_1[indx] = C0 * std::exp(-p->DT / OtherState->tau1) + A + B * (p->DT - OtherState->tau1);

            C0_2 = x->element[x_idx].vind[indx] - C0 / (1.0 - k_tau) - A + B * (OtherState->tau1 + OtherState->tau2);
            x->element[x_idx].vind[indx] = C0_2 * std::exp(-p->DT / OtherState->tau2) + A + B * (p->DT - OtherState->tau1 - OtherState->tau2)
                                          + (C0 / (1.0 - k_tau)) * std::exp(-p->DT / OtherState->tau1);
        }
    }
}

// --- Fortran-callable C wrapper ---
extern "C" {
    void dbemt_updatestates_c(int i, int j, double t, int n, dbemt_inputtype_view_t* u, int n_u, double* uTimes, dbemt_parametertype_view_t* p, dbemt_continuousstatetype_view_t* x, dbemt_otherstatetype_view_t* OtherState, dbemt_miscvartype_t* m, int* errStat, char* errMsg) {
        DBEMT_UpdateStates(i, j, t, n, u, n_u, uTimes, p, x, OtherState, m, errStat, errMsg);
    }
}
