! Auto-generated by VIT (Verified Incremental Translator)
! View populator for TYPE(AFI_ParameterType)
! DO NOT EDIT — regenerate with: vit analyze-types --scan-allocatable --type AFI_ParameterType

MODULE vit_afi_parametertype_view
    USE ISO_C_BINDING
    USE ISO_FORTRAN_ENV, ONLY: ERROR_UNIT
    USE AirfoilInfo_Types, ONLY: AFI_ParameterType, ReKi
    USE vit_afi_table_type_view, ONLY: afi_table_type_view_t, vit_populate_afi_table_type, &
        vit_copy_scalars_to_afi_table_type, vit_adopt_afi_table_type
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: afi_parametertype_view_t, vit_populate_afi_parametertype, vit_copy_scalars_to_afi_parametertype, vit_original_afi_parametertype
    PUBLIC :: vit_direct_afi_parametertype, vit_view_in_afi_parametertype, vit_view_out_afi_parametertype
    PUBLIC :: vit_snapshot_afi_parametertype, vit_adopt_afi_parametertype

    INTERFACE
        SUBROUTINE vit_c_free(p) BIND(C, NAME='free')
            IMPORT :: C_PTR
            TYPE(C_PTR), VALUE :: p
        END SUBROUTINE vit_c_free
    END INTERFACE

    TYPE, BIND(C) :: vit_adopt_header_t
        INTEGER(C_INT64_T) :: magic
        TYPE(C_PTR) :: base
        INTEGER(C_INT32_T) :: rank
        INTEGER(C_INT32_T) :: lb(3)
    END TYPE vit_adopt_header_t
    INTEGER(C_INT64_T), PARAMETER :: VIT_ADOPT_MAGIC = INT(Z'5649544144505431', C_INT64_T)

    ! Kernel stash: pointer to original Fortran type, set by wrapper before calling C++.
    ! Callee bridges USE this to pass the original type to Fortran callees.
    TYPE(AFI_ParameterType), POINTER, SAVE :: vit_original_afi_parametertype => NULL()

    ! DIRECT-CALLER ORIGINAL. The stash above is set by an integration or
    ! kernel WRAPPER before it calls the C++. A C++ caller with NO wrapper --
    ! the differential harness calls the translation directly -- leaves it
    ! NULL, and a callee bridge that passes it dereferences a null pointer.
    ! This is the object the bridge points it at in that case.
    TYPE(AFI_ParameterType), TARGET, SAVE :: vit_direct_afi_parametertype
    TYPE(afi_table_type_view_t), ALLOCATABLE, TARGET, SAVE :: vit_table_views_afi_parametertype(:)
    TYPE(afi_table_type_view_t), ALLOCATABLE, SAVE :: vit_table_snaps_afi_parametertype(:)

    ! Mirror of the C view struct — layout MUST match afi_parametertype_view_t in C header
    TYPE, BIND(C) :: afi_parametertype_view_t
        INTEGER(C_INT) :: ColCd = 0
        INTEGER(C_INT) :: ColCl = 0
        INTEGER(C_INT) :: ColCm = 0
        INTEGER(C_INT) :: ColCpmin = 0
        INTEGER(C_INT) :: ColUAf = 0
        INTEGER(C_INT) :: AFTabMod = 0
        INTEGER(C_INT) :: InterpOrd = 0
        REAL(C_DOUBLE) :: RelThickness = 0
        REAL(C_DOUBLE) :: NonDimArea = 0
        INTEGER(C_INT) :: NumCoords = 0
        INTEGER(C_INT) :: NumTabs = 0
        CHARACTER(KIND=C_CHAR) :: BL_file(1024)
        CHARACTER(KIND=C_CHAR) :: FileName(1024)
        ! ALLOCATABLE fields (pointer + size)
        TYPE(C_PTR) :: secondVals = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_secondVals = 0
        TYPE(C_PTR) :: X_Coord = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_X_Coord = 0
        TYPE(C_PTR) :: Y_Coord = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_Y_Coord = 0
        TYPE(C_PTR) :: Table = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_Table = 0
    END TYPE afi_parametertype_view_t

CONTAINS

    SUBROUTINE vit_populate_afi_parametertype(src, view)
        TYPE(AFI_ParameterType), INTENT(IN), TARGET :: src
        TYPE(afi_parametertype_view_t), INTENT(OUT) :: view
        INTEGER :: vit_i

        ! --- Scalars ---
        view%ColCd = INT(src%ColCd, C_INT)
        view%ColCl = INT(src%ColCl, C_INT)
        view%ColCm = INT(src%ColCm, C_INT)
        view%ColCpmin = INT(src%ColCpmin, C_INT)
        view%ColUAf = INT(src%ColUAf, C_INT)
        view%AFTabMod = INT(src%AFTabMod, C_INT)
        view%InterpOrd = INT(src%InterpOrd, C_INT)
        view%RelThickness = REAL(src%RelThickness, C_DOUBLE)
        view%NonDimArea = REAL(src%NonDimArea, C_DOUBLE)
        view%NumCoords = INT(src%NumCoords, C_INT)
        view%NumTabs = INT(src%NumTabs, C_INT)
        view%BL_file = TRANSFER(src%BL_file, view%BL_file)
        view%FileName = TRANSFER(src%FileName, view%FileName)

        ! --- ALLOCATABLE arrays ---
        IF (ALLOCATED(src%secondVals)) THEN
            view%secondVals = C_LOC(src%secondVals(LBOUND(src%secondVals,1)))
            view%n_secondVals = INT(SIZE(src%secondVals), C_INT32_T)
        ELSE
            view%secondVals = C_NULL_PTR
            view%n_secondVals = 0
        END IF
        IF (ALLOCATED(src%X_Coord)) THEN
            view%X_Coord = C_LOC(src%X_Coord(LBOUND(src%X_Coord,1)))
            view%n_X_Coord = INT(SIZE(src%X_Coord), C_INT32_T)
        ELSE
            view%X_Coord = C_NULL_PTR
            view%n_X_Coord = 0
        END IF
        IF (ALLOCATED(src%Y_Coord)) THEN
            view%Y_Coord = C_LOC(src%Y_Coord(LBOUND(src%Y_Coord,1)))
            view%n_Y_Coord = INT(SIZE(src%Y_Coord), C_INT32_T)
        ELSE
            view%Y_Coord = C_NULL_PTR
            view%n_Y_Coord = 0
        END IF
        IF (ALLOCATED(src%Table)) THEN
            IF (ALLOCATED(vit_table_views_afi_parametertype)) DEALLOCATE(vit_table_views_afi_parametertype)
            ALLOCATE(vit_table_views_afi_parametertype(SIZE(src%Table)))
            DO vit_i = 1, SIZE(src%Table)
                CALL vit_populate_afi_table_type(src%Table(vit_i), vit_table_views_afi_parametertype(vit_i))
            END DO
            view%Table = C_LOC(vit_table_views_afi_parametertype(1))
            view%n_Table = INT(SIZE(src%Table), C_INT32_T)
        ELSE
            view%Table = C_NULL_PTR
            view%n_Table = 0
        END IF

    END SUBROUTINE vit_populate_afi_parametertype

    SUBROUTINE vit_copy_scalars_to_afi_parametertype(view, dest)
        TYPE(afi_parametertype_view_t), INTENT(IN) :: view
        TYPE(AFI_ParameterType), INTENT(INOUT) :: dest
        INTEGER :: i

        ! --- Scalars (reverse of populator) ---
        dest%ColCd = INT(view%ColCd, C_INT)
        dest%ColCl = INT(view%ColCl, C_INT)
        dest%ColCm = INT(view%ColCm, C_INT)
        dest%ColCpmin = INT(view%ColCpmin, C_INT)
        dest%ColUAf = INT(view%ColUAf, C_INT)
        dest%AFTabMod = INT(view%AFTabMod, C_INT)
        dest%InterpOrd = INT(view%InterpOrd, C_INT)
        dest%RelThickness = REAL(view%RelThickness, C_DOUBLE)
        dest%NonDimArea = REAL(view%NonDimArea, C_DOUBLE)
        dest%NumCoords = INT(view%NumCoords, C_INT)
        dest%NumTabs = INT(view%NumTabs, C_INT)
        DO i = 1, 1024
            dest%BL_file(i:i) = view%BL_file(i)
        END DO
        DO i = 1, 1024
            dest%FileName(i:i) = view%FileName(i)
        END DO

    END SUBROUTINE vit_copy_scalars_to_afi_parametertype

    SUBROUTINE vit_view_in_afi_parametertype(view, dest)
        ! view -> Fortran TYPE, reading the CALLER'S buffers.
        TYPE(afi_parametertype_view_t), INTENT(IN) :: view
        TYPE(AFI_ParameterType), INTENT(INOUT) :: dest
        INTEGER :: i
        REAL(ReKi), POINTER :: vit_ap_secondvals(:)
        REAL(ReKi), POINTER :: vit_ap_x_coord(:)
        REAL(ReKi), POINTER :: vit_ap_y_coord(:)

        ! The direct-caller conversion is not measured on these field(s):
        !  Table
        ERROR STOP 'VIT: vit_view_in_afi_parametertype: an unmeasured field kind; see the comment above'
        dest%ColCd = INT(view%ColCd, C_INT)
        dest%ColCl = INT(view%ColCl, C_INT)
        dest%ColCm = INT(view%ColCm, C_INT)
        dest%ColCpmin = INT(view%ColCpmin, C_INT)
        dest%ColUAf = INT(view%ColUAf, C_INT)
        dest%AFTabMod = INT(view%AFTabMod, C_INT)
        dest%InterpOrd = INT(view%InterpOrd, C_INT)
        dest%RelThickness = REAL(view%RelThickness, C_DOUBLE)
        dest%NonDimArea = REAL(view%NonDimArea, C_DOUBLE)
        dest%NumCoords = INT(view%NumCoords, C_INT)
        dest%NumTabs = INT(view%NumTabs, C_INT)
        DO i = 1, 1024
            dest%BL_file(i:i) = view%BL_file(i)
        END DO
        DO i = 1, 1024
            dest%FileName(i:i) = view%FileName(i)
        END DO
        IF (ALLOCATED(dest%secondVals)) DEALLOCATE(dest%secondVals)
        IF (C_ASSOCIATED(view%secondVals) .AND. view%n_secondVals > 0) THEN
            CALL C_F_POINTER(view%secondVals, vit_ap_secondvals, [INT(view%n_secondVals)])
            ALLOCATE(dest%secondVals(view%n_secondVals))
            dest%secondVals = vit_ap_secondvals
        ELSE IF (view%n_secondVals == 0) THEN
            ALLOCATE(dest%secondVals(0))   ! allocated-empty, distinct from unallocated
        END IF
        IF (ALLOCATED(dest%X_Coord)) DEALLOCATE(dest%X_Coord)
        IF (C_ASSOCIATED(view%X_Coord) .AND. view%n_X_Coord > 0) THEN
            CALL C_F_POINTER(view%X_Coord, vit_ap_x_coord, [INT(view%n_X_Coord)])
            ALLOCATE(dest%X_Coord(view%n_X_Coord))
            dest%X_Coord = vit_ap_x_coord
        ELSE IF (view%n_X_Coord == 0) THEN
            ALLOCATE(dest%X_Coord(0))   ! allocated-empty, distinct from unallocated
        END IF
        IF (ALLOCATED(dest%Y_Coord)) DEALLOCATE(dest%Y_Coord)
        IF (C_ASSOCIATED(view%Y_Coord) .AND. view%n_Y_Coord > 0) THEN
            CALL C_F_POINTER(view%Y_Coord, vit_ap_y_coord, [INT(view%n_Y_Coord)])
            ALLOCATE(dest%Y_Coord(view%n_Y_Coord))
            dest%Y_Coord = vit_ap_y_coord
        ELSE IF (view%n_Y_Coord == 0) THEN
            ALLOCATE(dest%Y_Coord(0))   ! allocated-empty, distinct from unallocated
        END IF

    END SUBROUTINE vit_view_in_afi_parametertype

    SUBROUTINE vit_view_out_afi_parametertype(src, view)
        ! Fortran TYPE -> view, writing INTO the caller's buffer and
        ! leaving its pointer and capacity exactly as it supplied them.
        TYPE(AFI_ParameterType), INTENT(IN) :: src
        TYPE(afi_parametertype_view_t), INTENT(INOUT) :: view
        REAL(ReKi), POINTER :: vit_ap_secondvals(:)
        REAL(ReKi), POINTER :: vit_ap_x_coord(:)
        REAL(ReKi), POINTER :: vit_ap_y_coord(:)

        ! The direct-caller conversion is not measured on these field(s):
        !  Table
        ERROR STOP 'VIT: vit_view_out_afi_parametertype: an unmeasured field kind; see the comment above'
        view%ColCd = INT(src%ColCd, C_INT)
        view%ColCl = INT(src%ColCl, C_INT)
        view%ColCm = INT(src%ColCm, C_INT)
        view%ColCpmin = INT(src%ColCpmin, C_INT)
        view%ColUAf = INT(src%ColUAf, C_INT)
        view%AFTabMod = INT(src%AFTabMod, C_INT)
        view%InterpOrd = INT(src%InterpOrd, C_INT)
        view%RelThickness = REAL(src%RelThickness, C_DOUBLE)
        view%NonDimArea = REAL(src%NonDimArea, C_DOUBLE)
        view%NumCoords = INT(src%NumCoords, C_INT)
        view%NumTabs = INT(src%NumTabs, C_INT)
        view%BL_file = TRANSFER(src%BL_file, view%BL_file)
        view%FileName = TRANSFER(src%FileName, view%FileName)
        IF (C_ASSOCIATED(view%secondVals) .AND. view%n_secondVals > 0) THEN
            IF (ALLOCATED(src%secondVals)) THEN
                IF (SIZE(src%secondVals) == view%n_secondVals) THEN
                    CALL C_F_POINTER(view%secondVals, vit_ap_secondvals, [INT(view%n_secondVals)])
                    vit_ap_secondvals = src%secondVals
                ELSE
                    WRITE(ERROR_UNIT,'(A,I0,A,I0,A)') &
                        'VIT: AFI_ParameterType%secondVals came back at ', SIZE(src%secondVals), &
                        ' element(s) against the ', view%n_secondVals, &
                        ' the caller supplied; left unchanged'
                END IF
            END IF
        END IF
        IF (C_ASSOCIATED(view%X_Coord) .AND. view%n_X_Coord > 0) THEN
            IF (ALLOCATED(src%X_Coord)) THEN
                IF (SIZE(src%X_Coord) == view%n_X_Coord) THEN
                    CALL C_F_POINTER(view%X_Coord, vit_ap_x_coord, [INT(view%n_X_Coord)])
                    vit_ap_x_coord = src%X_Coord
                ELSE
                    WRITE(ERROR_UNIT,'(A,I0,A,I0,A)') &
                        'VIT: AFI_ParameterType%X_Coord came back at ', SIZE(src%X_Coord), &
                        ' element(s) against the ', view%n_X_Coord, &
                        ' the caller supplied; left unchanged'
                END IF
            END IF
        END IF
        IF (C_ASSOCIATED(view%Y_Coord) .AND. view%n_Y_Coord > 0) THEN
            IF (ALLOCATED(src%Y_Coord)) THEN
                IF (SIZE(src%Y_Coord) == view%n_Y_Coord) THEN
                    CALL C_F_POINTER(view%Y_Coord, vit_ap_y_coord, [INT(view%n_Y_Coord)])
                    vit_ap_y_coord = src%Y_Coord
                ELSE
                    WRITE(ERROR_UNIT,'(A,I0,A,I0,A)') &
                        'VIT: AFI_ParameterType%Y_Coord came back at ', SIZE(src%Y_Coord), &
                        ' element(s) against the ', view%n_Y_Coord, &
                        ' the caller supplied; left unchanged'
                END IF
            END IF
        END IF

    END SUBROUTINE vit_view_out_afi_parametertype

    SUBROUTINE vit_snapshot_afi_parametertype(view, snap)
        ! Pre-call copy of a view, for vit_adopt_afi_parametertype.
        TYPE(afi_parametertype_view_t), INTENT(IN) :: view
        TYPE(afi_parametertype_view_t), INTENT(OUT) :: snap
        TYPE(afi_table_type_view_t), POINTER :: vit_cv_table(:)

        snap = view
        IF (ALLOCATED(vit_table_snaps_afi_parametertype)) DEALLOCATE(vit_table_snaps_afi_parametertype)
        IF (C_ASSOCIATED(view%Table) .AND. view%n_Table > 0) THEN
            CALL C_F_POINTER(view%Table, vit_cv_table, [INT(view%n_Table)])
            ALLOCATE(vit_table_snaps_afi_parametertype(view%n_Table))
            vit_table_snaps_afi_parametertype = vit_cv_table
        END IF
    END SUBROUTINE vit_snapshot_afi_parametertype

    SUBROUTINE vit_adopt_afi_parametertype(view, snap, dest)
        ! Adopt the ALLOCATABLE components a C++ translation allocated.
        ! See view_populator._adopt_routines for the convention.
        TYPE(afi_parametertype_view_t), INTENT(IN) :: view
        TYPE(afi_parametertype_view_t), INTENT(IN) :: snap
        TYPE(AFI_ParameterType), INTENT(INOUT) :: dest
        LOGICAL :: vit_same
        TYPE(vit_adopt_header_t), POINTER :: vit_h
        INTEGER :: vit_i, vit_lb
        REAL(ReKi), POINTER :: vit_ad_secondvals(:)
        REAL(ReKi), POINTER :: vit_ad_x_coord(:)
        REAL(ReKi), POINTER :: vit_ad_y_coord(:)
        TYPE(afi_table_type_view_t), POINTER :: vit_cv_table(:)
        TYPE(afi_table_type_view_t) :: vit_zero_table   ! every component pointer NULL

        ! --- secondVals ---
        vit_same = C_ASSOCIATED(view%secondVals, snap%secondVals)
        IF (.NOT. C_ASSOCIATED(view%secondVals) .AND. &
            .NOT. C_ASSOCIATED(snap%secondVals)) vit_same = .TRUE.
        IF (.NOT. vit_same) THEN
            IF (ALLOCATED(dest%secondVals)) DEALLOCATE(dest%secondVals)
            IF (C_ASSOCIATED(view%secondVals)) THEN
                IF (C_ASSOCIATED(view%secondVals, snap%X_Coord)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%secondVals was set to the pre-call storage of AFI_P' // &
                        'arameterType%X_Coord; only a malloc buffer can be adopted'
                END IF
                IF (C_ASSOCIATED(view%secondVals, snap%Y_Coord)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%secondVals was set to the pre-call storage of AFI_P' // &
                        'arameterType%Y_Coord; only a malloc buffer can be adopted'
                END IF
                IF (C_ASSOCIATED(view%secondVals, snap%Table)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%secondVals was set to the pre-call storage of AFI_P' // &
                        'arameterType%Table; only a malloc buffer can be adopted'
                END IF
                vit_h => vit_adopt_header(view%secondVals, 1, 'AFI_ParameterType%secondVals')
                CALL C_F_POINTER(view%secondVals, vit_ad_secondvals, &
                    [INT(view%n_secondVals)])
                ALLOCATE(dest%secondVals( &
                    vit_h%lb(1):vit_h%lb(1)+view%n_secondVals-1))
                dest%secondVals = vit_ad_secondvals
                CALL vit_c_free(vit_h%base)
            END IF
        ELSE IF (C_ASSOCIATED(view%secondVals)) THEN
            IF (view%n_secondVals /= snap%n_secondVals) THEN
                ERROR STOP 'VIT adopt: AFI_ParameterType%secondVals changed extent without a new buffer; C++' // &
                    ' cannot resize Fortran storage in place'
            END IF
        END IF
        ! --- X_Coord ---
        vit_same = C_ASSOCIATED(view%X_Coord, snap%X_Coord)
        IF (.NOT. C_ASSOCIATED(view%X_Coord) .AND. &
            .NOT. C_ASSOCIATED(snap%X_Coord)) vit_same = .TRUE.
        IF (.NOT. vit_same) THEN
            IF (ALLOCATED(dest%X_Coord)) DEALLOCATE(dest%X_Coord)
            IF (C_ASSOCIATED(view%X_Coord)) THEN
                IF (C_ASSOCIATED(view%X_Coord, snap%secondVals)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%X_Coord was set to the pre-call storage of AFI_Para' // &
                        'meterType%secondVals; only a malloc buffer can be adopted'
                END IF
                IF (C_ASSOCIATED(view%X_Coord, snap%Y_Coord)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%X_Coord was set to the pre-call storage of AFI_Para' // &
                        'meterType%Y_Coord; only a malloc buffer can be adopted'
                END IF
                IF (C_ASSOCIATED(view%X_Coord, snap%Table)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%X_Coord was set to the pre-call storage of AFI_Para' // &
                        'meterType%Table; only a malloc buffer can be adopted'
                END IF
                vit_h => vit_adopt_header(view%X_Coord, 1, 'AFI_ParameterType%X_Coord')
                CALL C_F_POINTER(view%X_Coord, vit_ad_x_coord, &
                    [INT(view%n_X_Coord)])
                ALLOCATE(dest%X_Coord( &
                    vit_h%lb(1):vit_h%lb(1)+view%n_X_Coord-1))
                dest%X_Coord = vit_ad_x_coord
                CALL vit_c_free(vit_h%base)
            END IF
        ELSE IF (C_ASSOCIATED(view%X_Coord)) THEN
            IF (view%n_X_Coord /= snap%n_X_Coord) THEN
                ERROR STOP 'VIT adopt: AFI_ParameterType%X_Coord changed extent without a new buffer; C++ ca' // &
                    'nnot resize Fortran storage in place'
            END IF
        END IF
        ! --- Y_Coord ---
        vit_same = C_ASSOCIATED(view%Y_Coord, snap%Y_Coord)
        IF (.NOT. C_ASSOCIATED(view%Y_Coord) .AND. &
            .NOT. C_ASSOCIATED(snap%Y_Coord)) vit_same = .TRUE.
        IF (.NOT. vit_same) THEN
            IF (ALLOCATED(dest%Y_Coord)) DEALLOCATE(dest%Y_Coord)
            IF (C_ASSOCIATED(view%Y_Coord)) THEN
                IF (C_ASSOCIATED(view%Y_Coord, snap%secondVals)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%Y_Coord was set to the pre-call storage of AFI_Para' // &
                        'meterType%secondVals; only a malloc buffer can be adopted'
                END IF
                IF (C_ASSOCIATED(view%Y_Coord, snap%X_Coord)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%Y_Coord was set to the pre-call storage of AFI_Para' // &
                        'meterType%X_Coord; only a malloc buffer can be adopted'
                END IF
                IF (C_ASSOCIATED(view%Y_Coord, snap%Table)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%Y_Coord was set to the pre-call storage of AFI_Para' // &
                        'meterType%Table; only a malloc buffer can be adopted'
                END IF
                vit_h => vit_adopt_header(view%Y_Coord, 1, 'AFI_ParameterType%Y_Coord')
                CALL C_F_POINTER(view%Y_Coord, vit_ad_y_coord, &
                    [INT(view%n_Y_Coord)])
                ALLOCATE(dest%Y_Coord( &
                    vit_h%lb(1):vit_h%lb(1)+view%n_Y_Coord-1))
                dest%Y_Coord = vit_ad_y_coord
                CALL vit_c_free(vit_h%base)
            END IF
        ELSE IF (C_ASSOCIATED(view%Y_Coord)) THEN
            IF (view%n_Y_Coord /= snap%n_Y_Coord) THEN
                ERROR STOP 'VIT adopt: AFI_ParameterType%Y_Coord changed extent without a new buffer; C++ ca' // &
                    'nnot resize Fortran storage in place'
            END IF
        END IF
        ! --- Table: ALLOCATABLE TYPE(AFI_Table_Type) ---
        vit_same = C_ASSOCIATED(view%Table, snap%Table)
        IF (.NOT. C_ASSOCIATED(view%Table) .AND. &
            .NOT. C_ASSOCIATED(snap%Table)) vit_same = .TRUE.
        IF (vit_same) THEN
            IF (C_ASSOCIATED(view%Table)) THEN
                IF (view%n_Table /= snap%n_Table) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%Table changed extent without a new buffer'
                END IF
                IF (view%n_Table > 0) THEN
                    IF (.NOT. ALLOCATED(vit_table_snaps_afi_parametertype)) THEN
                        ERROR STOP 'VIT adopt: AFI_ParameterType%Table has no snapshot; vit_snapshot_afi_parameterty' // &
                            'pe must run before the C++ call'
                    END IF
                    CALL C_F_POINTER(view%Table, vit_cv_table, [INT(view%n_Table)])
                    vit_lb = LBOUND(dest%Table, 1)
                    DO vit_i = 1, view%n_Table
                        CALL vit_copy_scalars_to_afi_table_type(vit_cv_table(vit_i), &
                            dest%Table(vit_lb + vit_i - 1))
                        CALL vit_adopt_afi_table_type(vit_cv_table(vit_i), vit_table_snaps_afi_parametertype(vit_i), &
                            dest%Table(vit_lb + vit_i - 1))
                    END DO
                END IF
            END IF
        ELSE
            IF (ALLOCATED(dest%Table)) DEALLOCATE(dest%Table)
            IF (C_ASSOCIATED(view%Table)) THEN
                IF (C_ASSOCIATED(view%Table, snap%secondVals)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%Table was set to the pre-call storage of AFI_Parame' // &
                        'terType%secondVals; only a malloc buffer can be adopted'
                END IF
                IF (C_ASSOCIATED(view%Table, snap%X_Coord)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%Table was set to the pre-call storage of AFI_Parame' // &
                        'terType%X_Coord; only a malloc buffer can be adopted'
                END IF
                IF (C_ASSOCIATED(view%Table, snap%Y_Coord)) THEN
                    ERROR STOP 'VIT adopt: AFI_ParameterType%Table was set to the pre-call storage of AFI_Parame' // &
                        'terType%Y_Coord; only a malloc buffer can be adopted'
                END IF
                vit_h => vit_adopt_header(view%Table, 1, 'AFI_ParameterType%Table')
                vit_lb = vit_h%lb(1)
                CALL C_F_POINTER(view%Table, vit_cv_table, [INT(view%n_Table)])
                ALLOCATE(dest%Table(vit_lb:vit_lb+view%n_Table-1))
                DO vit_i = 1, view%n_Table
                    CALL vit_copy_scalars_to_afi_table_type(vit_cv_table(vit_i), &
                        dest%Table(vit_lb + vit_i - 1))
                    CALL vit_adopt_afi_table_type(vit_cv_table(vit_i), vit_zero_table, &
                        dest%Table(vit_lb + vit_i - 1))
                END DO
                CALL vit_c_free(vit_h%base)
            END IF
        END IF
    END SUBROUTINE vit_adopt_afi_parametertype

    FUNCTION vit_adopt_header(p, rank, what) RESULT(h)
        ! The header vit_adopt_alloc_lb put 32 bytes in front of buffer p.
        TYPE(C_PTR), INTENT(IN) :: p
        INTEGER, INTENT(IN) :: rank
        CHARACTER(*), INTENT(IN) :: what
        TYPE(vit_adopt_header_t), POINTER :: h
        INTEGER(C_INTPTR_T) :: a
        a = TRANSFER(p, a) - 32_C_INTPTR_T
        CALL C_F_POINTER(TRANSFER(a, p), h)
        IF (h%magic /= VIT_ADOPT_MAGIC) ERROR STOP 'VIT adopt: ' // what // &
            ' was not allocated with vit_adopt_alloc; only such a buffer can be adopted'
        IF (h%rank /= 0 .AND. h%rank /= rank) ERROR STOP 'VIT adopt: ' // what // &
            ' was allocated with vit_adopt_alloc_lb for a different rank'
    END FUNCTION vit_adopt_header

END MODULE vit_afi_parametertype_view
