! Auto-generated by VIT (Verified Incremental Translator)
! View populator for TYPE(DBEMT_InputType)
! DO NOT EDIT — regenerate with: vit analyze-types --scan-allocatable --type DBEMT_InputType

MODULE vit_dbemt_inputtype_view
    USE ISO_C_BINDING
    USE DBEMT_Types, ONLY: DBEMT_InputType
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: dbemt_inputtype_view_t, vit_populate_dbemt_inputtype, vit_copy_scalars_to_dbemt_inputtype, vit_original_dbemt_inputtype

    ! Kernel stash: pointer to original Fortran type, set by wrapper before calling C++.
    ! Callee bridges USE this to pass the original type to Fortran callees.
    TYPE(DBEMT_InputType), POINTER, SAVE :: vit_original_dbemt_inputtype => NULL()

    ! Mirror of the C view struct — layout MUST match dbemt_inputtype_view_t in C header
    TYPE, BIND(C) :: dbemt_inputtype_view_t
        REAL(C_DOUBLE) :: AxInd_disk = 0
        REAL(C_DOUBLE) :: Un_disk = 0
        REAL(C_DOUBLE) :: R_disk = 0
        ! ALLOCATABLE fields (pointer + size)
        TYPE(C_PTR) :: element = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_element_rows = 0
        INTEGER(C_INT32_T) :: n_element_cols = 0
    END TYPE dbemt_inputtype_view_t

CONTAINS

    SUBROUTINE vit_populate_dbemt_inputtype(src, view)
        TYPE(DBEMT_InputType), INTENT(IN), TARGET :: src
        TYPE(dbemt_inputtype_view_t), INTENT(OUT) :: view

        ! --- Scalars ---
        view%AxInd_disk = REAL(src%AxInd_disk, C_DOUBLE)
        view%Un_disk = REAL(src%Un_disk, C_DOUBLE)
        view%R_disk = REAL(src%R_disk, C_DOUBLE)

        ! --- ALLOCATABLE arrays ---
        IF (ALLOCATED(src%element)) THEN
            view%element = C_LOC(src%element(LBOUND(src%element,1),LBOUND(src%element,2)))
            view%n_element_rows = INT(SIZE(src%element, 1), C_INT32_T)
            view%n_element_cols = INT(SIZE(src%element, 2), C_INT32_T)
        ELSE
            view%element = C_NULL_PTR
            view%n_element_rows = 0
            view%n_element_cols = 0
        END IF

    END SUBROUTINE vit_populate_dbemt_inputtype

    SUBROUTINE vit_copy_scalars_to_dbemt_inputtype(view, dest)
        TYPE(dbemt_inputtype_view_t), INTENT(IN) :: view
        TYPE(DBEMT_InputType), INTENT(INOUT) :: dest

        ! --- Scalars (reverse of populator) ---
        dest%AxInd_disk = REAL(view%AxInd_disk, C_DOUBLE)
        dest%Un_disk = REAL(view%Un_disk, C_DOUBLE)
        dest%R_disk = REAL(view%R_disk, C_DOUBLE)

    END SUBROUTINE vit_copy_scalars_to_dbemt_inputtype

END MODULE vit_dbemt_inputtype_view
