// C struct definitions for Fortran derived types.
// Auto-generated by VIT. Do not edit manually.

#ifndef VIT_TYPES_H
#define VIT_TYPES_H

#include <stdint.h>

// Auto-generated C struct for Fortran TYPE(AFI_UA_BL_Type)
// Generated by VIT (Verified Incremental Translator)

#ifndef AFI_UA_BL_TYPE_T_H
#define AFI_UA_BL_TYPE_T_H

typedef struct {
    double alpha0;
    double alpha1;
    double alpha2;
    double eta_e;
    double C_nalpha;
    double C_lalpha;
    double T_f0;
    double T_V0;
    double T_p;
    double T_VL;
    double b1;
    double b2;
    double b5;
    double A1;
    double A2;
    double A5;
    double S1;
    double S2;
    double S3;
    double S4;
    double Cn1;
    double Cn2;
    double St_sh;
    double Cd0;
    double Cm0;
    double k0;
    double k1;
    double k2;
    double k3;
    double k1_hat;
    double x_cp_bar;
    double UACutout;
    double UACutout_delta;
    double UACutout_blend;
    double filtCutOff;
    double alphaUpper;
    double alphaLower;
    double c_alphaLower;
    double c_alphaUpper;
    double alpha0ReverseFlow;
    double alphaBreakUpper;
    double CnBreakUpper;
    double alphaBreakLower;
    double CnBreakLower;
} afi_ua_bl_type_t;

#endif // AFI_UA_BL_TYPE_T_H

// Auto-generated view struct for Fortran TYPE(AFI_Table_Type)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef AFI_TABLE_TYPE_VIEW_T_H
#define AFI_TABLE_TYPE_VIEW_T_H

#include <stdint.h>

typedef struct {
    // --- Scalar and fixed-size fields ---
    double UserProp;
    double Re;
    int NumAlf;
    int8_t ConstData;
    int8_t InclUAdata;
    afi_ua_bl_type_t UA_BL;

    // --- ALLOCATABLE fields (pointer + size) ---
    double* Alpha;
    int32_t n_Alpha;
    double* Coefs;  // column-major
    int32_t n_Coefs_rows;
    int32_t n_Coefs_cols;
    double* SplineCoefs;  // column-major
    int32_t n_SplineCoefs_dim1;
    int32_t n_SplineCoefs_dim2;
    int32_t n_SplineCoefs_dim3;
} afi_table_type_view_t;

#endif // AFI_TABLE_TYPE_VIEW_T_H

// Auto-generated view struct for Fortran TYPE(AFI_ParameterType)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef AFI_PARAMETERTYPE_VIEW_T_H
#define AFI_PARAMETERTYPE_VIEW_T_H

#include <stdint.h>

typedef struct {
    // --- Scalar and fixed-size fields ---
    int ColCd;
    int ColCl;
    int ColCm;
    int ColCpmin;
    int ColUAf;
    int AFTabMod;
    int InterpOrd;
    double RelThickness;
    double NonDimArea;
    int NumCoords;
    int NumTabs;
    char BL_file[1024];
    char FileName[1024];

    // --- ALLOCATABLE fields (pointer + size) ---
    double* secondVals;
    int32_t n_secondVals;
    double* X_Coord;
    int32_t n_X_Coord;
    double* Y_Coord;
    int32_t n_Y_Coord;
    afi_table_type_view_t* Table;  // Array of view structs, populated by Fortran
    int32_t n_Table;
} afi_parametertype_view_t;

#endif // AFI_PARAMETERTYPE_VIEW_T_H

// Auto-generated C struct for Fortran TYPE(AFI_UA_BL_Default_Type)
// Generated by VIT (Verified Incremental Translator)

#ifndef AFI_UA_BL_DEFAULT_TYPE_T_H
#define AFI_UA_BL_DEFAULT_TYPE_T_H

typedef struct {
    int32_t alpha0;
    int32_t alpha1;
    int32_t alpha2;
    int32_t eta_e;
    int32_t C_nalpha;
    int32_t C_lalpha;
    int32_t T_f0;
    int32_t T_V0;
    int32_t T_p;
    int32_t T_VL;
    int32_t b1;
    int32_t b2;
    int32_t b5;
    int32_t A1;
    int32_t A2;
    int32_t A5;
    int32_t S1;
    int32_t S2;
    int32_t S3;
    int32_t S4;
    int32_t Cn1;
    int32_t Cn2;
    int32_t St_sh;
    int32_t Cd0;
    int32_t Cm0;
    int32_t k0;
    int32_t k1;
    int32_t k2;
    int32_t k3;
    int32_t k1_hat;
    int32_t x_cp_bar;
    int32_t UACutout;
    int32_t UACutout_delta;
    int32_t filtCutOff;
    int32_t alphaUpper;
    int32_t alphaLower;
} afi_ua_bl_default_type_t;

#endif // AFI_UA_BL_DEFAULT_TYPE_T_H

// Auto-generated C struct for Fortran TYPE(AFI_InitInputType)
// Generated by VIT (Verified Incremental Translator)

#ifndef AFI_INITINPUTTYPE_T_H
#define AFI_INITINPUTTYPE_T_H

typedef struct {
    char FileName[1024];
    int AFTabMod;
    int InCol_Alfa;
    int InCol_Cl;
    int InCol_Cd;
    int InCol_Cm;
    int InCol_Cpmin;
    int UAMod;
} afi_initinputtype_t;

#endif // AFI_INITINPUTTYPE_T_H

// Auto-generated C struct for Fortran TYPE(AFI_OutputType)
// Generated by VIT (Verified Incremental Translator)

#ifndef AFI_OUTPUTTYPE_T_H
#define AFI_OUTPUTTYPE_T_H

typedef struct {
    double Cl;
    double Cd;
    double Cm;
    double Cpmin;
    double Cd0;
    double Cm0;
    double f_st;
    double FullySeparate;
    double FullyAttached;
} afi_outputtype_t;

#endif // AFI_OUTPUTTYPE_T_H

// ============================================================================
// DBEMT type definitions
// ============================================================================

// BIND(C)-compatible struct for Fortran TYPE(DBEMT_ElementInputType)
// All fixed-size fields — no view struct needed.
#ifndef DBEMT_ELEMENTINPUTTYPE_T_H
#define DBEMT_ELEMENTINPUTTYPE_T_H

typedef struct {
    double vind_s[2];
    double spanRatio;
} dbemt_elementinputtype_t;

#endif // DBEMT_ELEMENTINPUTTYPE_T_H

// View struct for Fortran TYPE(DBEMT_ParameterType)
// ALLOCATABLE field: spanRatio(:,:) exposed as pointer + row/col sizes.
#ifndef DBEMT_PARAMETERTYPE_VIEW_T_H
#define DBEMT_PARAMETERTYPE_VIEW_T_H

typedef struct {
    double DT;
    int lin_nx;
    int NumBlades;
    int NumNodes;
    double k_0ye;
    double tau1_const;
    int DBEMT_Mod;
    double* spanRatio;
    int32_t n_spanRatio_rows;
    int32_t n_spanRatio_cols;
} dbemt_parametertype_view_t;

#endif // DBEMT_PARAMETERTYPE_VIEW_T_H

// View struct for Fortran TYPE(DBEMT_InputType)
// ALLOCATABLE field: element(:,:) exposed as typed pointer + row/col sizes.
// ComputeTau1 only reads the 3 scalars; element is included for VIT's type system.
#ifndef DBEMT_INPUTTYPE_VIEW_T_H
#define DBEMT_INPUTTYPE_VIEW_T_H

typedef struct {
    double AxInd_disk;
    double Un_disk;
    double R_disk;
    dbemt_elementinputtype_t* element;
    int32_t n_element_rows;
    int32_t n_element_cols;
} dbemt_inputtype_view_t;

#endif // DBEMT_INPUTTYPE_VIEW_T_H

// BIND(C)-compatible struct for Fortran TYPE(DBEMT_MiscVarType)
// Single LOGICAL field. Fortran default LOGICAL is 4 bytes → int32_t.
#ifndef DBEMT_MISCVARTYPE_T_H
#define DBEMT_MISCVARTYPE_T_H

typedef struct {
    int32_t FirstWarn_tau1;
} dbemt_miscvartype_t;

#endif // DBEMT_MISCVARTYPE_T_H

// Auto-generated C struct for Fortran TYPE(DBEMT_ElementContinuousStateType)
// Generated by VIT (Verified Incremental Translator)

#ifndef DBEMT_ELEMENTCONTINUOUSSTATETYPE_T_H
#define DBEMT_ELEMENTCONTINUOUSSTATETYPE_T_H

typedef struct {
    double vind[2];
    double vind_1[2];
} dbemt_elementcontinuousstatetype_t;

#endif // DBEMT_ELEMENTCONTINUOUSSTATETYPE_T_H

// Auto-generated view struct for Fortran TYPE(DBEMT_ContinuousStateType)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef DBEMT_CONTINUOUSSTATETYPE_VIEW_T_H
#define DBEMT_CONTINUOUSSTATETYPE_VIEW_T_H

#include <stdint.h>

typedef struct {

    // --- ALLOCATABLE fields (pointer + size) ---
    dbemt_elementcontinuousstatetype_t* element;
    int32_t n_element_rows;
    int32_t n_element_cols;
} dbemt_continuousstatetype_view_t;

#endif // DBEMT_CONTINUOUSSTATETYPE_VIEW_T_H

// Auto-generated view struct for Fortran TYPE(DBEMT_OTHERSTATETYPE)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef DBEMT_OTHERSTATETYPE_VIEW_T_H
#define DBEMT_OTHERSTATETYPE_VIEW_T_H

#include <stdint.h>

typedef struct {
    // --- Scalar and fixed-size fields ---
    double tau1;
    double tau2;
    dbemt_continuousstatetype_view_t xdot[4];

    // --- ALLOCATABLE fields (pointer + size) ---
    int32_t* areStatesInitialized;  // column-major
    int32_t n_areStatesInitialized_rows;
    int32_t n_areStatesInitialized_cols;
    int32_t* n;  // column-major
    int32_t n_n_rows;
    int32_t n_n_cols;
} dbemt_otherstatetype_view_t;

#endif // DBEMT_OTHERSTATETYPE_VIEW_T_H

// Auto-generated view struct for Fortran TYPE(DBEMT_InitInputType)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef DBEMT_INITINPUTTYPE_VIEW_T_H
#define DBEMT_INITINPUTTYPE_VIEW_T_H

#include <stdint.h>

typedef struct {
    // --- Scalar and fixed-size fields ---
    int NumBlades;
    int NumNodes;
    double tau1_const;
    int DBEMT_Mod;

    // --- ALLOCATABLE fields (pointer + size) ---
    double* rLocal;  // column-major
    int32_t n_rLocal_rows;
    int32_t n_rLocal_cols;
} dbemt_initinputtype_view_t;

#endif // DBEMT_INITINPUTTYPE_VIEW_T_H

// Auto-generated C struct for Fortran TYPE(ProgDesc)
// Generated by VIT (Verified Incremental Translator)

#ifndef PROGDESC_T_H
#define PROGDESC_T_H

typedef struct {
    char Name[24];
    char Ver[99];
    char Date[24];
} progdesc_t;

#endif // PROGDESC_T_H

// Auto-generated C struct for Fortran TYPE(DBEMT_InitOutputType)
// Generated by VIT (Verified Incremental Translator)

#ifndef DBEMT_INITOUTPUTTYPE_T_H
#define DBEMT_INITOUTPUTTYPE_T_H

typedef struct {
    progdesc_t Ver;
} dbemt_initoutputtype_t;

#endif // DBEMT_INITOUTPUTTYPE_T_H

#endif // VIT_TYPES_H
