// Shared header for VIT-translated function entry points.
// Auto-generated by `vit integrate --apply`. Do not edit manually.
//
// C++ translations #include this header to call other translated
// functions directly via their _c entry points, bypassing the
// Fortran wrapper layer.

#ifndef VIT_TRANSLATED_H
#define VIT_TRANSLATED_H

#include "vit_types.h"

#ifdef __cplusplus
extern "C" {
#endif

void calculate_cn_c(double* alpha, int n_alpha, double* Cl, int n_Cl, double* Cd, int n_Cd, double Cd0, double* Calculate_Cn_result);
void findboundingtables_c(afi_parametertype_view_t* p, double secondaryDepVal, int* lowerTable, int* upperTable, double* xVals);
void compute_iloweriupper_c(afi_table_type_view_t* p, int* iLower, int* iUpper);
double computeua360_cnoffset_c(afi_table_type_view_t* p, double* cn_cl, int n_cn_cl, int Row, int iLower);
void calculate_c_alpha_c(double* alpha, int n_alpha, double* Cn, int n_Cn, double* Cl, int n_Cl, double* Default_Cn_alpha, double* Default_Cl_alpha, double* Default_alpha0, int* ErrStat, char* ErrMsg);
void computeuaseparationfunction_zero_c(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl);
void computeua360_updatecnseparated_c(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl, int iLower);
void computeua360_updateseparationf_c(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl, int iLower, int iUpper);
void computeuaseparationfunction_oncl_c(afi_table_type_view_t* p, int ColCl, int ColUAf, int col_fs, int col_fa);
void computeua360_attachedflow_c(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl, int* iLower, int* iUpper);
void calculateuacoeffs_c(afi_ua_bl_default_type_t* CalcDefaults, afi_table_type_view_t* p, int ColCl, int ColCd, int ColCm, int ColUAf, int UAMod);
void afi_validateinitinput_c(afi_initinputtype_t* InitInput, int* ErrStat, char* ErrMsg);
void afi_computeairfoilcoefs_c(double AOA, double Re, double UserProp, afi_parametertype_view_t* p, afi_outputtype_t* AFI_interp, int* errStat, char* errMsg);
void afi_computeuacoefs_c(afi_parametertype_view_t* p, double Re, double UserProp, afi_ua_bl_type_t* UA_BL, char* errMsg, int* errStat);
void readaffile_pass1_c(const afi_initinputtype_t* InitInp, int NumCoefsIn, afi_parametertype_view_t* p, int* numalf_out, int* ncoefstab_out, int* errStat, char* errMsg);
void readaffile_fill_c(afi_parametertype_view_t* p, const afi_initinputtype_t* InitInp, int NumCoefsIn, int* errStat, char* errMsg);
void afi_init_pass1_c(const afi_initinputtype_t* InitInput, afi_parametertype_view_t* p, int* n_secondVals_out, double* secondVals_buf, int* spline_dim1_out, int* spline_dim2_out, int* errStat, char* errMsg);
void afi_init_pass2_c(afi_parametertype_view_t* p, const double* secondVals_buf, int n_secondVals, int* errStat, char* errMsg);
void afi_wrheader_c(const char* delim, const char* filename, int* errStat, char* errMsg);
void afi_wrdata_c(int k, const char* filename, const char* delim, afi_parametertype_view_t* p);
void afi_wrtables_c(afi_parametertype_view_t* p, int UAMod, const char* OutRootName);
void computetau2_c(int i, int j, dbemt_elementinputtype_t* u, dbemt_parametertype_view_t* p, double tau1, double* tau2, int has_k_tau_out, double* k_tau_out);
void computetau1_c(dbemt_inputtype_view_t* u, dbemt_parametertype_view_t* p, dbemt_miscvartype_t* m, double* tau1, int* errStat, char* errMsg);
void dbemt_initstates_c(int i, int j, dbemt_inputtype_view_t* u, dbemt_parametertype_view_t* p, dbemt_continuousstatetype_view_t* x, dbemt_otherstatetype_view_t* OtherState);
void dbemt_calcoutput_c(int i, int j, double t, dbemt_inputtype_view_t* u, double* y_vind, dbemt_parametertype_view_t* p, dbemt_continuousstatetype_view_t* x, dbemt_otherstatetype_view_t* OtherState, dbemt_miscvartype_t* m, int* errStat, char* errMsg);

#ifdef __cplusplus
}
#endif

#endif // VIT_TRANSLATED_H
