! Auto-generated by VIT (Verified Incremental Translator)
! View populator for TYPE(DBEMT_ContinuousStateType)
! DO NOT EDIT — regenerate with: vit analyze-types --scan-allocatable --type DBEMT_ContinuousStateType

MODULE vit_dbemt_continuousstatetype_view
    USE ISO_C_BINDING
    USE DBEMT_Types, ONLY: DBEMT_ContinuousStateType
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: dbemt_continuousstatetype_view_t, vit_populate_dbemt_continuousstatetype, vit_copy_scalars_to_dbemt_continuousstatetype, vit_original_dbemt_continuousstatetype

    ! Kernel stash: pointer to original Fortran type, set by wrapper before calling C++.
    ! Callee bridges USE this to pass the original type to Fortran callees.
    TYPE(DBEMT_ContinuousStateType), POINTER, SAVE :: vit_original_dbemt_continuousstatetype => NULL()

    ! Mirror of the C view struct — layout MUST match dbemt_continuousstatetype_view_t in C header
    TYPE, BIND(C) :: dbemt_continuousstatetype_view_t
        ! ALLOCATABLE fields (pointer + size)
        TYPE(C_PTR) :: element = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_element_rows = 0
        INTEGER(C_INT32_T) :: n_element_cols = 0
    END TYPE dbemt_continuousstatetype_view_t

CONTAINS

    SUBROUTINE vit_populate_dbemt_continuousstatetype(src, view)
        TYPE(DBEMT_ContinuousStateType), INTENT(IN), TARGET :: src
        TYPE(dbemt_continuousstatetype_view_t), INTENT(OUT) :: view

        ! --- Scalars ---

        ! --- ALLOCATABLE arrays ---
        IF (ALLOCATED(src%element)) THEN
            view%element = C_LOC(src%element(LBOUND(src%element,1),LBOUND(src%element,2)))
            view%n_element_rows = INT(SIZE(src%element, 1), C_INT32_T)
            view%n_element_cols = INT(SIZE(src%element, 2), C_INT32_T)
        ELSE
            view%element = C_NULL_PTR
            view%n_element_rows = 0
            view%n_element_cols = 0
        END IF

    END SUBROUTINE vit_populate_dbemt_continuousstatetype

    SUBROUTINE vit_copy_scalars_to_dbemt_continuousstatetype(view, dest)
        TYPE(dbemt_continuousstatetype_view_t), INTENT(IN) :: view
        TYPE(DBEMT_ContinuousStateType), INTENT(INOUT) :: dest

        ! --- Scalars (reverse of populator) ---

    END SUBROUTINE vit_copy_scalars_to_dbemt_continuousstatetype

END MODULE vit_dbemt_continuousstatetype_view
