! Auto-generated by VIT (Verified Incremental Translator)
! View populator for TYPE(AFI_PARAMETERTYPE)
! DO NOT EDIT — regenerate with: vit analyze-types --scan-allocatable --type AFI_PARAMETERTYPE

MODULE vit_afi_parametertype_view
    USE ISO_C_BINDING
    USE AirfoilInfo_Types, ONLY: AFI_PARAMETERTYPE
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: afi_parametertype_view_t, vit_populate_afi_parametertype, vit_copy_scalars_to_afi_parametertype, vit_original_afi_parametertype

    ! Kernel stash: pointer to original Fortran type, set by wrapper before calling C++.
    ! Callee bridges USE this to pass the original type to Fortran callees.
    TYPE(AFI_PARAMETERTYPE), POINTER, SAVE :: vit_original_afi_parametertype => NULL()

    ! Mirror of the C view struct — layout MUST match afi_parametertype_view_t in C header
    TYPE, BIND(C) :: afi_parametertype_view_t
        INTEGER(C_INT) :: ColCd = 0
        INTEGER(C_INT) :: ColCl = 0
        INTEGER(C_INT) :: ColCm = 0
        INTEGER(C_INT) :: ColCpmin = 0
        INTEGER(C_INT) :: ColUAf = 0
        INTEGER(C_INT) :: AFTabMod = 0
        INTEGER(C_INT) :: InterpOrd = 0
        REAL(C_DOUBLE) :: RelThickness = 0
        REAL(C_DOUBLE) :: NonDimArea = 0
        INTEGER(C_INT) :: NumCoords = 0
        INTEGER(C_INT) :: NumTabs = 0
        CHARACTER(KIND=C_CHAR) :: BL_file(1024)
        CHARACTER(KIND=C_CHAR) :: FileName(1024)
        ! ALLOCATABLE fields (pointer + size)
        TYPE(C_PTR) :: secondVals = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_secondVals = 0
        TYPE(C_PTR) :: X_Coord = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_X_Coord = 0
        TYPE(C_PTR) :: Y_Coord = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_Y_Coord = 0
        TYPE(C_PTR) :: Table = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_Table = 0
    END TYPE afi_parametertype_view_t

CONTAINS

    SUBROUTINE vit_populate_afi_parametertype(src, view)
        TYPE(AFI_PARAMETERTYPE), INTENT(IN), TARGET :: src
        TYPE(afi_parametertype_view_t), INTENT(OUT) :: view

        ! --- Scalars ---
        view%ColCd = INT(src%ColCd, C_INT)
        view%ColCl = INT(src%ColCl, C_INT)
        view%ColCm = INT(src%ColCm, C_INT)
        view%ColCpmin = INT(src%ColCpmin, C_INT)
        view%ColUAf = INT(src%ColUAf, C_INT)
        view%AFTabMod = INT(src%AFTabMod, C_INT)
        view%InterpOrd = INT(src%InterpOrd, C_INT)
        view%RelThickness = REAL(src%RelThickness, C_DOUBLE)
        view%NonDimArea = REAL(src%NonDimArea, C_DOUBLE)
        view%NumCoords = INT(src%NumCoords, C_INT)
        view%NumTabs = INT(src%NumTabs, C_INT)
        view%BL_file = TRANSFER(src%BL_file, view%BL_file)
        view%FileName = TRANSFER(src%FileName, view%FileName)

        ! --- ALLOCATABLE arrays ---
        IF (ALLOCATED(src%secondVals)) THEN
            view%secondVals = C_LOC(src%secondVals(1))
            view%n_secondVals = INT(SIZE(src%secondVals), C_INT32_T)
        ELSE
            view%secondVals = C_NULL_PTR
            view%n_secondVals = 0
        END IF
        IF (ALLOCATED(src%X_Coord)) THEN
            view%X_Coord = C_LOC(src%X_Coord(1))
            view%n_X_Coord = INT(SIZE(src%X_Coord), C_INT32_T)
        ELSE
            view%X_Coord = C_NULL_PTR
            view%n_X_Coord = 0
        END IF
        IF (ALLOCATED(src%Y_Coord)) THEN
            view%Y_Coord = C_LOC(src%Y_Coord(1))
            view%n_Y_Coord = INT(SIZE(src%Y_Coord), C_INT32_T)
        ELSE
            view%Y_Coord = C_NULL_PTR
            view%n_Y_Coord = 0
        END IF
        IF (ALLOCATED(src%Table)) THEN
            view%Table = C_NULL_PTR  ! TYPE() — opaque, not interoperable
            view%n_Table = INT(SIZE(src%Table), C_INT32_T)
        ELSE
            view%Table = C_NULL_PTR
            view%n_Table = 0
        END IF

    END SUBROUTINE vit_populate_afi_parametertype

    SUBROUTINE vit_copy_scalars_to_afi_parametertype(view, dest)
        TYPE(afi_parametertype_view_t), INTENT(IN) :: view
        TYPE(AFI_PARAMETERTYPE), INTENT(INOUT) :: dest
        INTEGER :: i

        ! --- Scalars (reverse of populator) ---
        dest%ColCd = INT(view%ColCd, C_INT)
        dest%ColCl = INT(view%ColCl, C_INT)
        dest%ColCm = INT(view%ColCm, C_INT)
        dest%ColCpmin = INT(view%ColCpmin, C_INT)
        dest%ColUAf = INT(view%ColUAf, C_INT)
        dest%AFTabMod = INT(view%AFTabMod, C_INT)
        dest%InterpOrd = INT(view%InterpOrd, C_INT)
        dest%RelThickness = REAL(view%RelThickness, C_DOUBLE)
        dest%NonDimArea = REAL(view%NonDimArea, C_DOUBLE)
        dest%NumCoords = INT(view%NumCoords, C_INT)
        dest%NumTabs = INT(view%NumTabs, C_INT)
        DO i = 1, 1024
            dest%BL_file(i:i) = view%BL_file(i)
        END DO
        DO i = 1, 1024
            dest%FileName(i:i) = view%FileName(i)
        END DO

    END SUBROUTINE vit_copy_scalars_to_afi_parametertype

END MODULE vit_afi_parametertype_view
