! Auto-generated by VIT (Verified Incremental Translator)
! View populator for TYPE(DBEMT_ParameterType)
! DO NOT EDIT — regenerate with: vit analyze-types --scan-allocatable --type DBEMT_ParameterType

MODULE vit_dbemt_parametertype_view
    USE ISO_C_BINDING
    USE DBEMT_Types, ONLY: DBEMT_ParameterType
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: dbemt_parametertype_view_t, vit_populate_dbemt_parametertype, vit_copy_scalars_to_dbemt_parametertype, vit_original_dbemt_parametertype

    ! Kernel stash: pointer to original Fortran type, set by wrapper before calling C++.
    ! Callee bridges USE this to pass the original type to Fortran callees.
    TYPE(DBEMT_ParameterType), POINTER, SAVE :: vit_original_dbemt_parametertype => NULL()

    ! Mirror of the C view struct — layout MUST match dbemt_parametertype_view_t in C header
    TYPE, BIND(C) :: dbemt_parametertype_view_t
        REAL(C_DOUBLE) :: DT = 0
        INTEGER(C_INT) :: lin_nx = 0
        INTEGER(C_INT) :: NumBlades = 0
        INTEGER(C_INT) :: NumNodes = 0
        REAL(C_DOUBLE) :: k_0ye = 0
        REAL(C_DOUBLE) :: tau1_const = 0
        INTEGER(C_INT) :: DBEMT_Mod = 0
        ! ALLOCATABLE fields (pointer + size)
        TYPE(C_PTR) :: spanRatio = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_spanRatio_rows = 0
        INTEGER(C_INT32_T) :: n_spanRatio_cols = 0
    END TYPE dbemt_parametertype_view_t

CONTAINS

    SUBROUTINE vit_populate_dbemt_parametertype(src, view)
        TYPE(DBEMT_ParameterType), INTENT(IN), TARGET :: src
        TYPE(dbemt_parametertype_view_t), INTENT(OUT) :: view

        ! --- Scalars ---
        view%DT = REAL(src%DT, C_DOUBLE)
        view%lin_nx = INT(src%lin_nx, C_INT)
        view%NumBlades = INT(src%NumBlades, C_INT)
        view%NumNodes = INT(src%NumNodes, C_INT)
        view%k_0ye = REAL(src%k_0ye, C_DOUBLE)
        view%tau1_const = REAL(src%tau1_const, C_DOUBLE)
        view%DBEMT_Mod = INT(src%DBEMT_Mod, C_INT)

        ! --- ALLOCATABLE arrays ---
        IF (ALLOCATED(src%spanRatio)) THEN
            view%spanRatio = C_LOC(src%spanRatio(LBOUND(src%spanRatio,1),LBOUND(src%spanRatio,2)))
            view%n_spanRatio_rows = INT(SIZE(src%spanRatio, 1), C_INT32_T)
            view%n_spanRatio_cols = INT(SIZE(src%spanRatio, 2), C_INT32_T)
        ELSE
            view%spanRatio = C_NULL_PTR
            view%n_spanRatio_rows = 0
            view%n_spanRatio_cols = 0
        END IF

    END SUBROUTINE vit_populate_dbemt_parametertype

    SUBROUTINE vit_copy_scalars_to_dbemt_parametertype(view, dest)
        TYPE(dbemt_parametertype_view_t), INTENT(IN) :: view
        TYPE(DBEMT_ParameterType), INTENT(INOUT) :: dest

        ! --- Scalars (reverse of populator) ---
        dest%DT = REAL(view%DT, C_DOUBLE)
        dest%lin_nx = INT(view%lin_nx, C_INT)
        dest%NumBlades = INT(view%NumBlades, C_INT)
        dest%NumNodes = INT(view%NumNodes, C_INT)
        dest%k_0ye = REAL(view%k_0ye, C_DOUBLE)
        dest%tau1_const = REAL(view%tau1_const, C_DOUBLE)
        dest%DBEMT_Mod = INT(view%DBEMT_Mod, C_INT)

    END SUBROUTINE vit_copy_scalars_to_dbemt_parametertype

END MODULE vit_dbemt_parametertype_view
