! Auto-generated by VIT (Verified Incremental Translator)
! View populator for TYPE(DBEMT_OTHERSTATETYPE)
! DO NOT EDIT — regenerate with: vit analyze-types --scan-allocatable --type DBEMT_OTHERSTATETYPE

MODULE vit_dbemt_otherstatetype_view
    USE ISO_C_BINDING
    USE DBEMT_Types, ONLY: DBEMT_OTHERSTATETYPE
    USE vit_dbemt_continuousstatetype_view, ONLY: dbemt_continuousstatetype_view_t, vit_populate_dbemt_continuousstatetype, vit_copy_scalars_to_dbemt_continuousstatetype
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: dbemt_otherstatetype_view_t, vit_populate_dbemt_otherstatetype, vit_copy_scalars_to_dbemt_otherstatetype, vit_original_dbemt_otherstatetype

    ! Kernel stash: pointer to original Fortran type, set by wrapper before calling C++.
    ! Callee bridges USE this to pass the original type to Fortran callees.
    TYPE(DBEMT_OTHERSTATETYPE), POINTER, SAVE :: vit_original_dbemt_otherstatetype => NULL()

    ! Mirror of the C view struct — layout MUST match dbemt_otherstatetype_view_t in C header
    TYPE, BIND(C) :: dbemt_otherstatetype_view_t
        REAL(C_DOUBLE) :: tau1 = 0
        REAL(C_DOUBLE) :: tau2 = 0
        TYPE(dbemt_continuousstatetype_view_t) :: xdot(4)
        ! ALLOCATABLE fields (pointer + size)
        TYPE(C_PTR) :: areStatesInitialized = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_areStatesInitialized_rows = 0
        INTEGER(C_INT32_T) :: n_areStatesInitialized_cols = 0
        TYPE(C_PTR) :: n = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_n_rows = 0
        INTEGER(C_INT32_T) :: n_n_cols = 0
    END TYPE dbemt_otherstatetype_view_t

CONTAINS

    SUBROUTINE vit_populate_dbemt_otherstatetype(src, view)
        TYPE(DBEMT_OTHERSTATETYPE), INTENT(IN), TARGET :: src
        TYPE(dbemt_otherstatetype_view_t), INTENT(OUT) :: view
        INTEGER :: vit_k

        ! --- Scalars ---
        view%tau1 = REAL(src%tau1, C_DOUBLE)
        view%tau2 = REAL(src%tau2, C_DOUBLE)

        ! --- Fixed-size TYPE() view arrays ---
        DO vit_k = 1, 4
            CALL vit_populate_dbemt_continuousstatetype(src%xdot(vit_k), view%xdot(vit_k))
        END DO

        ! --- ALLOCATABLE arrays ---
        IF (ALLOCATED(src%areStatesInitialized)) THEN
            view%areStatesInitialized = C_LOC(src%areStatesInitialized(LBOUND(src%areStatesInitialized,1),LBOUND(src%areStatesInitialized,2)))
            view%n_areStatesInitialized_rows = INT(SIZE(src%areStatesInitialized, 1), C_INT32_T)
            view%n_areStatesInitialized_cols = INT(SIZE(src%areStatesInitialized, 2), C_INT32_T)
        ELSE
            view%areStatesInitialized = C_NULL_PTR
            view%n_areStatesInitialized_rows = 0
            view%n_areStatesInitialized_cols = 0
        END IF
        IF (ALLOCATED(src%n)) THEN
            view%n = C_LOC(src%n(LBOUND(src%n,1),LBOUND(src%n,2)))
            view%n_n_rows = INT(SIZE(src%n, 1), C_INT32_T)
            view%n_n_cols = INT(SIZE(src%n, 2), C_INT32_T)
        ELSE
            view%n = C_NULL_PTR
            view%n_n_rows = 0
            view%n_n_cols = 0
        END IF

    END SUBROUTINE vit_populate_dbemt_otherstatetype

    SUBROUTINE vit_copy_scalars_to_dbemt_otherstatetype(view, dest)
        TYPE(dbemt_otherstatetype_view_t), INTENT(IN) :: view
        TYPE(DBEMT_OTHERSTATETYPE), INTENT(INOUT) :: dest
        INTEGER :: vit_k

        ! --- Scalars (reverse of populator) ---
        dest%tau1 = REAL(view%tau1, C_DOUBLE)
        dest%tau2 = REAL(view%tau2, C_DOUBLE)
        DO vit_k = 1, 4
            CALL vit_copy_scalars_to_dbemt_continuousstatetype(view%xdot(vit_k), dest%xdot(vit_k))
        END DO

    END SUBROUTINE vit_copy_scalars_to_dbemt_otherstatetype

END MODULE vit_dbemt_otherstatetype_view
