! Auto-generated by VIT (Verified Incremental Translator)
! View populator for TYPE(DBEMT_InitInputType)
! DO NOT EDIT — regenerate with: vit analyze-types --scan-allocatable --type DBEMT_InitInputType

MODULE vit_dbemt_initinputtype_view
    USE ISO_C_BINDING
    USE DBEMT_Types, ONLY: DBEMT_InitInputType
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: dbemt_initinputtype_view_t, vit_populate_dbemt_initinputtype, vit_copy_scalars_to_dbemt_initinputtype, vit_original_dbemt_initinputtype

    ! Kernel stash: pointer to original Fortran type, set by wrapper before calling C++.
    ! Callee bridges USE this to pass the original type to Fortran callees.
    TYPE(DBEMT_InitInputType), POINTER, SAVE :: vit_original_dbemt_initinputtype => NULL()

    ! Mirror of the C view struct — layout MUST match dbemt_initinputtype_view_t in C header
    TYPE, BIND(C) :: dbemt_initinputtype_view_t
        INTEGER(C_INT) :: NumBlades = 0
        INTEGER(C_INT) :: NumNodes = 0
        REAL(C_DOUBLE) :: tau1_const = 0
        INTEGER(C_INT) :: DBEMT_Mod = 0
        ! ALLOCATABLE fields (pointer + size)
        TYPE(C_PTR) :: rLocal = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_rLocal_rows = 0
        INTEGER(C_INT32_T) :: n_rLocal_cols = 0
    END TYPE dbemt_initinputtype_view_t

CONTAINS

    SUBROUTINE vit_populate_dbemt_initinputtype(src, view)
        TYPE(DBEMT_InitInputType), INTENT(IN), TARGET :: src
        TYPE(dbemt_initinputtype_view_t), INTENT(OUT) :: view

        ! --- Scalars ---
        view%NumBlades = INT(src%NumBlades, C_INT)
        view%NumNodes = INT(src%NumNodes, C_INT)
        view%tau1_const = REAL(src%tau1_const, C_DOUBLE)
        view%DBEMT_Mod = INT(src%DBEMT_Mod, C_INT)

        ! --- ALLOCATABLE arrays ---
        IF (ALLOCATED(src%rLocal)) THEN
            view%rLocal = C_LOC(src%rLocal(LBOUND(src%rLocal,1),LBOUND(src%rLocal,2)))
            view%n_rLocal_rows = INT(SIZE(src%rLocal, 1), C_INT32_T)
            view%n_rLocal_cols = INT(SIZE(src%rLocal, 2), C_INT32_T)
        ELSE
            view%rLocal = C_NULL_PTR
            view%n_rLocal_rows = 0
            view%n_rLocal_cols = 0
        END IF

    END SUBROUTINE vit_populate_dbemt_initinputtype

    SUBROUTINE vit_copy_scalars_to_dbemt_initinputtype(view, dest)
        TYPE(dbemt_initinputtype_view_t), INTENT(IN) :: view
        TYPE(DBEMT_InitInputType), INTENT(INOUT) :: dest

        ! --- Scalars (reverse of populator) ---
        dest%NumBlades = INT(view%NumBlades, C_INT)
        dest%NumNodes = INT(view%NumNodes, C_INT)
        dest%tau1_const = REAL(view%tau1_const, C_DOUBLE)
        dest%DBEMT_Mod = INT(view%DBEMT_Mod, C_INT)

    END SUBROUTINE vit_copy_scalars_to_dbemt_initinputtype

END MODULE vit_dbemt_initinputtype_view
