// Auto-generated C wrapper for Fortran function: Compute_iLoweriUpper
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

// User-provided C++ implementation
#include "compute_iloweriupper.hpp"

extern "C" {
    void compute_iloweriupper_c(afi_table_type_view_t* p, int* iLower, int* iUpper) {
        Compute_iLoweriUpper(p, iLower, iUpper);
    }
}
