// Auto-generated C wrapper for Fortran function: FindBoundingTables
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

// User-provided C++ implementation
#include "findboundingtables.hpp"

extern "C" {
    void findboundingtables_c(afi_parametertype_view_t* p, double secondaryDepVal, int* lowerTable, int* upperTable, double* xVals) {
        FindBoundingTables(p, secondaryDepVal, lowerTable, upperTable, xVals);
    }
}
