// Auto-generated C wrapper for Fortran function: Calculate_C_alpha
// Generated by VIT (Verified Incremental Translator)

// User-provided C++ implementation
#include "calculate_c_alpha.hpp"

extern "C" {
    void calculate_c_alpha_c(double* alpha, int n_alpha, double* Cn, int n_Cn, double* Cl, int n_Cl, double* Default_Cn_alpha, double* Default_Cl_alpha, double* Default_alpha0, int* ErrStat, char* ErrMsg) {
        Calculate_C_alpha(alpha, n_alpha, Cn, n_Cn, Cl, n_Cl, Default_Cn_alpha, Default_Cl_alpha, Default_alpha0, ErrStat, ErrMsg);
    }
}
