// Auto-generated C wrapper for Fortran function: ComputeUASeparationFunction_onCl
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

#include "vit_kernel_callees.h"

// User-provided C++ implementation
#include "computeuaseparationfunction_oncl.hpp"

extern "C" {
    void computeuaseparationfunction_oncl_c(afi_table_type_view_t* p, int ColCl, int ColUAf, int col_fs, int col_fa) {
        ComputeUASeparationFunction_onCl(p, ColCl, ColUAf, col_fs, col_fa);
    }
}
