! Auto-generated by VIT (Verified Incremental Translator)
! View populator for TYPE(AFI_Table_Type)
! DO NOT EDIT — regenerate with: vit analyze-types --scan-allocatable --type AFI_Table_Type

MODULE vit_afi_table_type_view
    USE ISO_C_BINDING
    USE AirfoilInfo_Types, ONLY: AFI_Table_Type
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: afi_table_type_view_t, vit_populate_afi_table_type, vit_copy_scalars_to_afi_table_type, vit_original_afi_table_type

    ! Kernel stash: pointer to original Fortran type, set by wrapper before calling C++.
    ! Callee bridges USE this to pass the original type to Fortran callees.
    TYPE(AFI_Table_Type), POINTER, SAVE :: vit_original_afi_table_type => NULL()

    ! Nested BIND(C) mirror for TYPE(AFI_UA_BL_Type)
    TYPE, BIND(C) :: afi_ua_bl_type_view_t
        REAL(C_DOUBLE) :: alpha0 = 0
        REAL(C_DOUBLE) :: alpha1 = 0
        REAL(C_DOUBLE) :: alpha2 = 0
        REAL(C_DOUBLE) :: eta_e = 0
        REAL(C_DOUBLE) :: C_nalpha = 0
        REAL(C_DOUBLE) :: C_lalpha = 0
        REAL(C_DOUBLE) :: T_f0 = 0
        REAL(C_DOUBLE) :: T_V0 = 0
        REAL(C_DOUBLE) :: T_p = 0
        REAL(C_DOUBLE) :: T_VL = 0
        REAL(C_DOUBLE) :: b1 = 0
        REAL(C_DOUBLE) :: b2 = 0
        REAL(C_DOUBLE) :: b5 = 0
        REAL(C_DOUBLE) :: A1 = 0
        REAL(C_DOUBLE) :: A2 = 0
        REAL(C_DOUBLE) :: A5 = 0
        REAL(C_DOUBLE) :: S1 = 0
        REAL(C_DOUBLE) :: S2 = 0
        REAL(C_DOUBLE) :: S3 = 0
        REAL(C_DOUBLE) :: S4 = 0
        REAL(C_DOUBLE) :: Cn1 = 0
        REAL(C_DOUBLE) :: Cn2 = 0
        REAL(C_DOUBLE) :: St_sh = 0
        REAL(C_DOUBLE) :: Cd0 = 0
        REAL(C_DOUBLE) :: Cm0 = 0
        REAL(C_DOUBLE) :: k0 = 0
        REAL(C_DOUBLE) :: k1 = 0
        REAL(C_DOUBLE) :: k2 = 0
        REAL(C_DOUBLE) :: k3 = 0
        REAL(C_DOUBLE) :: k1_hat = 0
        REAL(C_DOUBLE) :: x_cp_bar = 0
        REAL(C_DOUBLE) :: UACutout = 0
        REAL(C_DOUBLE) :: UACutout_delta = 0
        REAL(C_DOUBLE) :: UACutout_blend = 0
        REAL(C_DOUBLE) :: filtCutOff = 0
        REAL(C_DOUBLE) :: alphaUpper = 0
        REAL(C_DOUBLE) :: alphaLower = 0
        REAL(C_DOUBLE) :: c_alphaLower = 0
        REAL(C_DOUBLE) :: c_alphaUpper = 0
        REAL(C_DOUBLE) :: alpha0ReverseFlow = 0
        REAL(C_DOUBLE) :: alphaBreakUpper = 0
        REAL(C_DOUBLE) :: CnBreakUpper = 0
        REAL(C_DOUBLE) :: alphaBreakLower = 0
        REAL(C_DOUBLE) :: CnBreakLower = 0
    END TYPE afi_ua_bl_type_view_t

    ! Mirror of the C view struct — layout MUST match afi_table_type_view_t in C header
    TYPE, BIND(C) :: afi_table_type_view_t
        REAL(C_DOUBLE) :: UserProp = 0
        REAL(C_DOUBLE) :: Re = 0
        INTEGER(C_INT) :: NumAlf = 0
        LOGICAL(C_BOOL) :: ConstData = .FALSE.
        LOGICAL(C_BOOL) :: InclUAdata = .FALSE.
        TYPE(afi_ua_bl_type_view_t) :: UA_BL
        ! ALLOCATABLE fields (pointer + size)
        TYPE(C_PTR) :: Alpha = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_Alpha = 0
        TYPE(C_PTR) :: Coefs = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_Coefs_rows = 0
        INTEGER(C_INT32_T) :: n_Coefs_cols = 0
        TYPE(C_PTR) :: SplineCoefs = C_NULL_PTR
        INTEGER(C_INT32_T) :: n_SplineCoefs_dim1 = 0
        INTEGER(C_INT32_T) :: n_SplineCoefs_dim2 = 0
        INTEGER(C_INT32_T) :: n_SplineCoefs_dim3 = 0
    END TYPE afi_table_type_view_t

CONTAINS

    SUBROUTINE vit_populate_afi_table_type(src, view)
        TYPE(AFI_Table_Type), INTENT(IN), TARGET :: src
        TYPE(afi_table_type_view_t), INTENT(OUT) :: view

        ! --- Scalars ---
        view%UserProp = REAL(src%UserProp, C_DOUBLE)
        view%Re = REAL(src%Re, C_DOUBLE)
        view%NumAlf = INT(src%NumAlf, C_INT)
        view%ConstData = LOGICAL(src%ConstData, C_BOOL)
        view%InclUAdata = LOGICAL(src%InclUAdata, C_BOOL)
        ! --- Nested TYPE(AFI_UA_BL_Type) UA_BL ---
        view%UA_BL%alpha0 = REAL(src%UA_BL%alpha0, C_DOUBLE)
        view%UA_BL%alpha1 = REAL(src%UA_BL%alpha1, C_DOUBLE)
        view%UA_BL%alpha2 = REAL(src%UA_BL%alpha2, C_DOUBLE)
        view%UA_BL%eta_e = REAL(src%UA_BL%eta_e, C_DOUBLE)
        view%UA_BL%C_nalpha = REAL(src%UA_BL%C_nalpha, C_DOUBLE)
        view%UA_BL%C_lalpha = REAL(src%UA_BL%C_lalpha, C_DOUBLE)
        view%UA_BL%T_f0 = REAL(src%UA_BL%T_f0, C_DOUBLE)
        view%UA_BL%T_V0 = REAL(src%UA_BL%T_V0, C_DOUBLE)
        view%UA_BL%T_p = REAL(src%UA_BL%T_p, C_DOUBLE)
        view%UA_BL%T_VL = REAL(src%UA_BL%T_VL, C_DOUBLE)
        view%UA_BL%b1 = REAL(src%UA_BL%b1, C_DOUBLE)
        view%UA_BL%b2 = REAL(src%UA_BL%b2, C_DOUBLE)
        view%UA_BL%b5 = REAL(src%UA_BL%b5, C_DOUBLE)
        view%UA_BL%A1 = REAL(src%UA_BL%A1, C_DOUBLE)
        view%UA_BL%A2 = REAL(src%UA_BL%A2, C_DOUBLE)
        view%UA_BL%A5 = REAL(src%UA_BL%A5, C_DOUBLE)
        view%UA_BL%S1 = REAL(src%UA_BL%S1, C_DOUBLE)
        view%UA_BL%S2 = REAL(src%UA_BL%S2, C_DOUBLE)
        view%UA_BL%S3 = REAL(src%UA_BL%S3, C_DOUBLE)
        view%UA_BL%S4 = REAL(src%UA_BL%S4, C_DOUBLE)
        view%UA_BL%Cn1 = REAL(src%UA_BL%Cn1, C_DOUBLE)
        view%UA_BL%Cn2 = REAL(src%UA_BL%Cn2, C_DOUBLE)
        view%UA_BL%St_sh = REAL(src%UA_BL%St_sh, C_DOUBLE)
        view%UA_BL%Cd0 = REAL(src%UA_BL%Cd0, C_DOUBLE)
        view%UA_BL%Cm0 = REAL(src%UA_BL%Cm0, C_DOUBLE)
        view%UA_BL%k0 = REAL(src%UA_BL%k0, C_DOUBLE)
        view%UA_BL%k1 = REAL(src%UA_BL%k1, C_DOUBLE)
        view%UA_BL%k2 = REAL(src%UA_BL%k2, C_DOUBLE)
        view%UA_BL%k3 = REAL(src%UA_BL%k3, C_DOUBLE)
        view%UA_BL%k1_hat = REAL(src%UA_BL%k1_hat, C_DOUBLE)
        view%UA_BL%x_cp_bar = REAL(src%UA_BL%x_cp_bar, C_DOUBLE)
        view%UA_BL%UACutout = REAL(src%UA_BL%UACutout, C_DOUBLE)
        view%UA_BL%UACutout_delta = REAL(src%UA_BL%UACutout_delta, C_DOUBLE)
        view%UA_BL%UACutout_blend = REAL(src%UA_BL%UACutout_blend, C_DOUBLE)
        view%UA_BL%filtCutOff = REAL(src%UA_BL%filtCutOff, C_DOUBLE)
        view%UA_BL%alphaUpper = REAL(src%UA_BL%alphaUpper, C_DOUBLE)
        view%UA_BL%alphaLower = REAL(src%UA_BL%alphaLower, C_DOUBLE)
        view%UA_BL%c_alphaLower = REAL(src%UA_BL%c_alphaLower, C_DOUBLE)
        view%UA_BL%c_alphaUpper = REAL(src%UA_BL%c_alphaUpper, C_DOUBLE)
        view%UA_BL%alpha0ReverseFlow = REAL(src%UA_BL%alpha0ReverseFlow, C_DOUBLE)
        view%UA_BL%alphaBreakUpper = REAL(src%UA_BL%alphaBreakUpper, C_DOUBLE)
        view%UA_BL%CnBreakUpper = REAL(src%UA_BL%CnBreakUpper, C_DOUBLE)
        view%UA_BL%alphaBreakLower = REAL(src%UA_BL%alphaBreakLower, C_DOUBLE)
        view%UA_BL%CnBreakLower = REAL(src%UA_BL%CnBreakLower, C_DOUBLE)

        ! --- ALLOCATABLE arrays ---
        IF (ALLOCATED(src%Alpha)) THEN
            view%Alpha = C_LOC(src%Alpha(1))
            view%n_Alpha = INT(SIZE(src%Alpha), C_INT32_T)
        ELSE
            view%Alpha = C_NULL_PTR
            view%n_Alpha = 0
        END IF
        IF (ALLOCATED(src%Coefs)) THEN
            view%Coefs = C_LOC(src%Coefs(1,1))
            view%n_Coefs_rows = INT(SIZE(src%Coefs, 1), C_INT32_T)
            view%n_Coefs_cols = INT(SIZE(src%Coefs, 2), C_INT32_T)
        ELSE
            view%Coefs = C_NULL_PTR
            view%n_Coefs_rows = 0
            view%n_Coefs_cols = 0
        END IF
        IF (ALLOCATED(src%SplineCoefs)) THEN
            view%SplineCoefs = C_LOC(src%SplineCoefs(1,1,1))
            view%n_SplineCoefs_dim1 = INT(SIZE(src%SplineCoefs, 1), C_INT32_T)
            view%n_SplineCoefs_dim2 = INT(SIZE(src%SplineCoefs, 2), C_INT32_T)
            view%n_SplineCoefs_dim3 = INT(SIZE(src%SplineCoefs, 3), C_INT32_T)
        ELSE
            view%SplineCoefs = C_NULL_PTR
            view%n_SplineCoefs_dim1 = 0
            view%n_SplineCoefs_dim2 = 0
            view%n_SplineCoefs_dim3 = 0
        END IF

    END SUBROUTINE vit_populate_afi_table_type

    SUBROUTINE vit_copy_scalars_to_afi_table_type(view, dest)
        TYPE(afi_table_type_view_t), INTENT(IN) :: view
        TYPE(AFI_Table_Type), INTENT(INOUT) :: dest

        ! --- Scalars (reverse of populator) ---
        dest%UserProp = REAL(view%UserProp, C_DOUBLE)
        dest%Re = REAL(view%Re, C_DOUBLE)
        dest%NumAlf = INT(view%NumAlf, C_INT)
        dest%ConstData = view%ConstData
        dest%InclUAdata = view%InclUAdata
        ! --- Nested TYPE(AFI_UA_BL_Type) UA_BL ---
        dest%UA_BL%alpha0 = REAL(view%UA_BL%alpha0, C_DOUBLE)
        dest%UA_BL%alpha1 = REAL(view%UA_BL%alpha1, C_DOUBLE)
        dest%UA_BL%alpha2 = REAL(view%UA_BL%alpha2, C_DOUBLE)
        dest%UA_BL%eta_e = REAL(view%UA_BL%eta_e, C_DOUBLE)
        dest%UA_BL%C_nalpha = REAL(view%UA_BL%C_nalpha, C_DOUBLE)
        dest%UA_BL%C_lalpha = REAL(view%UA_BL%C_lalpha, C_DOUBLE)
        dest%UA_BL%T_f0 = REAL(view%UA_BL%T_f0, C_DOUBLE)
        dest%UA_BL%T_V0 = REAL(view%UA_BL%T_V0, C_DOUBLE)
        dest%UA_BL%T_p = REAL(view%UA_BL%T_p, C_DOUBLE)
        dest%UA_BL%T_VL = REAL(view%UA_BL%T_VL, C_DOUBLE)
        dest%UA_BL%b1 = REAL(view%UA_BL%b1, C_DOUBLE)
        dest%UA_BL%b2 = REAL(view%UA_BL%b2, C_DOUBLE)
        dest%UA_BL%b5 = REAL(view%UA_BL%b5, C_DOUBLE)
        dest%UA_BL%A1 = REAL(view%UA_BL%A1, C_DOUBLE)
        dest%UA_BL%A2 = REAL(view%UA_BL%A2, C_DOUBLE)
        dest%UA_BL%A5 = REAL(view%UA_BL%A5, C_DOUBLE)
        dest%UA_BL%S1 = REAL(view%UA_BL%S1, C_DOUBLE)
        dest%UA_BL%S2 = REAL(view%UA_BL%S2, C_DOUBLE)
        dest%UA_BL%S3 = REAL(view%UA_BL%S3, C_DOUBLE)
        dest%UA_BL%S4 = REAL(view%UA_BL%S4, C_DOUBLE)
        dest%UA_BL%Cn1 = REAL(view%UA_BL%Cn1, C_DOUBLE)
        dest%UA_BL%Cn2 = REAL(view%UA_BL%Cn2, C_DOUBLE)
        dest%UA_BL%St_sh = REAL(view%UA_BL%St_sh, C_DOUBLE)
        dest%UA_BL%Cd0 = REAL(view%UA_BL%Cd0, C_DOUBLE)
        dest%UA_BL%Cm0 = REAL(view%UA_BL%Cm0, C_DOUBLE)
        dest%UA_BL%k0 = REAL(view%UA_BL%k0, C_DOUBLE)
        dest%UA_BL%k1 = REAL(view%UA_BL%k1, C_DOUBLE)
        dest%UA_BL%k2 = REAL(view%UA_BL%k2, C_DOUBLE)
        dest%UA_BL%k3 = REAL(view%UA_BL%k3, C_DOUBLE)
        dest%UA_BL%k1_hat = REAL(view%UA_BL%k1_hat, C_DOUBLE)
        dest%UA_BL%x_cp_bar = REAL(view%UA_BL%x_cp_bar, C_DOUBLE)
        dest%UA_BL%UACutout = REAL(view%UA_BL%UACutout, C_DOUBLE)
        dest%UA_BL%UACutout_delta = REAL(view%UA_BL%UACutout_delta, C_DOUBLE)
        dest%UA_BL%UACutout_blend = REAL(view%UA_BL%UACutout_blend, C_DOUBLE)
        dest%UA_BL%filtCutOff = REAL(view%UA_BL%filtCutOff, C_DOUBLE)
        dest%UA_BL%alphaUpper = REAL(view%UA_BL%alphaUpper, C_DOUBLE)
        dest%UA_BL%alphaLower = REAL(view%UA_BL%alphaLower, C_DOUBLE)
        dest%UA_BL%c_alphaLower = REAL(view%UA_BL%c_alphaLower, C_DOUBLE)
        dest%UA_BL%c_alphaUpper = REAL(view%UA_BL%c_alphaUpper, C_DOUBLE)
        dest%UA_BL%alpha0ReverseFlow = REAL(view%UA_BL%alpha0ReverseFlow, C_DOUBLE)
        dest%UA_BL%alphaBreakUpper = REAL(view%UA_BL%alphaBreakUpper, C_DOUBLE)
        dest%UA_BL%CnBreakUpper = REAL(view%UA_BL%CnBreakUpper, C_DOUBLE)
        dest%UA_BL%alphaBreakLower = REAL(view%UA_BL%alphaBreakLower, C_DOUBLE)
        dest%UA_BL%CnBreakLower = REAL(view%UA_BL%CnBreakLower, C_DOUBLE)

    END SUBROUTINE vit_copy_scalars_to_afi_table_type

END MODULE vit_afi_table_type_view
