// Auto-generated C wrapper for Fortran function: ComputeUA360_updateCnSeparated
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

#include "vit_kernel_callees.h"

// User-provided C++ implementation
#include "computeua360_updatecnseparated.hpp"

extern "C" {
    void computeua360_updatecnseparated_c(afi_table_type_view_t* p, int ColUAf, double* cn_cl, int n_cn_cl, int iLower) {
        ComputeUA360_updateCnSeparated(p, ColUAf, cn_cl, n_cn_cl, iLower);
    }
}
