// VIT Test-Validate Harness
// Function: DBEMT_ValidateInitInp
// Generated by: vit test-validate
//
// This file tests every error branch in the validation function.
// Each test constructs valid input, modifies one field to trigger
// the error condition, and asserts the function reports an error.

#include <cstdio>
#include <cstring>
#include <cstdlib>
#include "vit_types.h"
#include "vit_nwtc.h"
#include "vit_nwtc.cpp"
#include "vit_aerodyn_constants.h"

extern void DBEMT_ValidateInitInp(double interval, dbemt_initinputtype_view_t* InitInp, int* errStat, char* errMsg);

// --- Test infrastructure ---

struct TestResult {
    const char* name;
    bool passed;
    const char* detail;
};

// Fortran reference (via BIND(C) bridge — receives individual fields):
extern "C" void dbemt_validateinitinp_f90(
    double interval, int vit_InitInp_NumBlades, int vit_InitInp_NumNodes,
    double vit_InitInp_tau1_const, int vit_InitInp_DBEMT_Mod,
    double* vit_InitInp_rLocal_ptr, int vit_InitInp_rLocal_rows,
    int vit_InitInp_rLocal_cols, int* errStat);

struct DualResult {
    int err_cpp;
    int err_f90;
};

static DualResult run_both(double interval, dbemt_initinputtype_view_t* input) {
    DualResult r;
    char errMsg[ErrMsgLen];

    // C++ path
    std::memset(errMsg, ' ', ErrMsgLen);
    DBEMT_ValidateInitInp(interval, input, &r.err_cpp, errMsg);

    // Fortran path (pass individual fields)
    dbemt_validateinitinp_f90(interval, input->NumBlades, input->NumNodes,
        input->tau1_const, input->DBEMT_Mod, input->rLocal,
        input->n_rLocal_rows, input->n_rLocal_cols, &r.err_f90);

    return r;
}

// Valid input for DBEMT_Mod=2 (tauVaries) — skips the rLocal/tau1 block entirely
static double rlocal_data[6] = {1.0, 2.0, 3.0, 4.0, 5.0, 6.0};

static dbemt_initinputtype_view_t make_valid_input_mod2() {
    dbemt_initinputtype_view_t input;
    input.NumBlades = 2;
    input.NumNodes = 3;
    input.tau1_const = 0.33;
    input.DBEMT_Mod = DBEMT_tauVaries;  // 2
    input.rLocal = rlocal_data;
    input.n_rLocal_rows = 3;
    input.n_rLocal_cols = 2;
    return input;
}

// Valid input for DBEMT_Mod=1 (tauConst) — exercises the rLocal/tau1 block
static dbemt_initinputtype_view_t make_valid_input_mod1() {
    dbemt_initinputtype_view_t input;
    input.NumBlades = 2;
    input.NumNodes = 3;
    input.tau1_const = 0.33;
    input.DBEMT_Mod = DBEMT_tauConst;  // 1
    input.rLocal = rlocal_data;
    input.n_rLocal_rows = 3;
    input.n_rLocal_cols = 2;
    return input;
}

// --- Test functions ---

static TestResult test_happy_path_mod2() {
    auto input = make_valid_input_mod2();
    auto r = run_both(0.01, &input);
    if (r.err_cpp != r.err_f90)
        return {"happy_path_mod2", false, "C++ and Fortran disagree"};
    if (r.err_cpp != ErrID_None)
        return {"happy_path_mod2", false, "Expected ErrID_None"};
    return {"happy_path_mod2", true, nullptr};
}

static TestResult test_happy_path_mod1() {
    auto input = make_valid_input_mod1();
    auto r = run_both(0.01, &input);
    if (r.err_cpp != r.err_f90)
        return {"happy_path_mod1", false, "C++ and Fortran disagree"};
    if (r.err_cpp != ErrID_None)
        return {"happy_path_mod1", false, "Expected ErrID_None"};
    return {"happy_path_mod1", true, nullptr};
}

static TestResult test_interval_too_small() {
    auto input = make_valid_input_mod2();
    auto r = run_both(0.0, &input);
    if (r.err_cpp != r.err_f90)
        return {"interval_too_small", false, "C++ and Fortran disagree"};
    if (r.err_cpp != ErrID_Fatal)
        return {"interval_too_small", false, "Expected ErrID_Fatal"};
    return {"interval_too_small", true, nullptr};
}

static TestResult test_invalid_dbemt_mod() {
    auto input = make_valid_input_mod2();
    input.DBEMT_Mod = 4;
    auto r = run_both(0.01, &input);
    if (r.err_cpp != r.err_f90)
        return {"invalid_dbemt_mod", false, "C++ and Fortran disagree"};
    if (r.err_cpp != ErrID_Fatal)
        return {"invalid_dbemt_mod", false, "Expected ErrID_Fatal"};
    return {"invalid_dbemt_mod", true, nullptr};
}

static TestResult test_numblades_zero() {
    auto input = make_valid_input_mod2();
    input.NumBlades = 0;
    auto r = run_both(0.01, &input);
    if (r.err_cpp != r.err_f90)
        return {"numblades_zero", false, "C++ and Fortran disagree"};
    if (r.err_cpp != ErrID_Fatal)
        return {"numblades_zero", false, "Expected ErrID_Fatal"};
    return {"numblades_zero", true, nullptr};
}

static TestResult test_numnodes_one() {
    auto input = make_valid_input_mod2();
    input.NumNodes = 1;
    auto r = run_both(0.01, &input);
    if (r.err_cpp != r.err_f90)
        return {"numnodes_one", false, "C++ and Fortran disagree"};
    if (r.err_cpp != ErrID_Fatal)
        return {"numnodes_one", false, "Expected ErrID_Fatal"};
    return {"numnodes_one", true, nullptr};
}

static TestResult test_tau1_const_zero() {
    auto input = make_valid_input_mod1();
    input.tau1_const = 0.0;
    auto r = run_both(0.01, &input);
    if (r.err_cpp != r.err_f90)
        return {"tau1_const_zero", false, "C++ and Fortran disagree"};
    if (r.err_cpp != ErrID_Fatal)
        return {"tau1_const_zero", false, "Expected ErrID_Fatal"};
    return {"tau1_const_zero", true, nullptr};
}

static TestResult test_rlocal_not_allocated() {
    auto input = make_valid_input_mod1();
    input.rLocal = nullptr;
    input.n_rLocal_rows = 0;
    input.n_rLocal_cols = 0;
    auto r = run_both(0.01, &input);
    if (r.err_cpp != r.err_f90)
        return {"rlocal_not_allocated", false, "C++ and Fortran disagree"};
    if (r.err_cpp != ErrID_Fatal)
        return {"rlocal_not_allocated", false, "Expected ErrID_Fatal"};
    return {"rlocal_not_allocated", true, nullptr};
}

static TestResult test_rlocal_negative() {
    double bad_rlocal[6] = {1.0, 2.0, -1.0, 4.0, 5.0, 6.0};
    auto input = make_valid_input_mod1();
    input.rLocal = bad_rlocal;
    auto r = run_both(0.01, &input);
    if (r.err_cpp != r.err_f90)
        return {"rlocal_negative", false, "C++ and Fortran disagree"};
    if (r.err_cpp != ErrID_Fatal)
        return {"rlocal_negative", false, "Expected ErrID_Fatal"};
    return {"rlocal_negative", true, nullptr};
}

// --- Test runner ---

int main() {
    TestResult tests[] = {
        test_happy_path_mod2(),
        test_happy_path_mod1(),
        test_interval_too_small(),
        test_invalid_dbemt_mod(),
        test_numblades_zero(),
        test_numnodes_one(),
        test_tau1_const_zero(),
        test_rlocal_not_allocated(),
        test_rlocal_negative(),
    };

    int n = sizeof(tests) / sizeof(tests[0]);
    int passed = 0, failed = 0, skipped = 0;
    for (int i = 0; i < n; i++) {
        if (tests[i].detail && strstr(tests[i].detail, "SKIPPED")) {
            skipped++;
            printf("  SKIP %s\n", tests[i].name);
        } else if (tests[i].passed) {
            passed++;
            printf("  PASS %s\n", tests[i].name);
        } else {
            failed++;
            printf("  FAIL %s: %s\n", tests[i].name, tests[i].detail);
        }
    }
    printf("\n%d passed, %d failed, %d skipped\n", passed, failed, skipped);
    return failed > 0 ? 1 : 0;
}
