// C struct definitions for Fortran derived types.
// Auto-generated by VIT. Do not edit manually.

#ifndef VIT_TYPES_H
#define VIT_TYPES_H

#include <stdint.h>

// Auto-generated view struct for Fortran TYPE(DBEMT_INITINPUTTYPE)
// Generated by VIT (Verified Incremental Translator)
// ALLOCATABLE fields exposed as pointer+size pairs.
// Scalars and CHARACTER fields copied directly.
// 2D arrays use column-major layout: mat[col * n_rows + row]

#ifndef DBEMT_INITINPUTTYPE_VIEW_T_H
#define DBEMT_INITINPUTTYPE_VIEW_T_H

#include <stdint.h>

typedef struct {
    // --- Scalar and fixed-size fields ---
    int NumBlades;
    int NumNodes;
    double tau1_const;
    int DBEMT_Mod;

    // --- ALLOCATABLE fields (pointer + size) ---
    double* rLocal;  // column-major
    int32_t n_rLocal_rows;
    int32_t n_rLocal_cols;
} dbemt_initinputtype_view_t;

#endif // DBEMT_INITINPUTTYPE_VIEW_T_H

#endif // VIT_TYPES_H
