#include <fstream>
#include <set>

#include "registry.hpp"

// Known external module names — types from these modules are opaque (void*)
// because we don't generate C++ headers for them
static const std::set<std::string> external_modules = {
    "nwtc_library", "inflowwind", "seastate", "lindyn",
    "ifw_flowfield", "seast_wavefield", "gridinterp",
};

// Well-known character length parameters and their values.
// These are defined in Fortran source (NWTC_Base.f90) but not in Registry schema files.
static const std::map<std::string, int> char_len_defaults = {
    {"ChanLen", 20},
    {"LinChanLen", 200},
    {"MaxFileInfoLineLen", 512},
    {"NWTC_SizeOfNumWord", 20},
};

// Return C type string for a basic data type
static std::string cpp_type_str(const DataType &dt)
{
    switch (dt.tag)
    {
    case DataType::Tag::Integer:
        return "int32_t";
    case DataType::Tag::Logical:
        return "int32_t"; // Fortran LOGICAL is 4 bytes with gfortran
    case DataType::Tag::Real:
        switch (dt.basic.bit_size)
        {
        case 0:
            return "float"; // ReKi default
        case 32:
            return "float";
        case 64:
            return "double";
        }
        return "float";
    case DataType::Tag::Character:
        return "char";
    case DataType::Tag::Derived:
        return "void";
    }
    return "void";
}

// Check if a derived type field should be treated as opaque (void*)
static bool is_opaque_field(const Field &field)
{
    if (field.data_type->tag != DataType::Tag::Derived)
        return false;

    auto &ddt = field.data_type->derived;

    // POINTER fields (non-owning references) are always opaque
    if (field.is_pointer && !field.is_target)
        return true;

    // Built-in types with no module (MeshType, DLL_Type)
    if (ddt.module == nullptr)
        return true;

    // Types from external modules
    if (external_modules.count(tolower(ddt.module->name)) > 0)
        return true;

    return false;
}

// Resolve character string length to an integer.
// Returns the numeric value, or -1 if unresolvable.
static int resolve_string_len(const std::string &len_str)
{
    // If it's all digits, parse directly
    if (!len_str.empty() && std::all_of(len_str.begin(), len_str.end(), ::isdigit))
        return std::stoi(len_str);

    // Check known defaults
    auto it = char_len_defaults.find(len_str);
    if (it != char_len_defaults.end())
        return it->second;

    return -1;
}

// Compute total number of elements for a fixed-size array field.
// Returns the dimension expression strings for documentation.
static int compute_fixed_array_size(const Field &field, std::string &dims_comment)
{
    int total = 1;
    dims_comment = "";
    for (size_t i = 0; i < field.dims.size(); ++i)
    {
        auto &dim = field.dims[i];
        // For fixed dimensions, try to compute size
        // upper_bound and lower_bound are strings that may contain expressions
        int lb = 1, ub = 1;
        try
        {
            lb = std::stoi(dim.lower_bound);
            ub = std::stoi(dim.upper_bound);
        }
        catch (...)
        {
            // Non-numeric bounds (parameter names) — emit as expression
            dims_comment += (i > 0 ? " x " : "") + dim.upper_bound;
            total = -1; // can't compute
            continue;
        }
        int size = ub - lb + 1;
        if (total > 0)
            total *= size;
        dims_comment += (i > 0 ? " x " : "") + std::to_string(size);
    }
    return total;
}

void Registry::gen_cpp_module(const Module &mod, const std::string &out_dir)
{
    auto file_name = mod.name + "_Types.hpp";
    auto file_path = out_dir + "/" + file_name;
    std::string indent("\n");

    std::cerr << "generating " << file_name << std::endl;

    std::ofstream w(file_path);
    if (!w)
    {
        std::cerr << "Error creating module file: '" << file_path << "'" << std::endl;
        exit(EXIT_FAILURE);
    }

    //--------------------------------------------------------------------------
    // File header
    //--------------------------------------------------------------------------

    w << "// " << file_name << " -- Auto-generated by OpenFAST Registry. Do not edit.";
    w << indent << "#pragma once";
    w << indent;
    w << indent << "#include <cstdint>";
    w << indent << "#include <cstddef>";

    //--------------------------------------------------------------------------
    // Include headers for dependency modules
    // Scan all fields to find which external modules are actually referenced,
    // rather than relying on use_modules (which misses transitive usefrom).
    //--------------------------------------------------------------------------

    std::set<std::string, ci_less> needed_modules;
    for (auto &dt_name : mod.ddt_names)
    {
        auto it2 = mod.data_types.find(dt_name);
        if (it2 == mod.data_types.end())
            continue;
        auto &ddt = it2->second->derived;
        for (auto &field : ddt.fields)
        {
            if (field.data_type->tag != DataType::Tag::Derived)
                continue;
            if (is_opaque_field(field))
                continue;
            auto &fmod = field.data_type->derived.module;
            if (fmod && tolower(fmod->name) != tolower(mod.name))
                needed_modules.insert(fmod->name);
        }
    }
    for (auto &dep_mod : needed_modules)
    {
        w << indent << "#include \"" << dep_mod << "_Types.hpp\"";
    }

    w << indent;
    w << indent << "#ifdef __cplusplus";
    w << indent << "extern \"C\" {";
    w << indent << "#endif";

    //--------------------------------------------------------------------------
    // Parameters
    //--------------------------------------------------------------------------

    if (!mod.params.empty())
    {
        w << indent;
        w << indent << "// Parameters";
        for (const auto &param : mod.params)
        {
            auto type_str = cpp_type_str(*param.type);
            if (!param.value.empty())
            {
                // Convert Fortran-style values
                auto val = param.value;
                if (tolower(val) == ".true." || tolower(val) == "t")
                    val = "1";
                else if (tolower(val) == ".false." || tolower(val) == "f")
                    val = "0";

                w << indent << "static const " << type_str << " " << param.name
                  << " = " << val << ";";
            }
        }
    }

    //--------------------------------------------------------------------------
    // Struct definitions
    //--------------------------------------------------------------------------

    for (auto &dt_name : mod.ddt_names)
    {
        auto it = mod.data_types.find(dt_name);
        auto &dt = *it->second;
        if (dt.tag != DataType::Tag::Derived)
            continue;
        auto &ddt = dt.derived;

        w << indent;
        w << indent << "typedef struct " << ddt.type_fortran << " {";
        indent += "    ";

        for (const auto &field : ddt.fields)
        {
            // ---- Derived type fields ----
            if (field.data_type->tag == DataType::Tag::Derived)
            {
                if (is_opaque_field(field))
                {
                    // Opaque: void pointer
                    if (field.is_allocatable && field.rank > 0)
                    {
                        w << indent << "void* " << field.name << ";";
                        w << indent << "int32_t " << field.name << "_Len;";
                    }
                    else
                    {
                        w << indent << "void* " << field.name << ";";
                    }
                }
                else
                {
                    // Non-opaque derived type — use the struct name
                    auto &nested_name = field.data_type->derived.type_fortran;

                    if (field.is_allocatable)
                    {
                        // Allocatable array of structs
                        w << indent << nested_name << "* " << field.name << ";";
                        w << indent << "int32_t " << field.name << "_Len;";
                    }
                    else if (field.rank > 0)
                    {
                        // Fixed-size array of structs
                        std::string dims_comment;
                        int total = compute_fixed_array_size(field, dims_comment);
                        if (total > 0)
                        {
                            w << indent << nested_name << " " << field.name
                              << "[" << total << "];";
                        }
                        else
                        {
                            // Can't compute size — use pointer
                            w << indent << nested_name << "* " << field.name
                              << "; // fixed[" << dims_comment << "]";
                        }
                    }
                    else
                    {
                        // Scalar (by value)
                        w << indent << nested_name << " " << field.name << ";";
                    }
                }
                continue;
            }

            // ---- Character fields ----
            if (field.data_type->tag == DataType::Tag::Character)
            {
                int str_len = resolve_string_len(field.data_type->basic.string_len);
                if (str_len <= 0)
                    str_len = 256; // fallback for unresolvable lengths

                if (field.is_allocatable)
                {
                    // Allocatable array of strings → flat char buffer
                    w << indent << "char* " << field.name << ";";
                    w << indent << "int32_t " << field.name << "_Len;";
                    w << indent << "int32_t " << field.name << "_StrLen; // = "
                      << field.data_type->basic.string_len;
                }
                else if (field.rank == 0)
                {
                    // Scalar character
                    w << indent << "char " << field.name << "[" << str_len << "];";
                }
                else
                {
                    // Fixed-size array of strings
                    std::string dims_comment;
                    int total = compute_fixed_array_size(field, dims_comment);
                    if (total > 0)
                    {
                        w << indent << "char " << field.name
                          << "[" << total << "][" << str_len << "];";
                    }
                    else
                    {
                        w << indent << "char* " << field.name << ";";
                        w << indent << "int32_t " << field.name
                          << "_Len; // fixed[" << dims_comment << "]";
                    }
                }
                continue;
            }

            // ---- Basic type fields (Integer, Real, Logical) ----
            auto type_str = cpp_type_str(*field.data_type);

            if (field.is_allocatable)
            {
                // Allocatable array — pointer + length
                w << indent << type_str << "* " << field.name << ";";
                w << indent << "int32_t " << field.name << "_Len;";
            }
            else if (field.rank > 0)
            {
                // Fixed-size array — flatten to 1D, column-major
                std::string dims_comment;
                int total = compute_fixed_array_size(field, dims_comment);
                if (total > 0)
                {
                    w << indent << type_str << " " << field.name
                      << "[" << total << "];";
                    if (field.rank > 1)
                    {
                        w << " // " << dims_comment << ", column-major";
                    }
                }
                else
                {
                    // Can't compute — use as pointer
                    w << indent << type_str << "* " << field.name
                      << "; // fixed[" << dims_comment << "]";
                }
            }
            else
            {
                // Scalar
                w << indent << type_str << " " << field.name << ";";
            }
        }

        indent.erase(indent.size() - 4);
        w << indent << "} " << ddt.type_fortran << ";";
    }

    //--------------------------------------------------------------------------
    // File footer
    //--------------------------------------------------------------------------

    w << indent;
    w << indent << "#ifdef __cplusplus";
    w << indent << "}";
    w << indent << "#endif";
    w << indent;
}
