// VIT Test-Validate Harness
// Function: CheckValuesAreUniqueMonotonicIncreasing
// Generated by: vit test-validate
//
// Each test calls BOTH C++ and Fortran, asserts they agree.

#include <cstdio>
#include <cstring>
#include <cstdint>
#include <cmath>
#include <cfloat>
#include "vit_nwtc.h"
#include "vit_nwtc.cpp"
#include "checkvaluesareuniquemonotonicincreasing.hpp"

// --- Test infrastructure ---

struct TestResult {
    const char* name;
    bool passed;
    const char* detail;
};

// Fortran reference (via BIND(C) bridge):
extern "C" void checkvaluesareuniquemonotonicincreasing_f90(
    const double* secondVals, int n_secondVals, int8_t* result);

// Dual-call helper: calls both C++ and Fortran, returns pass/fail
static TestResult dual_call(const char* name, const double* vals, int n, bool expected) {
    // C++ call
    bool cpp_result = CheckValuesAreUniqueMonotonicIncreasing(vals, n);

    // Fortran call
    int8_t f90_result = 0;
    checkvaluesareuniquemonotonicincreasing_f90(vals, n, &f90_result);
    bool fortran_result = (f90_result != 0);

    // Check agreement
    if (cpp_result != fortran_result) {
        static char detail[256];
        snprintf(detail, sizeof(detail),
                 "C++=%s Fortran=%s (DISAGREE)",
                 cpp_result ? "true" : "false",
                 fortran_result ? "true" : "false");
        return {name, false, detail};
    }

    // Check correctness
    if (cpp_result != expected) {
        static char detail[256];
        snprintf(detail, sizeof(detail),
                 "got %s, expected %s (both agree but wrong)",
                 cpp_result ? "true" : "false",
                 expected ? "true" : "false");
        return {name, false, detail};
    }

    return {name, true, nullptr};
}

// --- Tests ---

static TestResult test_happy_path() {
    double vals[] = {1.0, 2.0, 3.0, 4.0, 5.0};
    return dual_call("happy_path_increasing", vals, 5, true);
}

static TestResult test_single_element() {
    double vals[] = {42.0};
    return dual_call("single_element", vals, 1, true);
}

static TestResult test_two_increasing() {
    double vals[] = {1.0, 2.0};
    return dual_call("two_increasing", vals, 2, true);
}

static TestResult test_two_equal() {
    double vals[] = {1.0, 1.0};
    return dual_call("two_equal", vals, 2, false);
}

static TestResult test_two_decreasing() {
    double vals[] = {2.0, 1.0};
    return dual_call("two_decreasing", vals, 2, false);
}

static TestResult test_equal_in_middle() {
    double vals[] = {1.0, 2.0, 2.0, 3.0};
    return dual_call("equal_in_middle", vals, 4, false);
}

static TestResult test_decreasing_in_middle() {
    double vals[] = {1.0, 3.0, 2.0, 4.0};
    return dual_call("decreasing_in_middle", vals, 4, false);
}

static TestResult test_failure_at_last_pair() {
    double vals[] = {1.0, 2.0, 3.0, 3.0};
    return dual_call("failure_at_last_pair", vals, 4, false);
}

static TestResult test_near_equal_within_tolerance() {
    // EqualRealNos uses 100*eps/2 relative tolerance.
    // Two values differing by less than this should be treated as equal.
    double base = 1.0;
    double eps = DBL_EPSILON;
    double vals[] = {base, base + 10.0 * eps};  // Within EqualRealNos tolerance
    return dual_call("near_equal_within_tolerance", vals, 2, false);
}

static TestResult test_large_values_increasing() {
    double vals[] = {1e10, 2e10, 3e10};
    return dual_call("large_values_increasing", vals, 3, true);
}

static TestResult test_negative_values_increasing() {
    double vals[] = {-100.0, -50.0, 0.0, 50.0};
    return dual_call("negative_values_increasing", vals, 4, true);
}

// --- Test runner ---

int main() {
    TestResult tests[] = {
        test_happy_path(),
        test_single_element(),
        test_two_increasing(),
        test_two_equal(),
        test_two_decreasing(),
        test_equal_in_middle(),
        test_decreasing_in_middle(),
        test_failure_at_last_pair(),
        test_near_equal_within_tolerance(),
        test_large_values_increasing(),
        test_negative_values_increasing(),
    };

    int n = sizeof(tests) / sizeof(tests[0]);
    int passed = 0, failed = 0;
    for (int i = 0; i < n; i++) {
        if (tests[i].passed) {
            passed++;
            printf("  PASS %s\n", tests[i].name);
        } else {
            failed++;
            printf("  FAIL %s: %s\n", tests[i].name, tests[i].detail);
        }
    }
    printf("\n%d/%d passed\n", passed, n);
    return failed > 0 ? 1 : 0;
}
