// C struct definitions for Fortran derived types.
// Auto-generated by VIT. Do not edit manually.

#ifndef VIT_TYPES_H
#define VIT_TYPES_H

#include <stdint.h>

// Auto-generated C struct for Fortran TYPE(AFI_InitInputType)
// Generated by VIT (Verified Incremental Translator)

#ifndef AFI_INITINPUTTYPE_T_H
#define AFI_INITINPUTTYPE_T_H

typedef struct {
    char FileName[1024];
    int AFTabMod;
    int InCol_Alfa;
    int InCol_Cl;
    int InCol_Cd;
    int InCol_Cm;
    int InCol_Cpmin;
    int UAMod;
} afi_initinputtype_t;

#endif // AFI_INITINPUTTYPE_T_H

#endif // VIT_TYPES_H
