// Auto-generated C wrapper for Fortran function: AFI_ComputeUACoefs
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

#include "vit_kernel_callees.h"

// User-provided C++ implementation
#include "afi_computeuacoefs.hpp"

extern "C" {
    void afi_computeuacoefs_c(afi_parametertype_view_t* p, double Re, double UserProp, afi_ua_bl_type_t* UA_BL, char* errMsg, int* errStat) {
        AFI_ComputeUACoefs(p, Re, UserProp, UA_BL, errMsg, errStat);
    }
}
