!KGEN-generated Fortran source file 
  
!Generated at : 2026-04-26 22:19:30 
!KGEN version : 0.8.1 
  
!STARTOFREGISTRYGENERATEDFILE 'UnsteadyAero_Types.f90'
! WARNING This file is generated automatically by the FAST registry.
! Do not edit.  Your changes to this file will be lost.
! FAST Registry
!*********************************************************************************************************************************
! UnsteadyAero_Types
!.................................................................................................................................
! This file is part of UnsteadyAero.
! Copyright (C) 2012-2016 National Renewable Energy Laboratory
! Licensed under the Apache License, Version 2.0 (the "License");
! you may not use this file except in compliance with the License.
! You may obtain a copy of the License at
!     http://www.apache.org/licenses/LICENSE-2.0
! Unless required by applicable law or agreed to in writing, software
! distributed under the License is distributed on an "AS IS" BASIS,
! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
! See the License for the specific language governing permissions and
! limitations under the License.
! W A R N I N G : This file was automatically generated from the FAST registry.  Changes made to this file may be lost.
!*********************************************************************************************************************************
!> This module contains the user-defined types needed in UnsteadyAero. It also contains copy, destroy, pack, and
!! unpack routines associated with each defined data type. This code is automatically generated by the FAST Registry.


!
!
!
!
!
!
!
!
!
MODULE UnsteadyAero_Types
!---------------------------------------------------------------------------------------------------------------------------------
    USE airfoilinfo_types 
    USE kgen_utils_mod
    USE tprof_mod, ONLY: tstart, tstop, tnull, tprnt 
    USE kgen_utils_mod
    IMPLICIT NONE 
! =========  UA_InitInputType  =======

! =======================
! =========  UA_InitOutputType  =======

! =======================
! =========  UA_KelvinChainType  =======

! =======================
! =========  UA_ElementContinuousStateType  =======

! =======================
! =========  UA_ContinuousStateType  =======

! =======================
! =========  UA_DiscreteStateType  =======

! =======================
! =========  UA_ConstraintStateType  =======

! =======================
! =========  UA_OtherStateType  =======

! =======================
! =========  UA_MiscVarType  =======

! =======================
! =========  UA_ParameterType  =======

! =======================
! =========  UA_InputType  =======
  TYPE, PUBLIC :: UA_InputType
    REAL(ReKi)  :: U = 0.0_ReKi      !< air velocity magnitude relative to the airfoil [m/s]
    REAL(ReKi)  :: alpha = 0.0_ReKi      !< angle of attack [rad]
    REAL(ReKi)  :: Re = 0.0_ReKi      !< Reynold's number [-]
    REAL(ReKi)  :: UserProp = 0.0      !< UserProp value for interpolating airfoil tables [-]
    REAL(ReKi) , DIMENSION(1:2)  :: v_ac = 0.0_ReKi      !< Relative fluid velocity at the aerodynamic center (UAMod=4) [m/s]
    REAL(ReKi)  :: omega = 0.0_ReKi      !< pitching/twisting rate of the airfoil section (UAMod=4) [rad/s]
  END TYPE UA_InputType
! =======================
! =========  UA_OutputType  =======

! =======================
  PUBLIC kr_unsteadyaero_types_ua_inputtype 
  PUBLIC kv_unsteadyaero_types_ua_inputtype 

    
  CONTAINS 
    


  !read state subroutine for kr_unsteadyaero_types_ua_inputtype 
  RECURSIVE SUBROUTINE kr_unsteadyaero_types_ua_inputtype(var, kgen_unit, printname, printvar) 
      TYPE(ua_inputtype), INTENT(INOUT) :: var 
      INTEGER, INTENT(IN) :: kgen_unit 
      CHARACTER(LEN=*), INTENT(IN) :: printname 
      LOGICAL, INTENT(IN), OPTIONAL :: printvar 
      LOGICAL :: kgen_istrue 
      REAL(KIND=8) :: kgen_array_sum 
        
      READ (UNIT = kgen_unit) var%u 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%u = ", var%u 
      END IF   
        
      READ (UNIT = kgen_unit) var%alpha 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%alpha = ", var%alpha 
      END IF   
        
      READ (UNIT = kgen_unit) var%re 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%re = ", var%re 
      END IF   
        
      READ (UNIT = kgen_unit) var%userprop 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%userprop = ", var%userprop 
      END IF   
        
      READ (UNIT = kgen_unit) kgen_istrue 
      IF (kgen_istrue) THEN 
          READ (UNIT = kgen_unit) kgen_array_sum 
          READ (UNIT = kgen_unit) var%v_ac 
          CALL kgen_array_sumcheck(printname // "%v_ac", kgen_array_sum, DBLE(SUM(var%v_ac, mask=(var%v_ac .eq. var%v_ac))), &
          &.TRUE.) 
          IF (PRESENT( printvar ) .AND. printvar) THEN 
              WRITE (*, *) "KGEN DEBUG: DBLE(SUM(" // printname // "%v_ac)) = ", DBLE(SUM(var%v_ac, mask=(var%v_ac .eq. &
              &var%v_ac))) 
          END IF   
      END IF   
        
      READ (UNIT = kgen_unit) var%omega 
      IF (PRESENT( printvar ) .AND. printvar) THEN 
          WRITE (*, *) "KGEN DEBUG: " // printname // "%omega = ", var%omega 
      END IF   
        
  END SUBROUTINE kr_unsteadyaero_types_ua_inputtype 
    
  !verify state subroutine for kv_unsteadyaero_types_ua_inputtype 
  RECURSIVE SUBROUTINE kv_unsteadyaero_types_ua_inputtype(varname, check_status, var, kgenref_var) 
      CHARACTER(LEN=*), INTENT(IN) :: varname 
      TYPE(check_t), INTENT(INOUT) :: check_status 
      TYPE(ua_inputtype), INTENT(IN) :: var, kgenref_var 
      TYPE(check_t) :: dtype_check_status, comp_check_status 
      INTEGER :: check_result 
      LOGICAL :: is_print = .FALSE. 
        
      real(KIND=reki) :: diff_u 
      real(KIND=reki) :: diff_alpha 
      real(KIND=reki) :: diff_re 
      real(KIND=reki) :: diff_userprop 
      INTEGER :: n_v_ac 
      real(KIND=reki) :: nrmsdiff_v_ac, rmsdiff_v_ac 
      real(KIND=reki), ALLOCATABLE :: buf1_v_ac(:), buf2_v_ac(:) 
      real(KIND=reki) :: diff_omega 
        
      check_status%numTotal = check_status%numTotal + 1 
        
      CALL kgen_init_check(dtype_check_status, rank=check_status%rank) 
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%u == kgenref_var%u) .OR. ((var%u /= var%u) .AND. (kgenref_var%u /= kgenref_var%u))) THEN
        IF (var%u /= var%u) WRITE(*, *) "localvar%u is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%u is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
          WRITE(*, *) "[VIT_FIELD] u | IDENTICAL | ", var%u, " | ", kgenref_var%u
      ELSE 
          diff_u = ABS(var%u - kgenref_var%u) 
          IF (diff_u <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%u is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
              WRITE(*, *) "[VIT_FIELD] u | IN_TOL | ", var%u, " | ", kgenref_var%u, " | ", diff_u
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%u is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
              WRITE(*, *) "[VIT_FIELD] u | OUT_TOL | ", var%u, " | ", kgenref_var%u, " | ", diff_u
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_u 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_u 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%alpha == kgenref_var%alpha) .OR. ((var%alpha /= var%alpha) .AND. (kgenref_var%alpha /= kgenref_var%alpha))) THEN
        IF (var%alpha /= var%alpha) WRITE(*, *) "localvar%alpha is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%alpha is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
          WRITE(*, *) "[VIT_FIELD] alpha | IDENTICAL | ", var%alpha, " | ", kgenref_var%alpha
      ELSE 
          diff_alpha = ABS(var%alpha - kgenref_var%alpha) 
          IF (diff_alpha <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%alpha is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
              WRITE(*, *) "[VIT_FIELD] alpha | IN_TOL | ", var%alpha, " | ", kgenref_var%alpha, " | ", diff_alpha
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%alpha is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
              WRITE(*, *) "[VIT_FIELD] alpha | OUT_TOL | ", var%alpha, " | ", kgenref_var%alpha, " | ", diff_alpha
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_alpha 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_alpha 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%re == kgenref_var%re) .OR. ((var%re /= var%re) .AND. (kgenref_var%re /= kgenref_var%re))) THEN
        IF (var%re /= var%re) WRITE(*, *) "localvar%re is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%re is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
          WRITE(*, *) "[VIT_FIELD] re | IDENTICAL | ", var%re, " | ", kgenref_var%re
      ELSE 
          diff_re = ABS(var%re - kgenref_var%re) 
          IF (diff_re <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%re is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
              WRITE(*, *) "[VIT_FIELD] re | IN_TOL | ", var%re, " | ", kgenref_var%re, " | ", diff_re
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%re is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
              WRITE(*, *) "[VIT_FIELD] re | OUT_TOL | ", var%re, " | ", kgenref_var%re, " | ", diff_re
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_re 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_re 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%userprop == kgenref_var%userprop) .OR. ((var%userprop /= var%userprop) .AND. (kgenref_var%userprop /= kgenref_var%userprop))) THEN
        IF (var%userprop /= var%userprop) WRITE(*, *) "localvar%userprop is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%userprop is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
          WRITE(*, *) "[VIT_FIELD] userprop | IDENTICAL | ", var%userprop, " | ", kgenref_var%userprop
      ELSE 
          diff_userprop = ABS(var%userprop - kgenref_var%userprop) 
          IF (diff_userprop <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%userprop is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
              WRITE(*, *) "[VIT_FIELD] userprop | IN_TOL | ", var%userprop, " | ", kgenref_var%userprop, " | ", diff_userprop
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%userprop is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
              WRITE(*, *) "[VIT_FIELD] userprop | OUT_TOL | ", var%userprop, " | ", kgenref_var%userprop, " | ", diff_userprop
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_userprop 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_userprop 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF (ALL(var%v_ac == kgenref_var%v_ac)) THEN 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%v_ac is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
          WRITE(*, *) "[VIT_ARRAY] v_ac | IDENTICAL | size=", SIZE(var%v_ac)
      ELSE 
          ALLOCATE (buf1_v_ac(SIZE(var%v_ac,dim=1))) 
          ALLOCATE (buf2_v_ac(SIZE(var%v_ac,dim=1))) 
          n_v_ac = COUNT(var%v_ac /= kgenref_var%v_ac) 
          WHERE ( ABS(kgenref_var%v_ac) > kgen_minvalue ) 
              buf1_v_ac = ((var%v_ac-kgenref_var%v_ac)/kgenref_var%v_ac)**2 
              buf2_v_ac = (var%v_ac-kgenref_var%v_ac)**2 
          ELSEWHERE 
              buf1_v_ac = (var%v_ac-kgenref_var%v_ac)**2 
              buf2_v_ac = buf1_v_ac 
          END WHERE   
          nrmsdiff_v_ac = SQRT(SUM(buf1_v_ac)/REAL(n_v_ac)) 
          rmsdiff_v_ac = SQRT(SUM(buf2_v_ac)/REAL(n_v_ac)) 
          IF (rmsdiff_v_ac > kgen_tolerance) THEN 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%v_ac is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
              WRITE(*, *) "[VIT_ARRAY] v_ac | OUT_TOL | n_diff=", n_v_ac, " | rms=", rmsdiff_v_ac
          ELSE 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%v_ac is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
              WRITE(*, *) "[VIT_ARRAY] v_ac | IN_TOL | n_diff=", n_v_ac, " | rms=", rmsdiff_v_ac
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) count( var%v_ac /= kgenref_var%v_ac), " of ", size( var%v_ac ), " elements are different." 
                  WRITE (*, *) "Average - kernel ", sum(var%v_ac)/real(size(var%v_ac)) 
                  WRITE (*, *) "Average - reference ", sum(kgenref_var%v_ac)/real(size(kgenref_var%v_ac)) 
                  WRITE (*, *) "RMS of difference is ", rmsdiff_v_ac 
                  WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_v_ac 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) count( var%v_ac /= kgenref_var%v_ac), " of ", size( var%v_ac ), " elements are different." 
                  WRITE (*, *) "Average - kernel ", sum(var%v_ac)/real(size(var%v_ac)) 
                  WRITE (*, *) "Average - reference ", sum(kgenref_var%v_ac)/real(size(kgenref_var%v_ac)) 
                  WRITE (*, *) "RMS of difference is ", rmsdiff_v_ac 
                  WRITE (*, *) "Normalized RMS of difference is ", nrmsdiff_v_ac 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      dtype_check_status%numTotal = dtype_check_status%numTotal + 1 
      IF ((var%omega == kgenref_var%omega) .OR. ((var%omega /= var%omega) .AND. (kgenref_var%omega /= kgenref_var%omega))) THEN
        IF (var%omega /= var%omega) WRITE(*, *) "localvar%omega is IDENTICAL (both NaN, uninitialized)." 
          dtype_check_status%numIdentical = dtype_check_status%numIdentical + 1 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank == 0) THEN 
                  WRITE (*, *) trim(adjustl(varname)), "%omega is IDENTICAL." 
              END IF   
          END IF   
          check_result = CHECK_IDENTICAL 
          WRITE(*, *) "[VIT_FIELD] omega | IDENTICAL | ", var%omega, " | ", kgenref_var%omega
      ELSE 
          diff_omega = ABS(var%omega - kgenref_var%omega) 
          IF (diff_omega <= kgen_tolerance) THEN 
              dtype_check_status%numInTol = dtype_check_status%numInTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%omega is NOT IDENTICAL(within tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_IN_TOL 
              WRITE(*, *) "[VIT_FIELD] omega | IN_TOL | ", var%omega, " | ", kgenref_var%omega, " | ", diff_omega
          ELSE 
              dtype_check_status%numOutTol = dtype_check_status%numOutTol + 1 
              IF (kgen_verboseLevel > 1) THEN 
                  IF (check_status%rank == 0) THEN 
                      WRITE (*, *) trim(adjustl(varname)), "%omega is NOT IDENTICAL(out of tolerance)." 
                  END IF   
              END IF   
              check_result = CHECK_OUT_TOL 
              WRITE(*, *) "[VIT_FIELD] omega | OUT_TOL | ", var%omega, " | ", kgenref_var%omega, " | ", diff_omega
          END IF   
      END IF   
      IF (check_result == CHECK_IDENTICAL) THEN 
          CONTINUE 
      ELSE IF (check_result == CHECK_OUT_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_omega 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      ELSE IF (check_result == CHECK_IN_TOL) THEN 
          IF (kgen_verboseLevel > 2) THEN 
              IF (check_status%rank ==0) THEN 
                  WRITE (*, *) "Difference is ", diff_omega 
                  WRITE (*, *) "" 
              END IF   
          END IF   
      END IF   
        
      IF (dtype_check_status%numTotal == dtype_check_status%numIdentical) THEN 
          check_status%numIdentical = check_status%numIdentical + 1 
      ELSE IF (dtype_check_status%numOutTol > 0) THEN 
          check_status%numOutTol = check_status%numOutTol + 1 
      ELSE IF (dtype_check_status%numInTol > 0) THEN 
          check_status%numInTol = check_status%numInTol + 1 
      END IF   
  END SUBROUTINE kv_unsteadyaero_types_ua_inputtype 
    
END MODULE UnsteadyAero_Types
!ENDOFREGISTRYGENERATEDFILE
