// Auto-generated C wrapper for Fortran function: ComputeUA360_CnOffset
// Generated by VIT (Verified Incremental Translator)

#include "vit_types.h"

// User-provided C++ implementation
#include "computeua360_cnoffset.hpp"

extern "C" {
    double computeua360_cnoffset_c(afi_table_type_view_t* p, double* cn_cl, int n_cn_cl, int Row, int iLower) {
        return ComputeUA360_CnOffset(p, cn_cl, n_cn_cl, Row, iLower);
    }
}
